// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_context_compaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentContextCompaction = `-- name: CreateAgentContextCompaction :one
INSERT INTO agent_context_compaction (
    workspace_id,
    thread_id,
    task_id,
    role,
    mode,
    trigger,
    semantic_key,
    source_seq_start,
    source_seq_end,
    source_message_ids,
    source_media_refs,
    original_token_estimate,
    compacted_token_estimate,
    original_bytes,
    summary,
    detail_files,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
) RETURNING id, workspace_id, thread_id, task_id, role, mode, trigger, semantic_key, source_seq_start, source_seq_end, source_message_ids, source_media_refs, original_token_estimate, compacted_token_estimate, original_bytes, summary, detail_files, payload, created_at
`

type CreateAgentContextCompactionParams struct {
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	ThreadID               pgtype.UUID `json:"thread_id"`
	TaskID                 pgtype.UUID `json:"task_id"`
	Role                   string      `json:"role"`
	Mode                   string      `json:"mode"`
	Trigger                string      `json:"trigger"`
	SemanticKey            string      `json:"semantic_key"`
	SourceSeqStart         int64       `json:"source_seq_start"`
	SourceSeqEnd           int64       `json:"source_seq_end"`
	SourceMessageIds       []byte      `json:"source_message_ids"`
	SourceMediaRefs        []byte      `json:"source_media_refs"`
	OriginalTokenEstimate  int64       `json:"original_token_estimate"`
	CompactedTokenEstimate int64       `json:"compacted_token_estimate"`
	OriginalBytes          int64       `json:"original_bytes"`
	Summary                string      `json:"summary"`
	DetailFiles            []byte      `json:"detail_files"`
	Payload                []byte      `json:"payload"`
}

func (q *Queries) CreateAgentContextCompaction(ctx context.Context, arg CreateAgentContextCompactionParams) (AgentContextCompaction, error) {
	row := q.db.QueryRow(ctx, createAgentContextCompaction,
		arg.WorkspaceID,
		arg.ThreadID,
		arg.TaskID,
		arg.Role,
		arg.Mode,
		arg.Trigger,
		arg.SemanticKey,
		arg.SourceSeqStart,
		arg.SourceSeqEnd,
		arg.SourceMessageIds,
		arg.SourceMediaRefs,
		arg.OriginalTokenEstimate,
		arg.CompactedTokenEstimate,
		arg.OriginalBytes,
		arg.Summary,
		arg.DetailFiles,
		arg.Payload,
	)
	var i AgentContextCompaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.Role,
		&i.Mode,
		&i.Trigger,
		&i.SemanticKey,
		&i.SourceSeqStart,
		&i.SourceSeqEnd,
		&i.SourceMessageIds,
		&i.SourceMediaRefs,
		&i.OriginalTokenEstimate,
		&i.CompactedTokenEstimate,
		&i.OriginalBytes,
		&i.Summary,
		&i.DetailFiles,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentContextCompactionBySemanticKey = `-- name: GetAgentContextCompactionBySemanticKey :one
SELECT id, workspace_id, thread_id, task_id, role, mode, trigger, semantic_key, source_seq_start, source_seq_end, source_message_ids, source_media_refs, original_token_estimate, compacted_token_estimate, original_bytes, summary, detail_files, payload, created_at
FROM agent_context_compaction
WHERE workspace_id = $1
  AND semantic_key = $2
LIMIT 1
`

type GetAgentContextCompactionBySemanticKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SemanticKey string      `json:"semantic_key"`
}

func (q *Queries) GetAgentContextCompactionBySemanticKey(ctx context.Context, arg GetAgentContextCompactionBySemanticKeyParams) (AgentContextCompaction, error) {
	row := q.db.QueryRow(ctx, getAgentContextCompactionBySemanticKey, arg.WorkspaceID, arg.SemanticKey)
	var i AgentContextCompaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.Role,
		&i.Mode,
		&i.Trigger,
		&i.SemanticKey,
		&i.SourceSeqStart,
		&i.SourceSeqEnd,
		&i.SourceMessageIds,
		&i.SourceMediaRefs,
		&i.OriginalTokenEstimate,
		&i.CompactedTokenEstimate,
		&i.OriginalBytes,
		&i.Summary,
		&i.DetailFiles,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const linkAgentMessageCompaction = `-- name: LinkAgentMessageCompaction :one
INSERT INTO agent_message_compaction (
    message_id,
    compaction_id,
    compacted_role
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (message_id) DO UPDATE
SET compaction_id = EXCLUDED.compaction_id,
    compacted_role = EXCLUDED.compacted_role,
    compacted_at = now()
RETURNING message_id, compaction_id, compacted_role, compacted_at
`

type LinkAgentMessageCompactionParams struct {
	MessageID     pgtype.UUID `json:"message_id"`
	CompactionID  pgtype.UUID `json:"compaction_id"`
	CompactedRole string      `json:"compacted_role"`
}

func (q *Queries) LinkAgentMessageCompaction(ctx context.Context, arg LinkAgentMessageCompactionParams) (AgentMessageCompaction, error) {
	row := q.db.QueryRow(ctx, linkAgentMessageCompaction, arg.MessageID, arg.CompactionID, arg.CompactedRole)
	var i AgentMessageCompaction
	err := row.Scan(
		&i.MessageID,
		&i.CompactionID,
		&i.CompactedRole,
		&i.CompactedAt,
	)
	return i, err
}

const listAgentContextCompactionsByThread = `-- name: ListAgentContextCompactionsByThread :many
SELECT id, workspace_id, thread_id, task_id, role, mode, trigger, semantic_key, source_seq_start, source_seq_end, source_message_ids, source_media_refs, original_token_estimate, compacted_token_estimate, original_bytes, summary, detail_files, payload, created_at
FROM agent_context_compaction
WHERE workspace_id = $1
  AND thread_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAgentContextCompactionsByThreadParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	RowLimit    int32       `json:"row_limit"`
}

func (q *Queries) ListAgentContextCompactionsByThread(ctx context.Context, arg ListAgentContextCompactionsByThreadParams) ([]AgentContextCompaction, error) {
	rows, err := q.db.Query(ctx, listAgentContextCompactionsByThread, arg.WorkspaceID, arg.ThreadID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentContextCompaction{}
	for rows.Next() {
		var i AgentContextCompaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.TaskID,
			&i.Role,
			&i.Mode,
			&i.Trigger,
			&i.SemanticKey,
			&i.SourceSeqStart,
			&i.SourceSeqEnd,
			&i.SourceMessageIds,
			&i.SourceMediaRefs,
			&i.OriginalTokenEstimate,
			&i.CompactedTokenEstimate,
			&i.OriginalBytes,
			&i.Summary,
			&i.DetailFiles,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentContextCompactionsByWorkspace = `-- name: ListAgentContextCompactionsByWorkspace :many
SELECT id, workspace_id, thread_id, task_id, role, mode, trigger, semantic_key, source_seq_start, source_seq_end, source_message_ids, source_media_refs, original_token_estimate, compacted_token_estimate, original_bytes, summary, detail_files, payload, created_at
FROM agent_context_compaction
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAgentContextCompactionsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RowLimit    int32       `json:"row_limit"`
}

func (q *Queries) ListAgentContextCompactionsByWorkspace(ctx context.Context, arg ListAgentContextCompactionsByWorkspaceParams) ([]AgentContextCompaction, error) {
	rows, err := q.db.Query(ctx, listAgentContextCompactionsByWorkspace, arg.WorkspaceID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentContextCompaction{}
	for rows.Next() {
		var i AgentContextCompaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.TaskID,
			&i.Role,
			&i.Mode,
			&i.Trigger,
			&i.SemanticKey,
			&i.SourceSeqStart,
			&i.SourceSeqEnd,
			&i.SourceMessageIds,
			&i.SourceMediaRefs,
			&i.OriginalTokenEstimate,
			&i.CompactedTokenEstimate,
			&i.OriginalBytes,
			&i.Summary,
			&i.DetailFiles,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactedMessageIDsByThread = `-- name: ListCompactedMessageIDsByThread :many
SELECT
    agent_message_compaction.message_id,
    agent_message_compaction.compaction_id,
    agent_message_compaction.compacted_role,
    agent_message_compaction.compacted_at,
    agent_context_compaction.semantic_key,
    agent_context_compaction.summary,
    agent_context_compaction.detail_files
FROM agent_message_compaction
JOIN agent_message ON agent_message.id = agent_message_compaction.message_id
JOIN agent_context_compaction ON agent_context_compaction.id = agent_message_compaction.compaction_id
WHERE agent_message.workspace_id = $1
  AND agent_message.thread_id = $2
`

type ListCompactedMessageIDsByThreadParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
}

type ListCompactedMessageIDsByThreadRow struct {
	MessageID     pgtype.UUID        `json:"message_id"`
	CompactionID  pgtype.UUID        `json:"compaction_id"`
	CompactedRole string             `json:"compacted_role"`
	CompactedAt   pgtype.Timestamptz `json:"compacted_at"`
	SemanticKey   string             `json:"semantic_key"`
	Summary       string             `json:"summary"`
	DetailFiles   []byte             `json:"detail_files"`
}

func (q *Queries) ListCompactedMessageIDsByThread(ctx context.Context, arg ListCompactedMessageIDsByThreadParams) ([]ListCompactedMessageIDsByThreadRow, error) {
	rows, err := q.db.Query(ctx, listCompactedMessageIDsByThread, arg.WorkspaceID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompactedMessageIDsByThreadRow{}
	for rows.Next() {
		var i ListCompactedMessageIDsByThreadRow
		if err := rows.Scan(
			&i.MessageID,
			&i.CompactionID,
			&i.CompactedRole,
			&i.CompactedAt,
			&i.SemanticKey,
			&i.Summary,
			&i.DetailFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAgentContextCompactions = `-- name: SearchAgentContextCompactions :many
SELECT id, workspace_id, thread_id, task_id, role, mode, trigger, semantic_key, source_seq_start, source_seq_end, source_message_ids, source_media_refs, original_token_estimate, compacted_token_estimate, original_bytes, summary, detail_files, payload, created_at
FROM agent_context_compaction
WHERE workspace_id = $1
  AND ($2::uuid IS NULL OR thread_id = $2)
  AND (
      semantic_key = $3::text
      OR summary ILIKE '%' || $3::text || '%'
      OR payload::text ILIKE '%' || $3::text || '%'
      OR source_media_refs::text ILIKE '%' || $3::text || '%'
  )
ORDER BY created_at DESC
LIMIT $4
`

type SearchAgentContextCompactionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	Query       string      `json:"query"`
	RowLimit    int32       `json:"row_limit"`
}

func (q *Queries) SearchAgentContextCompactions(ctx context.Context, arg SearchAgentContextCompactionsParams) ([]AgentContextCompaction, error) {
	rows, err := q.db.Query(ctx, searchAgentContextCompactions,
		arg.WorkspaceID,
		arg.ThreadID,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentContextCompaction{}
	for rows.Next() {
		var i AgentContextCompaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.TaskID,
			&i.Role,
			&i.Mode,
			&i.Trigger,
			&i.SemanticKey,
			&i.SourceSeqStart,
			&i.SourceSeqEnd,
			&i.SourceMessageIds,
			&i.SourceMediaRefs,
			&i.OriginalTokenEstimate,
			&i.CompactedTokenEstimate,
			&i.OriginalBytes,
			&i.Summary,
			&i.DetailFiles,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
