// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_canvas_layout.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAgentCanvasLayoutsByWorkspace = `-- name: ListAgentCanvasLayoutsByWorkspace :many
SELECT id, workspace_id, object_type, object_id, canvas_x, canvas_y, metadata, created_at, updated_at
FROM agent_canvas_layout
WHERE workspace_id = $1
ORDER BY object_type, updated_at
`

func (q *Queries) ListAgentCanvasLayoutsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]AgentCanvasLayout, error) {
	rows, err := q.db.Query(ctx, listAgentCanvasLayoutsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCanvasLayout{}
	for rows.Next() {
		var i AgentCanvasLayout
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ObjectType,
			&i.ObjectID,
			&i.CanvasX,
			&i.CanvasY,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentCanvasLayout = `-- name: UpsertAgentCanvasLayout :one
INSERT INTO agent_canvas_layout (
    workspace_id,
    object_type,
    object_id,
    canvas_x,
    canvas_y
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (workspace_id, object_type, object_id)
DO UPDATE SET
    canvas_x = EXCLUDED.canvas_x,
    canvas_y = EXCLUDED.canvas_y,
    updated_at = now()
RETURNING id, workspace_id, object_type, object_id, canvas_x, canvas_y, metadata, created_at, updated_at
`

type UpsertAgentCanvasLayoutParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ObjectType  string      `json:"object_type"`
	ObjectID    pgtype.UUID `json:"object_id"`
	CanvasX     float32     `json:"canvas_x"`
	CanvasY     float32     `json:"canvas_y"`
}

func (q *Queries) UpsertAgentCanvasLayout(ctx context.Context, arg UpsertAgentCanvasLayoutParams) (AgentCanvasLayout, error) {
	row := q.db.QueryRow(ctx, upsertAgentCanvasLayout,
		arg.WorkspaceID,
		arg.ObjectType,
		arg.ObjectID,
		arg.CanvasX,
		arg.CanvasY,
	)
	var i AgentCanvasLayout
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ObjectType,
		&i.ObjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
