// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentTask = `-- name: CreateAgentTask :one
WITH proposed AS (
    SELECT gen_random_uuid() AS id
)
INSERT INTO agent_task (
    id,
    workspace_id,
    thread_id,
    role,
    scope_type,
    scope_id,
    task_type,
    max_attempts,
    input,
    render_plan_id,
    semantic_key,
    display_name
)
SELECT
    proposed.id,
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    COALESCE(
        NULLIF($10::text, ''),
        $3 || '.' || $4 || '.' || left(COALESCE($5::uuid::text, $1::uuid::text), 8) || '.' || $6 || '.' || left(proposed.id::text, 8)
    ),
    COALESCE(
        NULLIF($11::text, ''),
        $3 || ' ' || $6
    )
FROM proposed
RETURNING id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
`

type CreateAgentTaskParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ThreadID     pgtype.UUID `json:"thread_id"`
	Role         string      `json:"role"`
	ScopeType    string      `json:"scope_type"`
	ScopeID      pgtype.UUID `json:"scope_id"`
	TaskType     string      `json:"task_type"`
	MaxAttempts  int32       `json:"max_attempts"`
	Input        []byte      `json:"input"`
	RenderPlanID pgtype.UUID `json:"render_plan_id"`
	SemanticKey  string      `json:"semantic_key"`
	DisplayName  string      `json:"display_name"`
}

func (q *Queries) CreateAgentTask(ctx context.Context, arg CreateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, createAgentTask,
		arg.WorkspaceID,
		arg.ThreadID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
		arg.TaskType,
		arg.MaxAttempts,
		arg.Input,
		arg.RenderPlanID,
		arg.SemanticKey,
		arg.DisplayName,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getAgentTaskByID = `-- name: GetAgentTaskByID :one
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE id = $1
`

func (q *Queries) GetAgentTaskByID(ctx context.Context, id pgtype.UUID) (AgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTaskByID, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const listActiveAgentTasksByWorkspace = `-- name: ListActiveAgentTasksByWorkspace :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE workspace_id = $1
  AND status IN ('queued', 'running', 'waiting_for_user')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAgentTasksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listActiveAgentTasksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasksByWorkspace = `-- name: ListAgentTasksByWorkspace :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAgentTasksByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListAgentTasksByWorkspace(ctx context.Context, arg ListAgentTasksByWorkspaceParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasksByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasksByWorkspaceStatus = `-- name: ListAgentTasksByWorkspaceStatus :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE workspace_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type ListAgentTasksByWorkspaceStatusParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Status      string      `json:"status"`
}

func (q *Queries) ListAgentTasksByWorkspaceStatus(ctx context.Context, arg ListAgentTasksByWorkspaceStatusParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasksByWorkspaceStatus, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedComposerTasksAcrossWorkspaces = `-- name: ListQueuedComposerTasksAcrossWorkspaces :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE role = 'composer'
  AND task_type = 'composer_turn'
  AND status = 'queued'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListQueuedComposerTasksAcrossWorkspaces(ctx context.Context, limit int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listQueuedComposerTasksAcrossWorkspaces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedCraftsmanTasksAcrossWorkspaces = `-- name: ListQueuedCraftsmanTasksAcrossWorkspaces :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE role = 'craftsman'
  AND task_type = 'craftsman_turn'
  AND status = 'queued'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListQueuedCraftsmanTasksAcrossWorkspaces(ctx context.Context, limit int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listQueuedCraftsmanTasksAcrossWorkspaces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedProducerTasks = `-- name: ListQueuedProducerTasks :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE workspace_id = $1
  AND role = 'producer'
  AND task_type = 'producer_turn'
  AND status = 'queued'
ORDER BY created_at ASC
LIMIT $2
`

type ListQueuedProducerTasksParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListQueuedProducerTasks(ctx context.Context, arg ListQueuedProducerTasksParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listQueuedProducerTasks, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedProducerTasksAcrossWorkspaces = `-- name: ListQueuedProducerTasksAcrossWorkspaces :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE role = 'producer'
  AND task_type = 'producer_turn'
  AND status = 'queued'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListQueuedProducerTasksAcrossWorkspaces(ctx context.Context, limit int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listQueuedProducerTasksAcrossWorkspaces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedReviewerTasksAcrossWorkspaces = `-- name: ListQueuedReviewerTasksAcrossWorkspaces :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE role = 'reviewer'
  AND task_type = 'reviewer_turn'
  AND status = 'queued'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListQueuedReviewerTasksAcrossWorkspaces(ctx context.Context, limit int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listQueuedReviewerTasksAcrossWorkspaces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedWorkerTasksAcrossWorkspaces = `-- name: ListQueuedWorkerTasksAcrossWorkspaces :many
SELECT id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
FROM agent_task
WHERE role = 'worker'
  AND task_type = 'worker_generation'
  AND status = 'queued'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListQueuedWorkerTasksAcrossWorkspaces(ctx context.Context, limit int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listQueuedWorkerTasksAcrossWorkspaces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.TaskType,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RenderPlanID,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentTaskCancelled = `-- name: MarkAgentTaskCancelled :one
UPDATE agent_task
SET status = 'cancelled',
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
`

func (q *Queries) MarkAgentTaskCancelled(ctx context.Context, id pgtype.UUID) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskCancelled, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markAgentTaskFailed = `-- name: MarkAgentTaskFailed :one
UPDATE agent_task
SET status = 'failed',
    error_code = $2,
    error_message = $3,
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
`

type MarkAgentTaskFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkAgentTaskFailed(ctx context.Context, arg MarkAgentTaskFailedParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskFailed, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markAgentTaskRunning = `-- name: MarkAgentTaskRunning :one
UPDATE agent_task
SET status = 'running',
    attempt = attempt + 1,
    started_at = COALESCE(started_at, now()),
    error_code = NULL,
    error_message = NULL
WHERE id = $1
  AND status = 'queued'
RETURNING id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
`

func (q *Queries) MarkAgentTaskRunning(ctx context.Context, id pgtype.UUID) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskRunning, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markAgentTaskSucceeded = `-- name: MarkAgentTaskSucceeded :one
UPDATE agent_task
SET status = 'succeeded',
    output = $2,
    error_code = NULL,
    error_message = NULL,
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
`

type MarkAgentTaskSucceededParams struct {
	ID     pgtype.UUID `json:"id"`
	Output []byte      `json:"output"`
}

func (q *Queries) MarkAgentTaskSucceeded(ctx context.Context, arg MarkAgentTaskSucceededParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskSucceeded, arg.ID, arg.Output)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markAgentTaskWaitingForUser = `-- name: MarkAgentTaskWaitingForUser :one
UPDATE agent_task
SET status = 'waiting_for_user'
WHERE id = $1
RETURNING id, workspace_id, thread_id, role, scope_type, scope_id, task_type, status, attempt, max_attempts, input, output, error_code, error_message, created_at, started_at, completed_at, render_plan_id, semantic_key, display_name
`

func (q *Queries) MarkAgentTaskWaitingForUser(ctx context.Context, id pgtype.UUID) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskWaitingForUser, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.TaskType,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RenderPlanID,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}
