// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_thread.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentThread = `-- name: CreateAgentThread :one
INSERT INTO agent_thread (
    workspace_id,
    role,
    scope_type,
    scope_id,
    runtime_provider,
    runtime_agent_name,
    summary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
`

type CreateAgentThreadParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	Role             string      `json:"role"`
	ScopeType        string      `json:"scope_type"`
	ScopeID          pgtype.UUID `json:"scope_id"`
	RuntimeProvider  string      `json:"runtime_provider"`
	RuntimeAgentName string      `json:"runtime_agent_name"`
	Summary          string      `json:"summary"`
}

func (q *Queries) CreateAgentThread(ctx context.Context, arg CreateAgentThreadParams) (AgentThread, error) {
	row := q.db.QueryRow(ctx, createAgentThread,
		arg.WorkspaceID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
		arg.RuntimeProvider,
		arg.RuntimeAgentName,
		arg.Summary,
	)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAgentThreadByScope = `-- name: GetActiveAgentThreadByScope :one
SELECT id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
FROM agent_thread
WHERE workspace_id = $1
  AND role = $2
  AND scope_type = $3
  AND scope_id = $4
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveAgentThreadByScopeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Role        string      `json:"role"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     pgtype.UUID `json:"scope_id"`
}

func (q *Queries) GetActiveAgentThreadByScope(ctx context.Context, arg GetActiveAgentThreadByScopeParams) (AgentThread, error) {
	row := q.db.QueryRow(ctx, getActiveAgentThreadByScope,
		arg.WorkspaceID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
	)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveComposerThreadByWorkspace = `-- name: GetActiveComposerThreadByWorkspace :one
SELECT id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
FROM agent_thread
WHERE workspace_id = $1
  AND role = 'composer'
  AND scope_type = 'final_output'
  AND scope_id IS NULL
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveComposerThreadByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (AgentThread, error) {
	row := q.db.QueryRow(ctx, getActiveComposerThreadByWorkspace, workspaceID)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProducerThreadByWorkspace = `-- name: GetActiveProducerThreadByWorkspace :one
SELECT id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
FROM agent_thread
WHERE workspace_id = $1
  AND role = 'producer'
  AND scope_type = 'workspace'
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveProducerThreadByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (AgentThread, error) {
	row := q.db.QueryRow(ctx, getActiveProducerThreadByWorkspace, workspaceID)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentThreadByID = `-- name: GetAgentThreadByID :one
SELECT id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
FROM agent_thread
WHERE id = $1
`

func (q *Queries) GetAgentThreadByID(ctx context.Context, id pgtype.UUID) (AgentThread, error) {
	row := q.db.QueryRow(ctx, getAgentThreadByID, id)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentThreadsByWorkspace = `-- name: ListAgentThreadsByWorkspace :many
SELECT id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
FROM agent_thread
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAgentThreadsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]AgentThread, error) {
	rows, err := q.db.Query(ctx, listAgentThreadsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentThread{}
	for rows.Next() {
		var i AgentThread
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.RuntimeProvider,
			&i.RuntimeAgentName,
			&i.CurrentCheckpointKey,
			&i.Status,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentThreadCheckpoint = `-- name: SetAgentThreadCheckpoint :one
UPDATE agent_thread
SET current_checkpoint_key = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
`

type SetAgentThreadCheckpointParams struct {
	ID                   pgtype.UUID `json:"id"`
	CurrentCheckpointKey pgtype.Text `json:"current_checkpoint_key"`
}

func (q *Queries) SetAgentThreadCheckpoint(ctx context.Context, arg SetAgentThreadCheckpointParams) (AgentThread, error) {
	row := q.db.QueryRow(ctx, setAgentThreadCheckpoint, arg.ID, arg.CurrentCheckpointKey)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentThreadStatus = `-- name: UpdateAgentThreadStatus :one
UPDATE agent_thread
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, role, scope_type, scope_id, runtime_provider, runtime_agent_name, current_checkpoint_key, status, summary, created_at, updated_at
`

type UpdateAgentThreadStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAgentThreadStatus(ctx context.Context, arg UpdateAgentThreadStatusParams) (AgentThread, error) {
	row := q.db.QueryRow(ctx, updateAgentThreadStatus, arg.ID, arg.Status)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.RuntimeProvider,
		&i.RuntimeAgentName,
		&i.CurrentCheckpointKey,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
