// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_canvas_detail.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentCanvasArtifactIssueByID = `-- name: GetAgentCanvasArtifactIssueByID :one
SELECT id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
FROM artifact_issue
WHERE id = $1
  AND workspace_id = $2
`

type GetAgentCanvasArtifactIssueByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentCanvasArtifactIssueByID(ctx context.Context, arg GetAgentCanvasArtifactIssueByIDParams) (ArtifactIssue, error) {
	row := q.db.QueryRow(ctx, getAgentCanvasArtifactIssueByID, arg.ID, arg.WorkspaceID)
	var i ArtifactIssue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReviewRecordID,
		&i.Dimension,
		&i.Severity,
		&i.Status,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.Title,
		&i.Description,
		&i.Evidence,
		&i.SuggestedFix,
		&i.FixHint,
		&i.RequiresUserConfirmation,
		&i.SupersededByIssueID,
		&i.ResolvedByReviewRecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentCanvasKeyElementByID = `-- name: GetAgentCanvasKeyElementByID :one
SELECT id, workspace_id, client_key, element_type, name, description, source_type, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at
FROM key_element
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
`

type GetAgentCanvasKeyElementByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentCanvasKeyElementByID(ctx context.Context, arg GetAgentCanvasKeyElementByIDParams) (KeyElement, error) {
	row := q.db.QueryRow(ctx, getAgentCanvasKeyElementByID, arg.ID, arg.WorkspaceID)
	var i KeyElement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.ElementType,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentCanvasSceneByID = `-- name: GetAgentCanvasSceneByID :one
SELECT id, workspace_id, client_key, sort_order, title, description, location, mood, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at
FROM scene
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
`

type GetAgentCanvasSceneByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentCanvasSceneByID(ctx context.Context, arg GetAgentCanvasSceneByIDParams) (Scene, error) {
	row := q.db.QueryRow(ctx, getAgentCanvasSceneByID, arg.ID, arg.WorkspaceID)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Mood,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
