// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentEvent = `-- name: CreateAgentEvent :one
INSERT INTO agent_event (
    workspace_id,
    thread_id,
    task_id,
    event_type,
    source_role,
    target_role,
    scope,
    payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, workspace_id, thread_id, task_id, event_type, source_role, target_role, scope, payload, status, created_at, handled_at
`

type CreateAgentEventParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	TaskID      pgtype.UUID `json:"task_id"`
	EventType   string      `json:"event_type"`
	SourceRole  string      `json:"source_role"`
	TargetRole  pgtype.Text `json:"target_role"`
	Scope       []byte      `json:"scope"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) CreateAgentEvent(ctx context.Context, arg CreateAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRow(ctx, createAgentEvent,
		arg.WorkspaceID,
		arg.ThreadID,
		arg.TaskID,
		arg.EventType,
		arg.SourceRole,
		arg.TargetRole,
		arg.Scope,
		arg.Payload,
	)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.EventType,
		&i.SourceRole,
		&i.TargetRole,
		&i.Scope,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.HandledAt,
	)
	return i, err
}

const getAgentEventByID = `-- name: GetAgentEventByID :one
SELECT id, workspace_id, thread_id, task_id, event_type, source_role, target_role, scope, payload, status, created_at, handled_at
FROM agent_event
WHERE id = $1
`

func (q *Queries) GetAgentEventByID(ctx context.Context, id pgtype.UUID) (AgentEvent, error) {
	row := q.db.QueryRow(ctx, getAgentEventByID, id)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.EventType,
		&i.SourceRole,
		&i.TargetRole,
		&i.Scope,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.HandledAt,
	)
	return i, err
}

const getAgentEventForWorkspace = `-- name: GetAgentEventForWorkspace :one
SELECT id, workspace_id, thread_id, task_id, event_type, source_role, target_role, scope, payload, status, created_at, handled_at
FROM agent_event
WHERE id = $1
  AND workspace_id = $2
`

type GetAgentEventForWorkspaceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentEventForWorkspace(ctx context.Context, arg GetAgentEventForWorkspaceParams) (AgentEvent, error) {
	row := q.db.QueryRow(ctx, getAgentEventForWorkspace, arg.ID, arg.WorkspaceID)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.EventType,
		&i.SourceRole,
		&i.TargetRole,
		&i.Scope,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.HandledAt,
	)
	return i, err
}

const listAgentEventsByWorkspaceStatus = `-- name: ListAgentEventsByWorkspaceStatus :many
SELECT id, workspace_id, thread_id, task_id, event_type, source_role, target_role, scope, payload, status, created_at, handled_at
FROM agent_event
WHERE workspace_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type ListAgentEventsByWorkspaceStatusParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Status      string      `json:"status"`
}

func (q *Queries) ListAgentEventsByWorkspaceStatus(ctx context.Context, arg ListAgentEventsByWorkspaceStatusParams) ([]AgentEvent, error) {
	rows, err := q.db.Query(ctx, listAgentEventsByWorkspaceStatus, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.TaskID,
			&i.EventType,
			&i.SourceRole,
			&i.TargetRole,
			&i.Scope,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.HandledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentEventHandled = `-- name: MarkAgentEventHandled :one
UPDATE agent_event
SET status = 'handled',
    handled_at = now()
WHERE id = $1
RETURNING id, workspace_id, thread_id, task_id, event_type, source_role, target_role, scope, payload, status, created_at, handled_at
`

func (q *Queries) MarkAgentEventHandled(ctx context.Context, id pgtype.UUID) (AgentEvent, error) {
	row := q.db.QueryRow(ctx, markAgentEventHandled, id)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.EventType,
		&i.SourceRole,
		&i.TargetRole,
		&i.Scope,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.HandledAt,
	)
	return i, err
}
