// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_issue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifactIssue = `-- name: CreateArtifactIssue :one
INSERT INTO artifact_issue (
    workspace_id,
    review_record_id,
    dimension,
    severity,
    status,
    target_object_type,
    target_object_id,
    title,
    description,
    evidence,
    suggested_fix,
    fix_hint,
    requires_user_confirmation
) VALUES (
    $1, $2, $3, $4, 'open',
    $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
`

type CreateArtifactIssueParams struct {
	WorkspaceID              pgtype.UUID `json:"workspace_id"`
	ReviewRecordID           pgtype.UUID `json:"review_record_id"`
	Dimension                string      `json:"dimension"`
	Severity                 string      `json:"severity"`
	TargetObjectType         string      `json:"target_object_type"`
	TargetObjectID           pgtype.UUID `json:"target_object_id"`
	Title                    string      `json:"title"`
	Description              string      `json:"description"`
	Evidence                 string      `json:"evidence"`
	SuggestedFix             string      `json:"suggested_fix"`
	FixHint                  string      `json:"fix_hint"`
	RequiresUserConfirmation bool        `json:"requires_user_confirmation"`
}

func (q *Queries) CreateArtifactIssue(ctx context.Context, arg CreateArtifactIssueParams) (ArtifactIssue, error) {
	row := q.db.QueryRow(ctx, createArtifactIssue,
		arg.WorkspaceID,
		arg.ReviewRecordID,
		arg.Dimension,
		arg.Severity,
		arg.TargetObjectType,
		arg.TargetObjectID,
		arg.Title,
		arg.Description,
		arg.Evidence,
		arg.SuggestedFix,
		arg.FixHint,
		arg.RequiresUserConfirmation,
	)
	var i ArtifactIssue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReviewRecordID,
		&i.Dimension,
		&i.Severity,
		&i.Status,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.Title,
		&i.Description,
		&i.Evidence,
		&i.SuggestedFix,
		&i.FixHint,
		&i.RequiresUserConfirmation,
		&i.SupersededByIssueID,
		&i.ResolvedByReviewRecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactIssuesByReviewRecord = `-- name: ListArtifactIssuesByReviewRecord :many
SELECT id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
FROM artifact_issue
WHERE review_record_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactIssuesByReviewRecord(ctx context.Context, reviewRecordID pgtype.UUID) ([]ArtifactIssue, error) {
	rows, err := q.db.Query(ctx, listArtifactIssuesByReviewRecord, reviewRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactIssue{}
	for rows.Next() {
		var i ArtifactIssue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReviewRecordID,
			&i.Dimension,
			&i.Severity,
			&i.Status,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.SuggestedFix,
			&i.FixHint,
			&i.RequiresUserConfirmation,
			&i.SupersededByIssueID,
			&i.ResolvedByReviewRecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactIssuesByTarget = `-- name: ListArtifactIssuesByTarget :many
SELECT id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
FROM artifact_issue
WHERE target_object_type = $1
  AND target_object_id = $2
ORDER BY created_at DESC
`

type ListArtifactIssuesByTargetParams struct {
	TargetObjectType string      `json:"target_object_type"`
	TargetObjectID   pgtype.UUID `json:"target_object_id"`
}

func (q *Queries) ListArtifactIssuesByTarget(ctx context.Context, arg ListArtifactIssuesByTargetParams) ([]ArtifactIssue, error) {
	rows, err := q.db.Query(ctx, listArtifactIssuesByTarget, arg.TargetObjectType, arg.TargetObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactIssue{}
	for rows.Next() {
		var i ArtifactIssue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReviewRecordID,
			&i.Dimension,
			&i.Severity,
			&i.Status,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.SuggestedFix,
			&i.FixHint,
			&i.RequiresUserConfirmation,
			&i.SupersededByIssueID,
			&i.ResolvedByReviewRecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactIssuesByWorkspace = `-- name: ListArtifactIssuesByWorkspace :many
SELECT id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
FROM artifact_issue
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListArtifactIssuesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListArtifactIssuesByWorkspace(ctx context.Context, arg ListArtifactIssuesByWorkspaceParams) ([]ArtifactIssue, error) {
	rows, err := q.db.Query(ctx, listArtifactIssuesByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactIssue{}
	for rows.Next() {
		var i ArtifactIssue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReviewRecordID,
			&i.Dimension,
			&i.Severity,
			&i.Status,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.SuggestedFix,
			&i.FixHint,
			&i.RequiresUserConfirmation,
			&i.SupersededByIssueID,
			&i.ResolvedByReviewRecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenArtifactIssuesByWorkspace = `-- name: ListOpenArtifactIssuesByWorkspace :many
SELECT id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
FROM artifact_issue
WHERE workspace_id = $1
  AND status = 'open'
ORDER BY created_at DESC
LIMIT $2
`

type ListOpenArtifactIssuesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListOpenArtifactIssuesByWorkspace(ctx context.Context, arg ListOpenArtifactIssuesByWorkspaceParams) ([]ArtifactIssue, error) {
	rows, err := q.db.Query(ctx, listOpenArtifactIssuesByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactIssue{}
	for rows.Next() {
		var i ArtifactIssue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReviewRecordID,
			&i.Dimension,
			&i.Severity,
			&i.Status,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.SuggestedFix,
			&i.FixHint,
			&i.RequiresUserConfirmation,
			&i.SupersededByIssueID,
			&i.ResolvedByReviewRecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactIssueResolved = `-- name: MarkArtifactIssueResolved :one
UPDATE artifact_issue
SET status = 'resolved',
    resolved_by_review_record_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, review_record_id, dimension, severity, status, target_object_type, target_object_id, title, description, evidence, suggested_fix, fix_hint, requires_user_confirmation, superseded_by_issue_id, resolved_by_review_record_id, created_at, updated_at
`

type MarkArtifactIssueResolvedParams struct {
	ID                       pgtype.UUID `json:"id"`
	ResolvedByReviewRecordID pgtype.UUID `json:"resolved_by_review_record_id"`
}

func (q *Queries) MarkArtifactIssueResolved(ctx context.Context, arg MarkArtifactIssueResolvedParams) (ArtifactIssue, error) {
	row := q.db.QueryRow(ctx, markArtifactIssueResolved, arg.ID, arg.ResolvedByReviewRecordID)
	var i ArtifactIssue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReviewRecordID,
		&i.Dimension,
		&i.Severity,
		&i.Status,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.Title,
		&i.Description,
		&i.Evidence,
		&i.SuggestedFix,
		&i.FixHint,
		&i.RequiresUserConfirmation,
		&i.SupersededByIssueID,
		&i.ResolvedByReviewRecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
