// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_asset (
    workspace_id,
    type,
    mime,
    storage_url,
    thumbnail_url,
    duration_ms,
    size_bytes,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, workspace_id, type, mime, storage_url, thumbnail_url, duration_ms, size_bytes, metadata, created_at
`

type CreateMediaAssetParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Type         MediaType   `json:"type"`
	Mime         string      `json:"mime"`
	StorageUrl   string      `json:"storage_url"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	DurationMs   pgtype.Int4 `json:"duration_ms"`
	SizeBytes    pgtype.Int8 `json:"size_bytes"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.WorkspaceID,
		arg.Type,
		arg.Mime,
		arg.StorageUrl,
		arg.ThumbnailUrl,
		arg.DurationMs,
		arg.SizeBytes,
		arg.Metadata,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Mime,
		&i.StorageUrl,
		&i.ThumbnailUrl,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT id, workspace_id, type, mime, storage_url, thumbnail_url, duration_ms, size_bytes, metadata, created_at
FROM media_asset
WHERE id = $1
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id pgtype.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Mime,
		&i.StorageUrl,
		&i.ThumbnailUrl,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaAssetsByWorkspace = `-- name: ListMediaAssetsByWorkspace :many
SELECT id, workspace_id, type, mime, storage_url, thumbnail_url, duration_ms, size_bytes, metadata, created_at
FROM media_asset
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListMediaAssetsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssetsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Mime,
			&i.StorageUrl,
			&i.ThumbnailUrl,
			&i.DurationMs,
			&i.SizeBytes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
