// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: creative_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveActiveProjectMemoryByWorkspace = `-- name: ArchiveActiveProjectMemoryByWorkspace :exec
UPDATE project_memory
SET status = 'archived'
WHERE workspace_id = $1
  AND status = 'active'
`

func (q *Queries) ArchiveActiveProjectMemoryByWorkspace(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveActiveProjectMemoryByWorkspace, workspaceID)
	return err
}

const archiveCreativeBrief = `-- name: ArchiveCreativeBrief :one
UPDATE creative_brief
SET status = 'archived',
    archived_at = now(),
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, title, video_type, target_audience, tone, visual_style, duration_sec, aspect_ratio, language, objective, concept, constraints, metadata, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type ArchiveCreativeBriefParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ArchiveCreativeBrief(ctx context.Context, arg ArchiveCreativeBriefParams) (CreativeBrief, error) {
	row := q.db.QueryRow(ctx, archiveCreativeBrief, arg.ID, arg.WorkspaceID)
	var i CreativeBrief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.VideoType,
		&i.TargetAudience,
		&i.Tone,
		&i.VisualStyle,
		&i.DurationSec,
		&i.AspectRatio,
		&i.Language,
		&i.Objective,
		&i.Concept,
		&i.Constraints,
		&i.Metadata,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const archiveKeyElement = `-- name: ArchiveKeyElement :one
UPDATE key_element
SET status = 'archived',
    archived_at = now(),
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, client_key, element_type, name, description, source_type, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type ArchiveKeyElementParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ArchiveKeyElement(ctx context.Context, arg ArchiveKeyElementParams) (KeyElement, error) {
	row := q.db.QueryRow(ctx, archiveKeyElement, arg.ID, arg.WorkspaceID)
	var i KeyElement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.ElementType,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const archiveScene = `-- name: ArchiveScene :one
UPDATE scene
SET status = 'archived',
    archived_at = now(),
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, client_key, sort_order, title, description, location, mood, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type ArchiveSceneParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ArchiveScene(ctx context.Context, arg ArchiveSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, archiveScene, arg.ID, arg.WorkspaceID)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Mood,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const clearDefaultKeyElementState = `-- name: ClearDefaultKeyElementState :exec
UPDATE key_element_state
SET is_default = false,
    updated_at = now()
WHERE key_element_id = $1
  AND archived_at IS NULL
`

func (q *Queries) ClearDefaultKeyElementState(ctx context.Context, keyElementID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultKeyElementState, keyElementID)
	return err
}

const createCreativeBrief = `-- name: CreateCreativeBrief :one
INSERT INTO creative_brief (
    workspace_id,
    title,
    video_type,
    target_audience,
    tone,
    visual_style,
    duration_sec,
    aspect_ratio,
    language,
    objective,
    concept,
    constraints,
    metadata,
    status,
    semantic_key,
    display_name,
    created_by_thread_id,
    created_by_task_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, workspace_id, title, video_type, target_audience, tone, visual_style, duration_sec, aspect_ratio, language, objective, concept, constraints, metadata, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type CreateCreativeBriefParams struct {
	WorkspaceID       pgtype.UUID   `json:"workspace_id"`
	Title             string        `json:"title"`
	VideoType         string        `json:"video_type"`
	TargetAudience    string        `json:"target_audience"`
	Tone              string        `json:"tone"`
	VisualStyle       string        `json:"visual_style"`
	DurationSec       pgtype.Float8 `json:"duration_sec"`
	AspectRatio       string        `json:"aspect_ratio"`
	Language          string        `json:"language"`
	Objective         string        `json:"objective"`
	Concept           string        `json:"concept"`
	Constraints       []byte        `json:"constraints"`
	Metadata          []byte        `json:"metadata"`
	Status            string        `json:"status"`
	SemanticKey       string        `json:"semantic_key"`
	DisplayName       string        `json:"display_name"`
	CreatedByThreadID pgtype.UUID   `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID   `json:"created_by_task_id"`
}

func (q *Queries) CreateCreativeBrief(ctx context.Context, arg CreateCreativeBriefParams) (CreativeBrief, error) {
	row := q.db.QueryRow(ctx, createCreativeBrief,
		arg.WorkspaceID,
		arg.Title,
		arg.VideoType,
		arg.TargetAudience,
		arg.Tone,
		arg.VisualStyle,
		arg.DurationSec,
		arg.AspectRatio,
		arg.Language,
		arg.Objective,
		arg.Concept,
		arg.Constraints,
		arg.Metadata,
		arg.Status,
		arg.SemanticKey,
		arg.DisplayName,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
	)
	var i CreativeBrief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.VideoType,
		&i.TargetAudience,
		&i.Tone,
		&i.VisualStyle,
		&i.DurationSec,
		&i.AspectRatio,
		&i.Language,
		&i.Objective,
		&i.Concept,
		&i.Constraints,
		&i.Metadata,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const createKeyElement = `-- name: CreateKeyElement :one
INSERT INTO key_element (
    workspace_id,
    client_key,
    element_type,
    name,
    description,
    source_type,
    source_refs,
    status,
    semantic_key,
    display_name,
    created_by_thread_id,
    created_by_task_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, workspace_id, client_key, element_type, name, description, source_type, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type CreateKeyElementParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ClientKey         string      `json:"client_key"`
	ElementType       string      `json:"element_type"`
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	SourceType        string      `json:"source_type"`
	SourceRefs        []byte      `json:"source_refs"`
	Status            string      `json:"status"`
	SemanticKey       string      `json:"semantic_key"`
	DisplayName       string      `json:"display_name"`
	CreatedByThreadID pgtype.UUID `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateKeyElement(ctx context.Context, arg CreateKeyElementParams) (KeyElement, error) {
	row := q.db.QueryRow(ctx, createKeyElement,
		arg.WorkspaceID,
		arg.ClientKey,
		arg.ElementType,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.SourceRefs,
		arg.Status,
		arg.SemanticKey,
		arg.DisplayName,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
	)
	var i KeyElement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.ElementType,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const createKeyElementState = `-- name: CreateKeyElementState :one
INSERT INTO key_element_state (
    workspace_id,
    key_element_id,
    client_key,
    label,
    visual_description,
    reference_status,
    reference_node_id,
    reference_version_id,
    is_default,
    state_facts,
    source_refs,
    status,
    semantic_key,
    display_name,
    created_by_thread_id,
    created_by_task_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, workspace_id, key_element_id, client_key, label, visual_description, reference_status, reference_node_id, reference_version_id, is_default, state_facts, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type CreateKeyElementStateParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	KeyElementID       pgtype.UUID `json:"key_element_id"`
	ClientKey          string      `json:"client_key"`
	Label              string      `json:"label"`
	VisualDescription  string      `json:"visual_description"`
	ReferenceStatus    string      `json:"reference_status"`
	ReferenceNodeID    pgtype.UUID `json:"reference_node_id"`
	ReferenceVersionID pgtype.UUID `json:"reference_version_id"`
	IsDefault          bool        `json:"is_default"`
	StateFacts         []byte      `json:"state_facts"`
	SourceRefs         []byte      `json:"source_refs"`
	Status             string      `json:"status"`
	SemanticKey        string      `json:"semantic_key"`
	DisplayName        string      `json:"display_name"`
	CreatedByThreadID  pgtype.UUID `json:"created_by_thread_id"`
	CreatedByTaskID    pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateKeyElementState(ctx context.Context, arg CreateKeyElementStateParams) (KeyElementState, error) {
	row := q.db.QueryRow(ctx, createKeyElementState,
		arg.WorkspaceID,
		arg.KeyElementID,
		arg.ClientKey,
		arg.Label,
		arg.VisualDescription,
		arg.ReferenceStatus,
		arg.ReferenceNodeID,
		arg.ReferenceVersionID,
		arg.IsDefault,
		arg.StateFacts,
		arg.SourceRefs,
		arg.Status,
		arg.SemanticKey,
		arg.DisplayName,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
	)
	var i KeyElementState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeyElementID,
		&i.ClientKey,
		&i.Label,
		&i.VisualDescription,
		&i.ReferenceStatus,
		&i.ReferenceNodeID,
		&i.ReferenceVersionID,
		&i.IsDefault,
		&i.StateFacts,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const createProjectMemory = `-- name: CreateProjectMemory :one
INSERT INTO project_memory (
    workspace_id,
    version,
    status,
    core_intent,
    soul,
    brand_facts,
    non_negotiables,
    visual_anchors,
    allowed,
    forbidden,
    prompt_injection_hints,
    source_refs,
    semantic_key,
    display_name,
    created_by_thread_id,
    created_by_task_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, workspace_id, version, status, core_intent, soul, brand_facts, non_negotiables, visual_anchors, allowed, forbidden, prompt_injection_hints, source_refs, created_by_thread_id, created_by_task_id, created_at, semantic_key, display_name
`

type CreateProjectMemoryParams struct {
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	Version              int32       `json:"version"`
	Status               string      `json:"status"`
	CoreIntent           string      `json:"core_intent"`
	Soul                 string      `json:"soul"`
	BrandFacts           []byte      `json:"brand_facts"`
	NonNegotiables       []byte      `json:"non_negotiables"`
	VisualAnchors        []byte      `json:"visual_anchors"`
	Allowed              []byte      `json:"allowed"`
	Forbidden            []byte      `json:"forbidden"`
	PromptInjectionHints []byte      `json:"prompt_injection_hints"`
	SourceRefs           []byte      `json:"source_refs"`
	SemanticKey          string      `json:"semantic_key"`
	DisplayName          string      `json:"display_name"`
	CreatedByThreadID    pgtype.UUID `json:"created_by_thread_id"`
	CreatedByTaskID      pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateProjectMemory(ctx context.Context, arg CreateProjectMemoryParams) (ProjectMemory, error) {
	row := q.db.QueryRow(ctx, createProjectMemory,
		arg.WorkspaceID,
		arg.Version,
		arg.Status,
		arg.CoreIntent,
		arg.Soul,
		arg.BrandFacts,
		arg.NonNegotiables,
		arg.VisualAnchors,
		arg.Allowed,
		arg.Forbidden,
		arg.PromptInjectionHints,
		arg.SourceRefs,
		arg.SemanticKey,
		arg.DisplayName,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
	)
	var i ProjectMemory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Version,
		&i.Status,
		&i.CoreIntent,
		&i.Soul,
		&i.BrandFacts,
		&i.NonNegotiables,
		&i.VisualAnchors,
		&i.Allowed,
		&i.Forbidden,
		&i.PromptInjectionHints,
		&i.SourceRefs,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const createScene = `-- name: CreateScene :one
INSERT INTO scene (
    workspace_id,
    client_key,
    sort_order,
    title,
    description,
    location,
    mood,
    status,
    semantic_key,
    display_name,
    created_by_thread_id,
    created_by_task_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, workspace_id, client_key, sort_order, title, description, location, mood, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type CreateSceneParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ClientKey         string      `json:"client_key"`
	SortOrder         int32       `json:"sort_order"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	Location          string      `json:"location"`
	Mood              string      `json:"mood"`
	Status            string      `json:"status"`
	SemanticKey       string      `json:"semantic_key"`
	DisplayName       string      `json:"display_name"`
	CreatedByThreadID pgtype.UUID `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.WorkspaceID,
		arg.ClientKey,
		arg.SortOrder,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Mood,
		arg.Status,
		arg.SemanticKey,
		arg.DisplayName,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Mood,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const createShotKeyElement = `-- name: CreateShotKeyElement :one
INSERT INTO shot_key_element (
    workspace_id,
    shot_id,
    key_element_id,
    key_element_state_id,
    role,
    required,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, workspace_id, shot_id, key_element_id, key_element_state_id, role, required, sort_order, created_at
`

type CreateShotKeyElementParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ShotID            pgtype.UUID `json:"shot_id"`
	KeyElementID      pgtype.UUID `json:"key_element_id"`
	KeyElementStateID pgtype.UUID `json:"key_element_state_id"`
	Role              string      `json:"role"`
	Required          bool        `json:"required"`
	SortOrder         int32       `json:"sort_order"`
}

func (q *Queries) CreateShotKeyElement(ctx context.Context, arg CreateShotKeyElementParams) (ShotKeyElement, error) {
	row := q.db.QueryRow(ctx, createShotKeyElement,
		arg.WorkspaceID,
		arg.ShotID,
		arg.KeyElementID,
		arg.KeyElementStateID,
		arg.Role,
		arg.Required,
		arg.SortOrder,
	)
	var i ShotKeyElement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShotID,
		&i.KeyElementID,
		&i.KeyElementStateID,
		&i.Role,
		&i.Required,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShotKeyElementsByShot = `-- name: DeleteShotKeyElementsByShot :exec
DELETE FROM shot_key_element
WHERE workspace_id = $1
  AND shot_id = $2
`

type DeleteShotKeyElementsByShotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ShotID      pgtype.UUID `json:"shot_id"`
}

func (q *Queries) DeleteShotKeyElementsByShot(ctx context.Context, arg DeleteShotKeyElementsByShotParams) error {
	_, err := q.db.Exec(ctx, deleteShotKeyElementsByShot, arg.WorkspaceID, arg.ShotID)
	return err
}

const deleteShotKeyElementsByWorkspace = `-- name: DeleteShotKeyElementsByWorkspace :exec
DELETE FROM shot_key_element
WHERE workspace_id = $1
`

func (q *Queries) DeleteShotKeyElementsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShotKeyElementsByWorkspace, workspaceID)
	return err
}

const getActiveCreativeBriefByWorkspace = `-- name: GetActiveCreativeBriefByWorkspace :one
SELECT id, workspace_id, title, video_type, target_audience, tone, visual_style, duration_sec, aspect_ratio, language, objective, concept, constraints, metadata, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM creative_brief
WHERE workspace_id = $1
  AND archived_at IS NULL
  AND status <> 'archived'
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCreativeBriefByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (CreativeBrief, error) {
	row := q.db.QueryRow(ctx, getActiveCreativeBriefByWorkspace, workspaceID)
	var i CreativeBrief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.VideoType,
		&i.TargetAudience,
		&i.Tone,
		&i.VisualStyle,
		&i.DurationSec,
		&i.AspectRatio,
		&i.Language,
		&i.Objective,
		&i.Concept,
		&i.Constraints,
		&i.Metadata,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getActiveProjectMemoryByWorkspace = `-- name: GetActiveProjectMemoryByWorkspace :one
SELECT id, workspace_id, version, status, core_intent, soul, brand_facts, non_negotiables, visual_anchors, allowed, forbidden, prompt_injection_hints, source_refs, created_by_thread_id, created_by_task_id, created_at, semantic_key, display_name
FROM project_memory
WHERE workspace_id = $1
  AND status = 'active'
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetActiveProjectMemoryByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (ProjectMemory, error) {
	row := q.db.QueryRow(ctx, getActiveProjectMemoryByWorkspace, workspaceID)
	var i ProjectMemory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Version,
		&i.Status,
		&i.CoreIntent,
		&i.Soul,
		&i.BrandFacts,
		&i.NonNegotiables,
		&i.VisualAnchors,
		&i.Allowed,
		&i.Forbidden,
		&i.PromptInjectionHints,
		&i.SourceRefs,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getCreativeBriefByID = `-- name: GetCreativeBriefByID :one
SELECT id, workspace_id, title, video_type, target_audience, tone, visual_style, duration_sec, aspect_ratio, language, objective, concept, constraints, metadata, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM creative_brief
WHERE id = $1
  AND workspace_id = $2
`

type GetCreativeBriefByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetCreativeBriefByID(ctx context.Context, arg GetCreativeBriefByIDParams) (CreativeBrief, error) {
	row := q.db.QueryRow(ctx, getCreativeBriefByID, arg.ID, arg.WorkspaceID)
	var i CreativeBrief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.VideoType,
		&i.TargetAudience,
		&i.Tone,
		&i.VisualStyle,
		&i.DurationSec,
		&i.AspectRatio,
		&i.Language,
		&i.Objective,
		&i.Concept,
		&i.Constraints,
		&i.Metadata,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getDefaultKeyElementState = `-- name: GetDefaultKeyElementState :one
SELECT id, workspace_id, key_element_id, client_key, label, visual_description, reference_status, reference_node_id, reference_version_id, is_default, state_facts, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM key_element_state
WHERE key_element_id = $1
  AND is_default
  AND archived_at IS NULL
LIMIT 1
`

func (q *Queries) GetDefaultKeyElementState(ctx context.Context, keyElementID pgtype.UUID) (KeyElementState, error) {
	row := q.db.QueryRow(ctx, getDefaultKeyElementState, keyElementID)
	var i KeyElementState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeyElementID,
		&i.ClientKey,
		&i.Label,
		&i.VisualDescription,
		&i.ReferenceStatus,
		&i.ReferenceNodeID,
		&i.ReferenceVersionID,
		&i.IsDefault,
		&i.StateFacts,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getKeyElementByClientKey = `-- name: GetKeyElementByClientKey :one
SELECT id, workspace_id, client_key, element_type, name, description, source_type, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM key_element
WHERE workspace_id = $1
  AND client_key = $2
  AND archived_at IS NULL
`

type GetKeyElementByClientKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ClientKey   string      `json:"client_key"`
}

func (q *Queries) GetKeyElementByClientKey(ctx context.Context, arg GetKeyElementByClientKeyParams) (KeyElement, error) {
	row := q.db.QueryRow(ctx, getKeyElementByClientKey, arg.WorkspaceID, arg.ClientKey)
	var i KeyElement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.ElementType,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getKeyElementStateByClientKey = `-- name: GetKeyElementStateByClientKey :one
SELECT id, workspace_id, key_element_id, client_key, label, visual_description, reference_status, reference_node_id, reference_version_id, is_default, state_facts, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM key_element_state
WHERE key_element_id = $1
  AND client_key = $2
  AND archived_at IS NULL
`

type GetKeyElementStateByClientKeyParams struct {
	KeyElementID pgtype.UUID `json:"key_element_id"`
	ClientKey    string      `json:"client_key"`
}

func (q *Queries) GetKeyElementStateByClientKey(ctx context.Context, arg GetKeyElementStateByClientKeyParams) (KeyElementState, error) {
	row := q.db.QueryRow(ctx, getKeyElementStateByClientKey, arg.KeyElementID, arg.ClientKey)
	var i KeyElementState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeyElementID,
		&i.ClientKey,
		&i.Label,
		&i.VisualDescription,
		&i.ReferenceStatus,
		&i.ReferenceNodeID,
		&i.ReferenceVersionID,
		&i.IsDefault,
		&i.StateFacts,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getKeyElementStateByID = `-- name: GetKeyElementStateByID :one
SELECT id, workspace_id, key_element_id, client_key, label, visual_description, reference_status, reference_node_id, reference_version_id, is_default, state_facts, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM key_element_state
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
`

type GetKeyElementStateByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetKeyElementStateByID(ctx context.Context, arg GetKeyElementStateByIDParams) (KeyElementState, error) {
	row := q.db.QueryRow(ctx, getKeyElementStateByID, arg.ID, arg.WorkspaceID)
	var i KeyElementState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeyElementID,
		&i.ClientKey,
		&i.Label,
		&i.VisualDescription,
		&i.ReferenceStatus,
		&i.ReferenceNodeID,
		&i.ReferenceVersionID,
		&i.IsDefault,
		&i.StateFacts,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getSceneByClientKey = `-- name: GetSceneByClientKey :one
SELECT id, workspace_id, client_key, sort_order, title, description, location, mood, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM scene
WHERE workspace_id = $1
  AND client_key = $2
  AND archived_at IS NULL
`

type GetSceneByClientKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ClientKey   string      `json:"client_key"`
}

func (q *Queries) GetSceneByClientKey(ctx context.Context, arg GetSceneByClientKeyParams) (Scene, error) {
	row := q.db.QueryRow(ctx, getSceneByClientKey, arg.WorkspaceID, arg.ClientKey)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Mood,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const listActiveKeyElementStatesByWorkspace = `-- name: ListActiveKeyElementStatesByWorkspace :many
SELECT id, workspace_id, key_element_id, client_key, label, visual_description, reference_status, reference_node_id, reference_version_id, is_default, state_facts, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM key_element_state
WHERE workspace_id = $1
  AND archived_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListActiveKeyElementStatesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]KeyElementState, error) {
	rows, err := q.db.Query(ctx, listActiveKeyElementStatesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyElementState{}
	for rows.Next() {
		var i KeyElementState
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeyElementID,
			&i.ClientKey,
			&i.Label,
			&i.VisualDescription,
			&i.ReferenceStatus,
			&i.ReferenceNodeID,
			&i.ReferenceVersionID,
			&i.IsDefault,
			&i.StateFacts,
			&i.SourceRefs,
			&i.Status,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveKeyElementsByWorkspace = `-- name: ListActiveKeyElementsByWorkspace :many
SELECT id, workspace_id, client_key, element_type, name, description, source_type, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM key_element
WHERE workspace_id = $1
  AND archived_at IS NULL
ORDER BY element_type, name, created_at
`

func (q *Queries) ListActiveKeyElementsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]KeyElement, error) {
	rows, err := q.db.Query(ctx, listActiveKeyElementsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyElement{}
	for rows.Next() {
		var i KeyElement
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ClientKey,
			&i.ElementType,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceRefs,
			&i.Status,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveScenesByWorkspace = `-- name: ListActiveScenesByWorkspace :many
SELECT id, workspace_id, client_key, sort_order, title, description, location, mood, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
FROM scene
WHERE workspace_id = $1
  AND archived_at IS NULL
ORDER BY sort_order, created_at
`

func (q *Queries) ListActiveScenesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Scene, error) {
	rows, err := q.db.Query(ctx, listActiveScenesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ClientKey,
			&i.SortOrder,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Mood,
			&i.Status,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMemoriesByWorkspace = `-- name: ListProjectMemoriesByWorkspace :many
SELECT id, workspace_id, version, status, core_intent, soul, brand_facts, non_negotiables, visual_anchors, allowed, forbidden, prompt_injection_hints, source_refs, created_by_thread_id, created_by_task_id, created_at, semantic_key, display_name
FROM project_memory
WHERE workspace_id = $1
ORDER BY version DESC
`

func (q *Queries) ListProjectMemoriesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ProjectMemory, error) {
	rows, err := q.db.Query(ctx, listProjectMemoriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMemory{}
	for rows.Next() {
		var i ProjectMemory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Version,
			&i.Status,
			&i.CoreIntent,
			&i.Soul,
			&i.BrandFacts,
			&i.NonNegotiables,
			&i.VisualAnchors,
			&i.Allowed,
			&i.Forbidden,
			&i.PromptInjectionHints,
			&i.SourceRefs,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.CreatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShotKeyElementsByWorkspace = `-- name: ListShotKeyElementsByWorkspace :many
SELECT id, workspace_id, shot_id, key_element_id, key_element_state_id, role, required, sort_order, created_at
FROM shot_key_element
WHERE workspace_id = $1
ORDER BY shot_id, sort_order, created_at
`

func (q *Queries) ListShotKeyElementsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ShotKeyElement, error) {
	rows, err := q.db.Query(ctx, listShotKeyElementsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShotKeyElement{}
	for rows.Next() {
		var i ShotKeyElement
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.KeyElementID,
			&i.KeyElementStateID,
			&i.Role,
			&i.Required,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreativeBrief = `-- name: UpdateCreativeBrief :one
UPDATE creative_brief
SET title = $3,
    video_type = $4,
    target_audience = $5,
    tone = $6,
    visual_style = $7,
    duration_sec = $8,
    aspect_ratio = $9,
    language = $10,
    objective = $11,
    concept = $12,
    constraints = $13,
    metadata = $14,
    status = $15,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, title, video_type, target_audience, tone, visual_style, duration_sec, aspect_ratio, language, objective, concept, constraints, metadata, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type UpdateCreativeBriefParams struct {
	ID             pgtype.UUID   `json:"id"`
	WorkspaceID    pgtype.UUID   `json:"workspace_id"`
	Title          string        `json:"title"`
	VideoType      string        `json:"video_type"`
	TargetAudience string        `json:"target_audience"`
	Tone           string        `json:"tone"`
	VisualStyle    string        `json:"visual_style"`
	DurationSec    pgtype.Float8 `json:"duration_sec"`
	AspectRatio    string        `json:"aspect_ratio"`
	Language       string        `json:"language"`
	Objective      string        `json:"objective"`
	Concept        string        `json:"concept"`
	Constraints    []byte        `json:"constraints"`
	Metadata       []byte        `json:"metadata"`
	Status         string        `json:"status"`
}

func (q *Queries) UpdateCreativeBrief(ctx context.Context, arg UpdateCreativeBriefParams) (CreativeBrief, error) {
	row := q.db.QueryRow(ctx, updateCreativeBrief,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.VideoType,
		arg.TargetAudience,
		arg.Tone,
		arg.VisualStyle,
		arg.DurationSec,
		arg.AspectRatio,
		arg.Language,
		arg.Objective,
		arg.Concept,
		arg.Constraints,
		arg.Metadata,
		arg.Status,
	)
	var i CreativeBrief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.VideoType,
		&i.TargetAudience,
		&i.Tone,
		&i.VisualStyle,
		&i.DurationSec,
		&i.AspectRatio,
		&i.Language,
		&i.Objective,
		&i.Concept,
		&i.Constraints,
		&i.Metadata,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const updateKeyElement = `-- name: UpdateKeyElement :one
UPDATE key_element
SET element_type = $3,
    name = $4,
    description = $5,
    source_type = $6,
    source_refs = $7,
    status = $8,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, client_key, element_type, name, description, source_type, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type UpdateKeyElementParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ElementType string      `json:"element_type"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	SourceType  string      `json:"source_type"`
	SourceRefs  []byte      `json:"source_refs"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateKeyElement(ctx context.Context, arg UpdateKeyElementParams) (KeyElement, error) {
	row := q.db.QueryRow(ctx, updateKeyElement,
		arg.ID,
		arg.WorkspaceID,
		arg.ElementType,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.SourceRefs,
		arg.Status,
	)
	var i KeyElement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.ElementType,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const updateKeyElementState = `-- name: UpdateKeyElementState :one
UPDATE key_element_state
SET label = $3,
    visual_description = $4,
    reference_status = $5,
    reference_node_id = $6,
    reference_version_id = $7,
    is_default = $8,
    state_facts = $9,
    source_refs = $10,
    status = $11,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, key_element_id, client_key, label, visual_description, reference_status, reference_node_id, reference_version_id, is_default, state_facts, source_refs, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type UpdateKeyElementStateParams struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	Label              string      `json:"label"`
	VisualDescription  string      `json:"visual_description"`
	ReferenceStatus    string      `json:"reference_status"`
	ReferenceNodeID    pgtype.UUID `json:"reference_node_id"`
	ReferenceVersionID pgtype.UUID `json:"reference_version_id"`
	IsDefault          bool        `json:"is_default"`
	StateFacts         []byte      `json:"state_facts"`
	SourceRefs         []byte      `json:"source_refs"`
	Status             string      `json:"status"`
}

func (q *Queries) UpdateKeyElementState(ctx context.Context, arg UpdateKeyElementStateParams) (KeyElementState, error) {
	row := q.db.QueryRow(ctx, updateKeyElementState,
		arg.ID,
		arg.WorkspaceID,
		arg.Label,
		arg.VisualDescription,
		arg.ReferenceStatus,
		arg.ReferenceNodeID,
		arg.ReferenceVersionID,
		arg.IsDefault,
		arg.StateFacts,
		arg.SourceRefs,
		arg.Status,
	)
	var i KeyElementState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeyElementID,
		&i.ClientKey,
		&i.Label,
		&i.VisualDescription,
		&i.ReferenceStatus,
		&i.ReferenceNodeID,
		&i.ReferenceVersionID,
		&i.IsDefault,
		&i.StateFacts,
		&i.SourceRefs,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const updateScene = `-- name: UpdateScene :one
UPDATE scene
SET client_key = $3,
    sort_order = $4,
    title = $5,
    description = $6,
    location = $7,
    mood = $8,
    status = $9,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND archived_at IS NULL
RETURNING id, workspace_id, client_key, sort_order, title, description, location, mood, status, created_by_thread_id, created_by_task_id, archived_at, created_at, updated_at, semantic_key, display_name
`

type UpdateSceneParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ClientKey   string      `json:"client_key"`
	SortOrder   int32       `json:"sort_order"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Location    string      `json:"location"`
	Mood        string      `json:"mood"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, updateScene,
		arg.ID,
		arg.WorkspaceID,
		arg.ClientKey,
		arg.SortOrder,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Mood,
		arg.Status,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientKey,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Mood,
		&i.Status,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}
