// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaEdge = `-- name: CreateMediaEdge :one
INSERT INTO media_edge (
    workspace_id,
    from_node_id,
    to_node_id,
    edge_type
) VALUES (
    $1,
    $2,
    $3,
    'dependency'
) RETURNING id, workspace_id, from_node_id, to_node_id, edge_type, transition_type, transition_duration, source, metadata, created_at
`

type CreateMediaEdgeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromNodeID  pgtype.UUID `json:"from_node_id"`
	ToNodeID    pgtype.UUID `json:"to_node_id"`
}

func (q *Queries) CreateMediaEdge(ctx context.Context, arg CreateMediaEdgeParams) (MediaEdge, error) {
	row := q.db.QueryRow(ctx, createMediaEdge, arg.WorkspaceID, arg.FromNodeID, arg.ToNodeID)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.TransitionType,
		&i.TransitionDuration,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaEdge = `-- name: DeleteMediaEdge :exec
DELETE FROM media_edge
WHERE id = $1
`

func (q *Queries) DeleteMediaEdge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaEdge, id)
	return err
}

const getDependencyEdgeByEndpoints = `-- name: GetDependencyEdgeByEndpoints :one
SELECT id, workspace_id, from_node_id, to_node_id, edge_type, transition_type, transition_duration, source, metadata, created_at FROM media_edge
WHERE from_node_id = $1
  AND to_node_id = $2
  AND edge_type = 'dependency'
`

type GetDependencyEdgeByEndpointsParams struct {
	FromNodeID pgtype.UUID `json:"from_node_id"`
	ToNodeID   pgtype.UUID `json:"to_node_id"`
}

func (q *Queries) GetDependencyEdgeByEndpoints(ctx context.Context, arg GetDependencyEdgeByEndpointsParams) (MediaEdge, error) {
	row := q.db.QueryRow(ctx, getDependencyEdgeByEndpoints, arg.FromNodeID, arg.ToNodeID)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.TransitionType,
		&i.TransitionDuration,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaEdgeByID = `-- name: GetMediaEdgeByID :one
SELECT id, workspace_id, from_node_id, to_node_id, edge_type, transition_type, transition_duration, source, metadata, created_at FROM media_edge
WHERE id = $1
`

func (q *Queries) GetMediaEdgeByID(ctx context.Context, id pgtype.UUID) (MediaEdge, error) {
	row := q.db.QueryRow(ctx, getMediaEdgeByID, id)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.TransitionType,
		&i.TransitionDuration,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaEdgesByWorkspace = `-- name: ListMediaEdgesByWorkspace :many
SELECT id, workspace_id, from_node_id, to_node_id, edge_type, transition_type, transition_duration, source, metadata, created_at FROM media_edge
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListMediaEdgesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]MediaEdge, error) {
	rows, err := q.db.Query(ctx, listMediaEdgesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEdge{}
	for rows.Next() {
		var i MediaEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.TransitionType,
			&i.TransitionDuration,
			&i.Source,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingDependencyEdges = `-- name: ListOutgoingDependencyEdges :many
SELECT id, workspace_id, from_node_id, to_node_id, edge_type, transition_type, transition_duration, source, metadata, created_at FROM media_edge
WHERE from_node_id = $1
  AND edge_type = 'dependency'
ORDER BY created_at
`

func (q *Queries) ListOutgoingDependencyEdges(ctx context.Context, fromNodeID pgtype.UUID) ([]MediaEdge, error) {
	rows, err := q.db.Query(ctx, listOutgoingDependencyEdges, fromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEdge{}
	for rows.Next() {
		var i MediaEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.TransitionType,
			&i.TransitionDuration,
			&i.Source,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
