// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eino_checkpoint.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEinoCheckpoint = `-- name: DeleteEinoCheckpoint :exec
DELETE FROM eino_checkpoint
WHERE key = $1
`

func (q *Queries) DeleteEinoCheckpoint(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteEinoCheckpoint, key)
	return err
}

const getEinoCheckpoint = `-- name: GetEinoCheckpoint :one
SELECT key, workspace_id, thread_id, task_id, value, metadata, created_at, updated_at
FROM eino_checkpoint
WHERE key = $1
`

func (q *Queries) GetEinoCheckpoint(ctx context.Context, key string) (EinoCheckpoint, error) {
	row := q.db.QueryRow(ctx, getEinoCheckpoint, key)
	var i EinoCheckpoint
	err := row.Scan(
		&i.Key,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.Value,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEinoCheckpointsByThread = `-- name: ListEinoCheckpointsByThread :many
SELECT key, workspace_id, thread_id, task_id, value, metadata, created_at, updated_at
FROM eino_checkpoint
WHERE thread_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListEinoCheckpointsByThread(ctx context.Context, threadID pgtype.UUID) ([]EinoCheckpoint, error) {
	rows, err := q.db.Query(ctx, listEinoCheckpointsByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EinoCheckpoint{}
	for rows.Next() {
		var i EinoCheckpoint
		if err := rows.Scan(
			&i.Key,
			&i.WorkspaceID,
			&i.ThreadID,
			&i.TaskID,
			&i.Value,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEinoCheckpoint = `-- name: UpsertEinoCheckpoint :one
INSERT INTO eino_checkpoint (
    key,
    workspace_id,
    thread_id,
    task_id,
    value,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (key)
DO UPDATE SET
    workspace_id = EXCLUDED.workspace_id,
    thread_id = EXCLUDED.thread_id,
    task_id = EXCLUDED.task_id,
    value = EXCLUDED.value,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING key, workspace_id, thread_id, task_id, value, metadata, created_at, updated_at
`

type UpsertEinoCheckpointParams struct {
	Key         string      `json:"key"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	TaskID      pgtype.UUID `json:"task_id"`
	Value       []byte      `json:"value"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpsertEinoCheckpoint(ctx context.Context, arg UpsertEinoCheckpointParams) (EinoCheckpoint, error) {
	row := q.db.QueryRow(ctx, upsertEinoCheckpoint,
		arg.Key,
		arg.WorkspaceID,
		arg.ThreadID,
		arg.TaskID,
		arg.Value,
		arg.Metadata,
	)
	var i EinoCheckpoint
	err := row.Scan(
		&i.Key,
		&i.WorkspaceID,
		&i.ThreadID,
		&i.TaskID,
		&i.Value,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
