// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaGroup = `-- name: CreateMediaGroup :one
INSERT INTO media_group (workspace_id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, sort_order, created_at, updated_at
`

type CreateMediaGroupParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) CreateMediaGroup(ctx context.Context, arg CreateMediaGroupParams) (MediaGroup, error) {
	row := q.db.QueryRow(ctx, createMediaGroup, arg.WorkspaceID, arg.Name, arg.SortOrder)
	var i MediaGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaGroup = `-- name: DeleteMediaGroup :exec
DELETE FROM media_group
WHERE id = $1
`

func (q *Queries) DeleteMediaGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaGroup, id)
	return err
}

const getMediaGroupByID = `-- name: GetMediaGroupByID :one
SELECT id, workspace_id, name, sort_order, created_at, updated_at
FROM media_group
WHERE id = $1
`

func (q *Queries) GetMediaGroupByID(ctx context.Context, id pgtype.UUID) (MediaGroup, error) {
	row := q.db.QueryRow(ctx, getMediaGroupByID, id)
	var i MediaGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaGroupsByWorkspace = `-- name: ListMediaGroupsByWorkspace :many
SELECT id, workspace_id, name, sort_order, created_at, updated_at
FROM media_group
WHERE workspace_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListMediaGroupsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]MediaGroup, error) {
	rows, err := q.db.Query(ctx, listMediaGroupsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaGroup{}
	for rows.Next() {
		var i MediaGroup
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaGroupName = `-- name: UpdateMediaGroupName :one
UPDATE media_group
SET name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, sort_order, created_at, updated_at
`

type UpdateMediaGroupNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateMediaGroupName(ctx context.Context, arg UpdateMediaGroupNameParams) (MediaGroup, error) {
	row := q.db.QueryRow(ctx, updateMediaGroupName, arg.ID, arg.Name)
	var i MediaGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaGroupSortOrder = `-- name: UpdateMediaGroupSortOrder :one
UPDATE media_group
SET sort_order = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, sort_order, created_at, updated_at
`

type UpdateMediaGroupSortOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateMediaGroupSortOrder(ctx context.Context, arg UpdateMediaGroupSortOrderParams) (MediaGroup, error) {
	row := q.db.QueryRow(ctx, updateMediaGroupSortOrder, arg.ID, arg.SortOrder)
	var i MediaGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
