// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetType string

const (
	AssetTypeText  AssetType = "text"
	AssetTypeImage AssetType = "image"
	AssetTypeVideo AssetType = "video"
	AssetTypeAudio AssetType = "audio"
	AssetTypeJson  AssetType = "json"
)

func (e *AssetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetType(s)
	case string:
		*e = AssetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetType: %T", src)
	}
	return nil
}

type NullAssetType struct {
	AssetType AssetType `json:"asset_type"`
	Valid     bool      `json:"valid"` // Valid is true if AssetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetType), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusCancelled JobStatus = "cancelled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type NodeStatus string

const (
	NodeStatusDraft       NodeStatus = "draft"
	NodeStatusReady       NodeStatus = "ready"
	NodeStatusQueued      NodeStatus = "queued"
	NodeStatusRunning     NodeStatus = "running"
	NodeStatusSucceeded   NodeStatus = "succeeded"
	NodeStatusFailed      NodeStatus = "failed"
	NodeStatusStale       NodeStatus = "stale"
	NodeStatusUserEditing NodeStatus = "user_editing"
)

func (e *NodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeStatus(s)
	case string:
		*e = NodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeStatus: %T", src)
	}
	return nil
}

type NullNodeStatus struct {
	NodeStatus NodeStatus `json:"node_status"`
	Valid      bool       `json:"valid"` // Valid is true if NodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeStatus), nil
}

type NodeType string

const (
	NodeTypeText          NodeType = "text"
	NodeTypeImage         NodeType = "image"
	NodeTypeVideo         NodeType = "video"
	NodeTypeAudio         NodeType = "audio"
	NodeTypeReferencePack NodeType = "reference_pack"
)

func (e *NodeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeType(s)
	case string:
		*e = NodeType(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeType: %T", src)
	}
	return nil
}

type NullNodeType struct {
	NodeType NodeType `json:"node_type"`
	Valid    bool     `json:"valid"` // Valid is true if NodeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeType) Scan(value interface{}) error {
	if value == nil {
		ns.NodeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeType), nil
}

type WorkspaceMode string

const (
	WorkspaceModeStudio WorkspaceMode = "studio"
	WorkspaceModeAgent  WorkspaceMode = "agent"
)

func (e *WorkspaceMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceMode(s)
	case string:
		*e = WorkspaceMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceMode: %T", src)
	}
	return nil
}

type NullWorkspaceMode struct {
	WorkspaceMode WorkspaceMode `json:"workspace_mode"`
	Valid         bool          `json:"valid"` // Valid is true if WorkspaceMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceMode) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceMode), nil
}

type Account struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AgentEvent struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	EventType   string             `json:"event_type"`
	SourceRole  string             `json:"source_role"`
	TargetRole  pgtype.Text        `json:"target_role"`
	Scope       []byte             `json:"scope"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	HandledAt   pgtype.Timestamptz `json:"handled_at"`
}

type AgentMessage struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	Seq         int64              `json:"seq"`
	Role        string             `json:"role"`
	MessageType string             `json:"message_type"`
	Content     []byte             `json:"content"`
	RawMessage  []byte             `json:"raw_message"`
	TaskID      pgtype.UUID        `json:"task_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AgentTask struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	ThreadID     pgtype.UUID        `json:"thread_id"`
	Role         string             `json:"role"`
	ScopeType    string             `json:"scope_type"`
	ScopeID      pgtype.UUID        `json:"scope_id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	Attempt      int32              `json:"attempt"`
	MaxAttempts  int32              `json:"max_attempts"`
	Input        []byte             `json:"input"`
	Output       []byte             `json:"output"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type AgentThread struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	Role                 string             `json:"role"`
	ScopeType            string             `json:"scope_type"`
	ScopeID              pgtype.UUID        `json:"scope_id"`
	RuntimeProvider      string             `json:"runtime_provider"`
	RuntimeAgentName     string             `json:"runtime_agent_name"`
	CurrentCheckpointKey pgtype.Text        `json:"current_checkpoint_key"`
	Status               string             `json:"status"`
	Summary              string             `json:"summary"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ArtifactVersion struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	NodeID           pgtype.UUID        `json:"node_id"`
	JobID            pgtype.UUID        `json:"job_id"`
	AssetID          pgtype.UUID        `json:"asset_id"`
	VersionNo        int32              `json:"version_no"`
	Winner           bool               `json:"winner"`
	Output           []byte             `json:"output"`
	ReviewScore      pgtype.Float4      `json:"review_score"`
	InputHash        string             `json:"input_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Status           JobStatus          `json:"status"`
	Progress         int32              `json:"progress"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	ProviderRequest  []byte             `json:"provider_request"`
	ProviderResponse []byte             `json:"provider_response"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type CanvasDocument struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	CameraX       float32            `json:"camera_x"`
	CameraY       float32            `json:"camera_y"`
	CameraZoom    float32            `json:"camera_zoom"`
	LayoutVersion int32              `json:"layout_version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EinoCheckpoint struct {
	Key         string             `json:"key"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Value       []byte             `json:"value"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GenerationJob struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	TargetNodeID     pgtype.UUID        `json:"target_node_id"`
	ParentJobID      pgtype.UUID        `json:"parent_job_id"`
	OperationType    string             `json:"operation_type"`
	Provider         string             `json:"provider"`
	ModelID          string             `json:"model_id"`
	Intent           []byte             `json:"intent"`
	RenderedPrompt   string             `json:"rendered_prompt"`
	ProviderRequest  []byte             `json:"provider_request"`
	ProviderResponse []byte             `json:"provider_response"`
	Status           JobStatus          `json:"status"`
	Progress         int32              `json:"progress"`
	Attempt          int32              `json:"attempt"`
	MaxAttempts      int32              `json:"max_attempts"`
	RetryPolicy      []byte             `json:"retry_policy"`
	CostCents        pgtype.Int4        `json:"cost_cents"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	RequestedByType  string             `json:"requested_by_type"`
	RequestedByID    pgtype.Text        `json:"requested_by_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MediaAsset struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Type         AssetType          `json:"type"`
	Mime         string             `json:"mime"`
	StorageUrl   pgtype.Text        `json:"storage_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	SizeBytes    pgtype.Int8        `json:"size_bytes"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TextContent  pgtype.Text        `json:"text_content"`
}

type MediaEdge struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	FromNodeID  pgtype.UUID        `json:"from_node_id"`
	ToNodeID    pgtype.UUID        `json:"to_node_id"`
	Source      string             `json:"source"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MediaGroup struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MediaNode struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	NodeType         NodeType           `json:"node_type"`
	Title            string             `json:"title"`
	Status           NodeStatus         `json:"status"`
	Prompt           string             `json:"prompt"`
	Source           string             `json:"source"`
	CanvasX          float32            `json:"canvas_x"`
	CanvasY          float32            `json:"canvas_y"`
	CanvasW          float32            `json:"canvas_w"`
	CanvasH          float32            `json:"canvas_h"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	GroupID          pgtype.UUID        `json:"group_id"`
	AssetID          pgtype.UUID        `json:"asset_id"`
	OperationType    string             `json:"operation_type"`
	PromptTemplate   string             `json:"prompt_template"`
	PromptRich       []byte             `json:"prompt_rich"`
	PromptRefs       []byte             `json:"prompt_refs"`
	ModelProvider    pgtype.Text        `json:"model_provider"`
	ModelID          pgtype.Text        `json:"model_id"`
	ModelParams      []byte             `json:"model_params"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	Metadata         []byte             `json:"metadata"`
	ShotID           pgtype.UUID        `json:"shot_id"`
}

type ModelCapability struct {
	ID                      pgtype.UUID        `json:"id"`
	ProviderID              string             `json:"provider_id"`
	ModelID                 string             `json:"model_id"`
	DisplayName             string             `json:"display_name"`
	OutputTypes             []byte             `json:"output_types"`
	SupportedOperations     []byte             `json:"supported_operations"`
	SupportedInputNodeTypes []byte             `json:"supported_input_node_types"`
	Limits                  []byte             `json:"limits"`
	Pricing                 []byte             `json:"pricing"`
	Defaults                []byte             `json:"defaults"`
	Enabled                 bool               `json:"enabled"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ModelProvider struct {
	ID           string             `json:"id"`
	DisplayName  string             `json:"display_name"`
	ProviderType string             `json:"provider_type"`
	Config       []byte             `json:"config"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type NodeStaleReason struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	NodeID            pgtype.UUID        `json:"node_id"`
	UpstreamNodeID    pgtype.UUID        `json:"upstream_node_id"`
	UpstreamVersionID pgtype.UUID        `json:"upstream_version_id"`
	ReasonCode        string             `json:"reason_code"`
	ReasonMessage     string             `json:"reason_message"`
	Details           []byte             `json:"details"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ReferencePackItem struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	PackNodeID   pgtype.UUID        `json:"pack_node_id"`
	MemberNodeID pgtype.UUID        `json:"member_node_id"`
	Position     int32              `json:"position"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SandboxJob struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	TargetNodeID    pgtype.UUID        `json:"target_node_id"`
	GenerationJobID pgtype.UUID        `json:"generation_job_id"`
	JobType         string             `json:"job_type"`
	OperationType   string             `json:"operation_type"`
	Status          JobStatus          `json:"status"`
	SandboxID       pgtype.Text        `json:"sandbox_id"`
	Command         string             `json:"command"`
	Cwd             string             `json:"cwd"`
	Input           []byte             `json:"input"`
	Output          []byte             `json:"output"`
	ExitCode        pgtype.Int4        `json:"exit_code"`
	Stdout          string             `json:"stdout"`
	Stderr          string             `json:"stderr"`
	DurationMs      int32              `json:"duration_ms"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Shot struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ClientKey         string             `json:"client_key"`
	SortOrder         int32              `json:"sort_order"`
	Title             string             `json:"title"`
	Brief             []byte             `json:"brief"`
	DurationSec       pgtype.Float8      `json:"duration_sec"`
	NarrativePurpose  string             `json:"narrative_purpose"`
	Status            string             `json:"status"`
	CraftsmanThreadID pgtype.UUID        `json:"craftsman_thread_id"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ShotDependency struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	FromShotID       pgtype.UUID        `json:"from_shot_id"`
	ToShotID         pgtype.UUID        `json:"to_shot_id"`
	DependencyType   string             `json:"dependency_type"`
	RequiredArtifact string             `json:"required_artifact"`
	InjectionRole    string             `json:"injection_role"`
	BlockingPhase    string             `json:"blocking_phase"`
	StalePolicy      string             `json:"stale_policy"`
	Reason           string             `json:"reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Mode      WorkspaceMode      `json:"mode"`
}

type WorkspaceSandbox struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	SandboxID         pgtype.Text        `json:"sandbox_id"`
	VolumeName        string             `json:"volume_name"`
	Status            string             `json:"status"`
	LastHealthCheckAt pgtype.Timestamptz `json:"last_health_check_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
