// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model.sql

package db

import (
	"context"
)

const getEnabledModelCapability = `-- name: GetEnabledModelCapability :one
SELECT id, provider_id, model_id, display_name, output_types, supported_operations, supported_input_node_types, limits, pricing, defaults, enabled, created_at, updated_at
FROM model_capability
WHERE provider_id = $1
  AND model_id = $2
  AND enabled = true
`

type GetEnabledModelCapabilityParams struct {
	ProviderID string `json:"provider_id"`
	ModelID    string `json:"model_id"`
}

func (q *Queries) GetEnabledModelCapability(ctx context.Context, arg GetEnabledModelCapabilityParams) (ModelCapability, error) {
	row := q.db.QueryRow(ctx, getEnabledModelCapability, arg.ProviderID, arg.ModelID)
	var i ModelCapability
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.OutputTypes,
		&i.SupportedOperations,
		&i.SupportedInputNodeTypes,
		&i.Limits,
		&i.Pricing,
		&i.Defaults,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledModelProvider = `-- name: GetEnabledModelProvider :one
SELECT id, display_name, provider_type, config, enabled, created_at, updated_at
FROM model_provider
WHERE id = $1
  AND enabled = true
`

func (q *Queries) GetEnabledModelProvider(ctx context.Context, id string) (ModelProvider, error) {
	row := q.db.QueryRow(ctx, getEnabledModelProvider, id)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ProviderType,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledModelCapabilities = `-- name: ListEnabledModelCapabilities :many
SELECT id, provider_id, model_id, display_name, output_types, supported_operations, supported_input_node_types, limits, pricing, defaults, enabled, created_at, updated_at
FROM model_capability
WHERE enabled = true
ORDER BY provider_id, model_id
`

func (q *Queries) ListEnabledModelCapabilities(ctx context.Context) ([]ModelCapability, error) {
	rows, err := q.db.Query(ctx, listEnabledModelCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelCapability{}
	for rows.Next() {
		var i ModelCapability
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ModelID,
			&i.DisplayName,
			&i.OutputTypes,
			&i.SupportedOperations,
			&i.SupportedInputNodeTypes,
			&i.Limits,
			&i.Pricing,
			&i.Defaults,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
