// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EdgeType string

const (
	EdgeTypeDependency EdgeType = "dependency"
	EdgeTypeReference  EdgeType = "reference"
	EdgeTypeSequence   EdgeType = "sequence"
)

func (e *EdgeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EdgeType(s)
	case string:
		*e = EdgeType(s)
	default:
		return fmt.Errorf("unsupported scan type for EdgeType: %T", src)
	}
	return nil
}

type NullEdgeType struct {
	EdgeType EdgeType `json:"edge_type"`
	Valid    bool     `json:"valid"` // Valid is true if EdgeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEdgeType) Scan(value interface{}) error {
	if value == nil {
		ns.EdgeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EdgeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEdgeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EdgeType), nil
}

type MediaType string

const (
	MediaTypeText  MediaType = "text"
	MediaTypeImage MediaType = "image"
	MediaTypeVideo MediaType = "video"
	MediaTypeAudio MediaType = "audio"
)

func (e *MediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaType(s)
	case string:
		*e = MediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaType: %T", src)
	}
	return nil
}

type NullMediaType struct {
	MediaType MediaType `json:"media_type"`
	Valid     bool      `json:"valid"` // Valid is true if MediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaType), nil
}

type NodeStatus string

const (
	NodeStatusDraft       NodeStatus = "draft"
	NodeStatusReady       NodeStatus = "ready"
	NodeStatusQueued      NodeStatus = "queued"
	NodeStatusRunning     NodeStatus = "running"
	NodeStatusSucceeded   NodeStatus = "succeeded"
	NodeStatusFailed      NodeStatus = "failed"
	NodeStatusStale       NodeStatus = "stale"
	NodeStatusUserEditing NodeStatus = "user_editing"
)

func (e *NodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeStatus(s)
	case string:
		*e = NodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeStatus: %T", src)
	}
	return nil
}

type NullNodeStatus struct {
	NodeStatus NodeStatus `json:"node_status"`
	Valid      bool       `json:"valid"` // Valid is true if NodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeStatus), nil
}

type TransitionType string

const (
	TransitionTypeCut       TransitionType = "cut"
	TransitionTypeCrossfade TransitionType = "crossfade"
	TransitionTypeDissolve  TransitionType = "dissolve"
	TransitionTypeWipe      TransitionType = "wipe"
)

func (e *TransitionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransitionType(s)
	case string:
		*e = TransitionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransitionType: %T", src)
	}
	return nil
}

type NullTransitionType struct {
	TransitionType TransitionType `json:"transition_type"`
	Valid          bool           `json:"valid"` // Valid is true if TransitionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransitionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransitionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransitionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransitionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransitionType), nil
}

type Account struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CanvasDocument struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	CameraX       float32            `json:"camera_x"`
	CameraY       float32            `json:"camera_y"`
	CameraZoom    float32            `json:"camera_zoom"`
	LayoutVersion int32              `json:"layout_version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MediaAsset struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Type         MediaType          `json:"type"`
	Mime         string             `json:"mime"`
	StorageUrl   string             `json:"storage_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	SizeBytes    pgtype.Int8        `json:"size_bytes"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MediaEdge struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	FromNodeID         pgtype.UUID        `json:"from_node_id"`
	ToNodeID           pgtype.UUID        `json:"to_node_id"`
	EdgeType           EdgeType           `json:"edge_type"`
	TransitionType     NullTransitionType `json:"transition_type"`
	TransitionDuration pgtype.Float4      `json:"transition_duration"`
	Source             string             `json:"source"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type MediaGroup struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MediaNode struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	NodeType    MediaType          `json:"node_type"`
	Title       string             `json:"title"`
	Status      NodeStatus         `json:"status"`
	Prompt      string             `json:"prompt"`
	Source      string             `json:"source"`
	CanvasX     float32            `json:"canvas_x"`
	CanvasY     float32            `json:"canvas_y"`
	CanvasW     float32            `json:"canvas_w"`
	CanvasH     float32            `json:"canvas_h"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GroupID     pgtype.UUID        `json:"group_id"`
	AssetID     pgtype.UUID        `json:"asset_id"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
