// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetType string

const (
	AssetTypeText  AssetType = "text"
	AssetTypeImage AssetType = "image"
	AssetTypeVideo AssetType = "video"
	AssetTypeAudio AssetType = "audio"
	AssetTypeJson  AssetType = "json"
)

func (e *AssetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetType(s)
	case string:
		*e = AssetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetType: %T", src)
	}
	return nil
}

type NullAssetType struct {
	AssetType AssetType `json:"asset_type"`
	Valid     bool      `json:"valid"` // Valid is true if AssetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetType), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusCancelled JobStatus = "cancelled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type NodeStatus string

const (
	NodeStatusDraft       NodeStatus = "draft"
	NodeStatusReady       NodeStatus = "ready"
	NodeStatusQueued      NodeStatus = "queued"
	NodeStatusRunning     NodeStatus = "running"
	NodeStatusSucceeded   NodeStatus = "succeeded"
	NodeStatusFailed      NodeStatus = "failed"
	NodeStatusStale       NodeStatus = "stale"
	NodeStatusUserEditing NodeStatus = "user_editing"
)

func (e *NodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeStatus(s)
	case string:
		*e = NodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeStatus: %T", src)
	}
	return nil
}

type NullNodeStatus struct {
	NodeStatus NodeStatus `json:"node_status"`
	Valid      bool       `json:"valid"` // Valid is true if NodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeStatus), nil
}

type NodeType string

const (
	NodeTypeText          NodeType = "text"
	NodeTypeImage         NodeType = "image"
	NodeTypeVideo         NodeType = "video"
	NodeTypeAudio         NodeType = "audio"
	NodeTypeReferencePack NodeType = "reference_pack"
)

func (e *NodeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeType(s)
	case string:
		*e = NodeType(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeType: %T", src)
	}
	return nil
}

type NullNodeType struct {
	NodeType NodeType `json:"node_type"`
	Valid    bool     `json:"valid"` // Valid is true if NodeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeType) Scan(value interface{}) error {
	if value == nil {
		ns.NodeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeType), nil
}

type WorkspaceMode string

const (
	WorkspaceModeStudio WorkspaceMode = "studio"
	WorkspaceModeAgent  WorkspaceMode = "agent"
)

func (e *WorkspaceMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceMode(s)
	case string:
		*e = WorkspaceMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceMode: %T", src)
	}
	return nil
}

type NullWorkspaceMode struct {
	WorkspaceMode WorkspaceMode `json:"workspace_mode"`
	Valid         bool          `json:"valid"` // Valid is true if WorkspaceMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceMode) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceMode), nil
}

type Account struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AgentContextCompaction struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	ThreadID               pgtype.UUID        `json:"thread_id"`
	TaskID                 pgtype.UUID        `json:"task_id"`
	Role                   string             `json:"role"`
	Mode                   string             `json:"mode"`
	Trigger                string             `json:"trigger"`
	SemanticKey            string             `json:"semantic_key"`
	SourceSeqStart         int64              `json:"source_seq_start"`
	SourceSeqEnd           int64              `json:"source_seq_end"`
	SourceMessageIds       []byte             `json:"source_message_ids"`
	SourceMediaRefs        []byte             `json:"source_media_refs"`
	OriginalTokenEstimate  int64              `json:"original_token_estimate"`
	CompactedTokenEstimate int64              `json:"compacted_token_estimate"`
	OriginalBytes          int64              `json:"original_bytes"`
	Summary                string             `json:"summary"`
	DetailFiles            []byte             `json:"detail_files"`
	Payload                []byte             `json:"payload"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type AgentEvent struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	EventType   string             `json:"event_type"`
	SourceRole  string             `json:"source_role"`
	TargetRole  pgtype.Text        `json:"target_role"`
	Scope       []byte             `json:"scope"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	HandledAt   pgtype.Timestamptz `json:"handled_at"`
}

type AgentMessage struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	Seq         int64              `json:"seq"`
	Role        string             `json:"role"`
	MessageType string             `json:"message_type"`
	Content     []byte             `json:"content"`
	RawMessage  []byte             `json:"raw_message"`
	TaskID      pgtype.UUID        `json:"task_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AgentMessageCompaction struct {
	MessageID     pgtype.UUID        `json:"message_id"`
	CompactionID  pgtype.UUID        `json:"compaction_id"`
	CompactedRole string             `json:"compacted_role"`
	CompactedAt   pgtype.Timestamptz `json:"compacted_at"`
}

type AgentObjectIndex struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ObjectType        string             `json:"object_type"`
	ObjectID          pgtype.UUID        `json:"object_id"`
	SemanticKey       string             `json:"semantic_key"`
	DisplayName       string             `json:"display_name"`
	ParentObjectType  string             `json:"parent_object_type"`
	ParentObjectID    pgtype.UUID        `json:"parent_object_id"`
	ParentSemanticKey string             `json:"parent_semantic_key"`
	Status            string             `json:"status"`
	Kind              string             `json:"kind"`
	SortOrder         int32              `json:"sort_order"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AgentTask struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	ThreadID     pgtype.UUID        `json:"thread_id"`
	Role         string             `json:"role"`
	ScopeType    string             `json:"scope_type"`
	ScopeID      pgtype.UUID        `json:"scope_id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	Attempt      int32              `json:"attempt"`
	MaxAttempts  int32              `json:"max_attempts"`
	Input        []byte             `json:"input"`
	Output       []byte             `json:"output"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	RenderPlanID pgtype.UUID        `json:"render_plan_id"`
	SemanticKey  string             `json:"semantic_key"`
	DisplayName  string             `json:"display_name"`
}

type AgentThread struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	Role                 string             `json:"role"`
	ScopeType            string             `json:"scope_type"`
	ScopeID              pgtype.UUID        `json:"scope_id"`
	RuntimeProvider      string             `json:"runtime_provider"`
	RuntimeAgentName     string             `json:"runtime_agent_name"`
	CurrentCheckpointKey pgtype.Text        `json:"current_checkpoint_key"`
	Status               string             `json:"status"`
	Summary              string             `json:"summary"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SemanticKey          string             `json:"semantic_key"`
	DisplayName          string             `json:"display_name"`
}

type ArtifactIssue struct {
	ID                       pgtype.UUID        `json:"id"`
	WorkspaceID              pgtype.UUID        `json:"workspace_id"`
	ReviewRecordID           pgtype.UUID        `json:"review_record_id"`
	Dimension                string             `json:"dimension"`
	Severity                 string             `json:"severity"`
	Status                   string             `json:"status"`
	TargetObjectType         string             `json:"target_object_type"`
	TargetObjectID           pgtype.UUID        `json:"target_object_id"`
	Title                    string             `json:"title"`
	Description              string             `json:"description"`
	Evidence                 string             `json:"evidence"`
	SuggestedFix             string             `json:"suggested_fix"`
	FixHint                  string             `json:"fix_hint"`
	RequiresUserConfirmation bool               `json:"requires_user_confirmation"`
	SupersededByIssueID      pgtype.UUID        `json:"superseded_by_issue_id"`
	ResolvedByReviewRecordID pgtype.UUID        `json:"resolved_by_review_record_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	SemanticKey              string             `json:"semantic_key"`
	DisplayName              string             `json:"display_name"`
}

type ArtifactVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	NodeID             pgtype.UUID        `json:"node_id"`
	JobID              pgtype.UUID        `json:"job_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	VersionNo          int32              `json:"version_no"`
	Winner             bool               `json:"winner"`
	Output             []byte             `json:"output"`
	ReviewScore        pgtype.Float4      `json:"review_score"`
	InputHash          string             `json:"input_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Status             JobStatus          `json:"status"`
	Progress           int32              `json:"progress"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	ProviderRequest    []byte             `json:"provider_request"`
	ProviderResponse   []byte             `json:"provider_response"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	SemanticKey        string             `json:"semantic_key"`
	DisplayName        string             `json:"display_name"`
	ArtifactKind       string             `json:"artifact_kind"`
	SourceRenderPlanID pgtype.UUID        `json:"source_render_plan_id"`
}

type AudioPlan struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	Status                string             `json:"status"`
	Title                 string             `json:"title"`
	PlanKind              string             `json:"plan_kind"`
	Language              string             `json:"language"`
	TargetDurationSec     pgtype.Float8      `json:"target_duration_sec"`
	VoiceoverScript       string             `json:"voiceover_script"`
	VoiceProfile          []byte             `json:"voice_profile"`
	BgmPlan               []byte             `json:"bgm_plan"`
	CuePlan               []byte             `json:"cue_plan"`
	GenerationParams      []byte             `json:"generation_params"`
	VoiceoverRenderPlanID pgtype.UUID        `json:"voiceover_render_plan_id"`
	BgmRenderPlanID       pgtype.UUID        `json:"bgm_render_plan_id"`
	VoiceoverNodeID       pgtype.UUID        `json:"voiceover_node_id"`
	BgmNodeID             pgtype.UUID        `json:"bgm_node_id"`
	TimelinePlanID        pgtype.UUID        `json:"timeline_plan_id"`
	CreatedByRole         string             `json:"created_by_role"`
	CreatedByTaskID       pgtype.UUID        `json:"created_by_task_id"`
	SemanticKey           string             `json:"semantic_key"`
	DisplayName           string             `json:"display_name"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type CanvasDocument struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	CameraX       float32            `json:"camera_x"`
	CameraY       float32            `json:"camera_y"`
	CameraZoom    float32            `json:"camera_zoom"`
	LayoutVersion int32              `json:"layout_version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CreativeBrief struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Title             string             `json:"title"`
	VideoType         string             `json:"video_type"`
	TargetAudience    string             `json:"target_audience"`
	Tone              string             `json:"tone"`
	VisualStyle       string             `json:"visual_style"`
	DurationSec       pgtype.Float8      `json:"duration_sec"`
	AspectRatio       string             `json:"aspect_ratio"`
	Language          string             `json:"language"`
	Objective         string             `json:"objective"`
	Concept           string             `json:"concept"`
	Constraints       []byte             `json:"constraints"`
	Metadata          []byte             `json:"metadata"`
	Status            string             `json:"status"`
	CreatedByThreadID pgtype.UUID        `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID        `json:"created_by_task_id"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SemanticKey       string             `json:"semantic_key"`
	DisplayName       string             `json:"display_name"`
}

type EinoCheckpoint struct {
	Key         string             `json:"key"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Value       []byte             `json:"value"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GenerationJob struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	TargetNodeID       pgtype.UUID        `json:"target_node_id"`
	ParentJobID        pgtype.UUID        `json:"parent_job_id"`
	OperationType      string             `json:"operation_type"`
	Provider           string             `json:"provider"`
	ModelID            string             `json:"model_id"`
	Intent             []byte             `json:"intent"`
	RenderedPrompt     string             `json:"rendered_prompt"`
	ProviderRequest    []byte             `json:"provider_request"`
	ProviderResponse   []byte             `json:"provider_response"`
	Status             JobStatus          `json:"status"`
	Progress           int32              `json:"progress"`
	Attempt            int32              `json:"attempt"`
	MaxAttempts        int32              `json:"max_attempts"`
	RetryPolicy        []byte             `json:"retry_policy"`
	CostCents          pgtype.Int4        `json:"cost_cents"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	RequestedByType    string             `json:"requested_by_type"`
	RequestedByID      pgtype.Text        `json:"requested_by_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SemanticKey        string             `json:"semantic_key"`
	DisplayName        string             `json:"display_name"`
	SourceRenderPlanID pgtype.UUID        `json:"source_render_plan_id"`
}

type KeyElement struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ClientKey         string             `json:"client_key"`
	ElementType       string             `json:"element_type"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	SourceType        string             `json:"source_type"`
	SourceRefs        []byte             `json:"source_refs"`
	Status            string             `json:"status"`
	CreatedByThreadID pgtype.UUID        `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID        `json:"created_by_task_id"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SemanticKey       string             `json:"semantic_key"`
	DisplayName       string             `json:"display_name"`
}

type KeyElementState struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	KeyElementID       pgtype.UUID        `json:"key_element_id"`
	ClientKey          string             `json:"client_key"`
	Label              string             `json:"label"`
	VisualDescription  string             `json:"visual_description"`
	ReferenceStatus    string             `json:"reference_status"`
	ReferenceNodeID    pgtype.UUID        `json:"reference_node_id"`
	ReferenceVersionID pgtype.UUID        `json:"reference_version_id"`
	IsDefault          bool               `json:"is_default"`
	StateFacts         []byte             `json:"state_facts"`
	SourceRefs         []byte             `json:"source_refs"`
	Status             string             `json:"status"`
	CreatedByThreadID  pgtype.UUID        `json:"created_by_thread_id"`
	CreatedByTaskID    pgtype.UUID        `json:"created_by_task_id"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SemanticKey        string             `json:"semantic_key"`
	DisplayName        string             `json:"display_name"`
}

type MediaAsset struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Type         AssetType          `json:"type"`
	Mime         string             `json:"mime"`
	StorageUrl   pgtype.Text        `json:"storage_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	SizeBytes    pgtype.Int8        `json:"size_bytes"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TextContent  pgtype.Text        `json:"text_content"`
}

type MediaEdge struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	FromNodeID  pgtype.UUID        `json:"from_node_id"`
	ToNodeID    pgtype.UUID        `json:"to_node_id"`
	Source      string             `json:"source"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MediaGroup struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MediaNode struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	NodeType           NodeType           `json:"node_type"`
	Title              string             `json:"title"`
	Status             NodeStatus         `json:"status"`
	Prompt             string             `json:"prompt"`
	Source             string             `json:"source"`
	CanvasX            float32            `json:"canvas_x"`
	CanvasY            float32            `json:"canvas_y"`
	CanvasW            float32            `json:"canvas_w"`
	CanvasH            float32            `json:"canvas_h"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	GroupID            pgtype.UUID        `json:"group_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	OperationType      string             `json:"operation_type"`
	PromptTemplate     string             `json:"prompt_template"`
	PromptRich         []byte             `json:"prompt_rich"`
	PromptRefs         []byte             `json:"prompt_refs"`
	ModelProvider      pgtype.Text        `json:"model_provider"`
	ModelID            pgtype.Text        `json:"model_id"`
	ModelParams        []byte             `json:"model_params"`
	CurrentVersionID   pgtype.UUID        `json:"current_version_id"`
	Metadata           []byte             `json:"metadata"`
	ShotID             pgtype.UUID        `json:"shot_id"`
	SemanticKey        string             `json:"semantic_key"`
	DisplayName        string             `json:"display_name"`
	ArtifactKind       string             `json:"artifact_kind"`
	SourceRenderPlanID pgtype.UUID        `json:"source_render_plan_id"`
}

type ModelCapability struct {
	ID                      pgtype.UUID        `json:"id"`
	ProviderID              string             `json:"provider_id"`
	ModelID                 string             `json:"model_id"`
	DisplayName             string             `json:"display_name"`
	OutputTypes             []byte             `json:"output_types"`
	SupportedOperations     []byte             `json:"supported_operations"`
	SupportedInputNodeTypes []byte             `json:"supported_input_node_types"`
	Limits                  []byte             `json:"limits"`
	Pricing                 []byte             `json:"pricing"`
	Defaults                []byte             `json:"defaults"`
	Enabled                 bool               `json:"enabled"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ModelProvider struct {
	ID           string             `json:"id"`
	DisplayName  string             `json:"display_name"`
	ProviderType string             `json:"provider_type"`
	Config       []byte             `json:"config"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type NodeStaleReason struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	NodeID            pgtype.UUID        `json:"node_id"`
	UpstreamNodeID    pgtype.UUID        `json:"upstream_node_id"`
	UpstreamVersionID pgtype.UUID        `json:"upstream_version_id"`
	ReasonCode        string             `json:"reason_code"`
	ReasonMessage     string             `json:"reason_message"`
	Details           []byte             `json:"details"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProducerPendingSignal struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ProducerThreadID  pgtype.UUID        `json:"producer_thread_id"`
	SourceRole        string             `json:"source_role"`
	SourceTaskID      pgtype.UUID        `json:"source_task_id"`
	SourceThreadID    pgtype.UUID        `json:"source_thread_id"`
	SignalType        string             `json:"signal_type"`
	ScopeType         string             `json:"scope_type"`
	ScopeID           pgtype.UUID        `json:"scope_id"`
	RenderPlanID      pgtype.UUID        `json:"render_plan_id"`
	MessageID         pgtype.UUID        `json:"message_id"`
	Status            string             `json:"status"`
	Priority          int32              `json:"priority"`
	DedupeKey         string             `json:"dedupe_key"`
	Payload           []byte             `json:"payload"`
	ClaimedByTaskID   pgtype.UUID        `json:"claimed_by_task_id"`
	ClaimedAt         pgtype.Timestamptz `json:"claimed_at"`
	ProcessedByTaskID pgtype.UUID        `json:"processed_by_task_id"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	LastError         pgtype.Text        `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SemanticKey       string             `json:"semantic_key"`
	DisplayName       string             `json:"display_name"`
}

type ProjectMemory struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	Version              int32              `json:"version"`
	Status               string             `json:"status"`
	CoreIntent           string             `json:"core_intent"`
	Soul                 string             `json:"soul"`
	BrandFacts           []byte             `json:"brand_facts"`
	NonNegotiables       []byte             `json:"non_negotiables"`
	VisualAnchors        []byte             `json:"visual_anchors"`
	Allowed              []byte             `json:"allowed"`
	Forbidden            []byte             `json:"forbidden"`
	PromptInjectionHints []byte             `json:"prompt_injection_hints"`
	SourceRefs           []byte             `json:"source_refs"`
	CreatedByThreadID    pgtype.UUID        `json:"created_by_thread_id"`
	CreatedByTaskID      pgtype.UUID        `json:"created_by_task_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	SemanticKey          string             `json:"semantic_key"`
	DisplayName          string             `json:"display_name"`
}

type ReferencePackItem struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	PackNodeID   pgtype.UUID        `json:"pack_node_id"`
	MemberNodeID pgtype.UUID        `json:"member_node_id"`
	Position     int32              `json:"position"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RenderPlan struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	ScopeType              string             `json:"scope_type"`
	ScopeID                pgtype.UUID        `json:"scope_id"`
	TargetPhase            string             `json:"target_phase"`
	TaskType               string             `json:"task_type"`
	ModelPromptProfile     string             `json:"model_prompt_profile"`
	Operation              string             `json:"operation"`
	Status                 string             `json:"status"`
	Revision               int32              `json:"revision"`
	ForkedFromRenderPlanID pgtype.UUID        `json:"forked_from_render_plan_id"`
	RenderPlanKey          string             `json:"render_plan_key"`
	ReferenceBindings      []byte             `json:"reference_bindings"`
	SubjectBindings        []byte             `json:"subject_bindings"`
	PromptParts            []byte             `json:"prompt_parts"`
	Params                 []byte             `json:"params"`
	AuditHints             []byte             `json:"audit_hints"`
	Blocker                []byte             `json:"blocker"`
	CompiledPrompt         string             `json:"compiled_prompt"`
	CompiledRequest        []byte             `json:"compiled_request"`
	PromptAudit            []byte             `json:"prompt_audit"`
	CostEstimate           []byte             `json:"cost_estimate"`
	Rationale              string             `json:"rationale"`
	CreatedByThreadID      pgtype.UUID        `json:"created_by_thread_id"`
	CreatedByTaskID        pgtype.UUID        `json:"created_by_task_id"`
	SubmittedWorkerTaskID  pgtype.UUID        `json:"submitted_worker_task_id"`
	OutputNodeID           pgtype.UUID        `json:"output_node_id"`
	OutputVersionID        pgtype.UUID        `json:"output_version_id"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CompiledAt             pgtype.Timestamptz `json:"compiled_at"`
	SubmittedAt            pgtype.Timestamptz `json:"submitted_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	SemanticKey            string             `json:"semantic_key"`
	DisplayName            string             `json:"display_name"`
}

type ReviewRecord struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	ShotID               pgtype.UUID        `json:"shot_id"`
	NodeID               pgtype.UUID        `json:"node_id"`
	ArtifactVersionID    pgtype.UUID        `json:"artifact_version_id"`
	GenerationJobID      pgtype.UUID        `json:"generation_job_id"`
	ReviewerThreadID     pgtype.UUID        `json:"reviewer_thread_id"`
	ReviewerTaskID       pgtype.UUID        `json:"reviewer_task_id"`
	ParentReviewRecordID pgtype.UUID        `json:"parent_review_record_id"`
	TargetPhase          string             `json:"target_phase"`
	Status               string             `json:"status"`
	AttemptNo            int32              `json:"attempt_no"`
	MaxAttempts          int32              `json:"max_attempts"`
	OverallScore         pgtype.Float4      `json:"overall_score"`
	Rubric               []byte             `json:"rubric"`
	Critique             string             `json:"critique"`
	RetryRecommendation  []byte             `json:"retry_recommendation"`
	ModelProvider        string             `json:"model_provider"`
	ModelID              string             `json:"model_id"`
	ErrorCode            string             `json:"error_code"`
	ErrorMessage         string             `json:"error_message"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ReviewTask           string             `json:"review_task"`
	TargetObjectType     string             `json:"target_object_type"`
	TargetObjectID       pgtype.UUID        `json:"target_object_id"`
	RenderPlanID         pgtype.UUID        `json:"render_plan_id"`
	RequiredAxes         []byte             `json:"required_axes"`
	Escalation           []byte             `json:"escalation"`
	SemanticKey          string             `json:"semantic_key"`
	DisplayName          string             `json:"display_name"`
}

type SandboxJob struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	TargetNodeID    pgtype.UUID        `json:"target_node_id"`
	GenerationJobID pgtype.UUID        `json:"generation_job_id"`
	JobType         string             `json:"job_type"`
	OperationType   string             `json:"operation_type"`
	Status          JobStatus          `json:"status"`
	SandboxID       pgtype.Text        `json:"sandbox_id"`
	Command         string             `json:"command"`
	Cwd             string             `json:"cwd"`
	Input           []byte             `json:"input"`
	Output          []byte             `json:"output"`
	ExitCode        pgtype.Int4        `json:"exit_code"`
	Stdout          string             `json:"stdout"`
	Stderr          string             `json:"stderr"`
	DurationMs      int32              `json:"duration_ms"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Scene struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ClientKey         string             `json:"client_key"`
	SortOrder         int32              `json:"sort_order"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Location          string             `json:"location"`
	Mood              string             `json:"mood"`
	Status            string             `json:"status"`
	CreatedByThreadID pgtype.UUID        `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID        `json:"created_by_task_id"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SemanticKey       string             `json:"semantic_key"`
	DisplayName       string             `json:"display_name"`
}

type Shot struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ClientKey         string             `json:"client_key"`
	SortOrder         int32              `json:"sort_order"`
	Title             string             `json:"title"`
	Brief             []byte             `json:"brief"`
	DurationSec       pgtype.Float8      `json:"duration_sec"`
	NarrativePurpose  string             `json:"narrative_purpose"`
	Status            string             `json:"status"`
	CraftsmanThreadID pgtype.UUID        `json:"craftsman_thread_id"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SceneID           pgtype.UUID        `json:"scene_id"`
	ShotKind          string             `json:"shot_kind"`
	CreativeText      string             `json:"creative_text"`
	VisualIntent      string             `json:"visual_intent"`
	ActionText        string             `json:"action_text"`
	CameraIntent      string             `json:"camera_intent"`
	Dialogue          string             `json:"dialogue"`
	Narration         string             `json:"narration"`
	AudioPlan         []byte             `json:"audio_plan"`
	SemanticKey       string             `json:"semantic_key"`
	DisplayName       string             `json:"display_name"`
}

type ShotDependency struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	FromShotID       pgtype.UUID        `json:"from_shot_id"`
	ToShotID         pgtype.UUID        `json:"to_shot_id"`
	DependencyType   string             `json:"dependency_type"`
	RequiredArtifact string             `json:"required_artifact"`
	InjectionRole    string             `json:"injection_role"`
	BlockingPhase    string             `json:"blocking_phase"`
	StalePolicy      string             `json:"stale_policy"`
	Reason           string             `json:"reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SemanticKey      string             `json:"semantic_key"`
	DisplayName      string             `json:"display_name"`
}

type ShotKeyElement struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ShotID            pgtype.UUID        `json:"shot_id"`
	KeyElementID      pgtype.UUID        `json:"key_element_id"`
	KeyElementStateID pgtype.UUID        `json:"key_element_state_id"`
	Role              string             `json:"role"`
	Required          bool               `json:"required"`
	SortOrder         int32              `json:"sort_order"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type TimelinePlan struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	SourceStoryboardNodeID pgtype.UUID        `json:"source_storyboard_node_id"`
	OutputNodeID           pgtype.UUID        `json:"output_node_id"`
	ProductionJobID        pgtype.UUID        `json:"production_job_id"`
	ArtifactVersionID      pgtype.UUID        `json:"artifact_version_id"`
	SandboxJobID           pgtype.UUID        `json:"sandbox_job_id"`
	Status                 string             `json:"status"`
	TemplateKey            string             `json:"template_key"`
	PlanJson               []byte             `json:"plan_json"`
	RenderSettings         []byte             `json:"render_settings"`
	Result                 []byte             `json:"result"`
	ErrorMessage           pgtype.Text        `json:"error_message"`
	CreatedByRole          string             `json:"created_by_role"`
	CreatedByTaskID        pgtype.UUID        `json:"created_by_task_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Mode      WorkspaceMode      `json:"mode"`
}

type WorkspaceSandbox struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	SandboxID         pgtype.Text        `json:"sandbox_id"`
	VolumeName        string             `json:"volume_name"`
	Status            string             `json:"status"`
	LastHealthCheckAt pgtype.Timestamptz `json:"last_health_check_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
