// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMediaNodeGroup = `-- name: ClearMediaNodeGroup :one
UPDATE media_node
SET group_id = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

func (q *Queries) ClearMediaNodeGroup(ctx context.Context, id pgtype.UUID) (MediaNode, error) {
	row := q.db.QueryRow(ctx, clearMediaNodeGroup, id)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const createAgentMediaNode = `-- name: CreateAgentMediaNode :one
INSERT INTO media_node (
    workspace_id,
    node_type,
    title,
    prompt,
    prompt_template,
    status,
    source,
    asset_id,
    canvas_x,
    canvas_y,
    canvas_w,
    canvas_h
)
VALUES ($1, $2, $3, $4, $4, 'succeeded', 'agent', $5, $6, $7, $8, $9)
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type CreateAgentMediaNodeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeType    NodeType    `json:"node_type"`
	Title       string      `json:"title"`
	Prompt      string      `json:"prompt"`
	AssetID     pgtype.UUID `json:"asset_id"`
	CanvasX     float32     `json:"canvas_x"`
	CanvasY     float32     `json:"canvas_y"`
	CanvasW     float32     `json:"canvas_w"`
	CanvasH     float32     `json:"canvas_h"`
}

func (q *Queries) CreateAgentMediaNode(ctx context.Context, arg CreateAgentMediaNodeParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, createAgentMediaNode,
		arg.WorkspaceID,
		arg.NodeType,
		arg.Title,
		arg.Prompt,
		arg.AssetID,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasW,
		arg.CanvasH,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const createMediaNode = `-- name: CreateMediaNode :one
INSERT INTO media_node (
    workspace_id,
    node_type,
    title,
    prompt,
    prompt_template,
    asset_id,
    canvas_x,
    canvas_y,
    canvas_w,
    canvas_h
)
VALUES ($1, $2, $3, $4, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type CreateMediaNodeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeType    NodeType    `json:"node_type"`
	Title       string      `json:"title"`
	Prompt      string      `json:"prompt"`
	AssetID     pgtype.UUID `json:"asset_id"`
	CanvasX     float32     `json:"canvas_x"`
	CanvasY     float32     `json:"canvas_y"`
	CanvasW     float32     `json:"canvas_w"`
	CanvasH     float32     `json:"canvas_h"`
}

func (q *Queries) CreateMediaNode(ctx context.Context, arg CreateMediaNodeParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, createMediaNode,
		arg.WorkspaceID,
		arg.NodeType,
		arg.Title,
		arg.Prompt,
		arg.AssetID,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasW,
		arg.CanvasH,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const createMediaNodeWithID = `-- name: CreateMediaNodeWithID :one
INSERT INTO media_node (
    id,
    workspace_id,
    node_type,
    title,
    prompt,
    prompt_template,
    status,
    asset_id,
    canvas_x,
    canvas_y,
    canvas_w,
    canvas_h
)
VALUES ($1, $2, $3, $4, $5, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type CreateMediaNodeWithIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeType    NodeType    `json:"node_type"`
	Title       string      `json:"title"`
	Prompt      string      `json:"prompt"`
	Status      NodeStatus  `json:"status"`
	AssetID     pgtype.UUID `json:"asset_id"`
	CanvasX     float32     `json:"canvas_x"`
	CanvasY     float32     `json:"canvas_y"`
	CanvasW     float32     `json:"canvas_w"`
	CanvasH     float32     `json:"canvas_h"`
}

func (q *Queries) CreateMediaNodeWithID(ctx context.Context, arg CreateMediaNodeWithIDParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, createMediaNodeWithID,
		arg.ID,
		arg.WorkspaceID,
		arg.NodeType,
		arg.Title,
		arg.Prompt,
		arg.Status,
		arg.AssetID,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasW,
		arg.CanvasH,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const deleteMediaNode = `-- name: DeleteMediaNode :exec
DELETE FROM media_node
WHERE id = $1
`

func (q *Queries) DeleteMediaNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaNode, id)
	return err
}

const getMediaNodeByID = `-- name: GetMediaNodeByID :one
SELECT id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
FROM media_node
WHERE id = $1
`

func (q *Queries) GetMediaNodeByID(ctx context.Context, id pgtype.UUID) (MediaNode, error) {
	row := q.db.QueryRow(ctx, getMediaNodeByID, id)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const listDownstreamDependencyNodes = `-- name: ListDownstreamDependencyNodes :many
SELECT media_node.id, media_node.workspace_id, media_node.node_type, media_node.title, media_node.status, media_node.prompt, media_node.source, media_node.canvas_x, media_node.canvas_y, media_node.canvas_w, media_node.canvas_h, media_node.created_at, media_node.updated_at, media_node.group_id, media_node.asset_id, media_node.operation_type, media_node.prompt_template, media_node.prompt_rich, media_node.prompt_refs, media_node.model_provider, media_node.model_id, media_node.model_params, media_node.current_version_id, media_node.metadata
FROM media_node
JOIN media_edge ON media_edge.to_node_id = media_node.id
WHERE media_edge.from_node_id = $1
ORDER BY media_edge.created_at
`

func (q *Queries) ListDownstreamDependencyNodes(ctx context.Context, fromNodeID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listDownstreamDependencyNodes, fromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AssetID,
			&i.OperationType,
			&i.PromptTemplate,
			&i.PromptRich,
			&i.PromptRefs,
			&i.ModelProvider,
			&i.ModelID,
			&i.ModelParams,
			&i.CurrentVersionID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaNodesByGroup = `-- name: ListMediaNodesByGroup :many
SELECT id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
FROM media_node
WHERE group_id = $1
ORDER BY created_at
`

func (q *Queries) ListMediaNodesByGroup(ctx context.Context, groupID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listMediaNodesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AssetID,
			&i.OperationType,
			&i.PromptTemplate,
			&i.PromptRich,
			&i.PromptRefs,
			&i.ModelProvider,
			&i.ModelID,
			&i.ModelParams,
			&i.CurrentVersionID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaNodesByWorkspace = `-- name: ListMediaNodesByWorkspace :many
SELECT id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
FROM media_node
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListMediaNodesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listMediaNodesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AssetID,
			&i.OperationType,
			&i.PromptTemplate,
			&i.PromptRich,
			&i.PromptRefs,
			&i.ModelProvider,
			&i.ModelID,
			&i.ModelParams,
			&i.CurrentVersionID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpstreamDependencyNodes = `-- name: ListUpstreamDependencyNodes :many
SELECT media_node.id, media_node.workspace_id, media_node.node_type, media_node.title, media_node.status, media_node.prompt, media_node.source, media_node.canvas_x, media_node.canvas_y, media_node.canvas_w, media_node.canvas_h, media_node.created_at, media_node.updated_at, media_node.group_id, media_node.asset_id, media_node.operation_type, media_node.prompt_template, media_node.prompt_rich, media_node.prompt_refs, media_node.model_provider, media_node.model_id, media_node.model_params, media_node.current_version_id, media_node.metadata
FROM media_node
JOIN media_edge ON media_edge.from_node_id = media_node.id
WHERE media_edge.to_node_id = $1
ORDER BY media_edge.created_at
`

func (q *Queries) ListUpstreamDependencyNodes(ctx context.Context, toNodeID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listUpstreamDependencyNodes, toNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AssetID,
			&i.OperationType,
			&i.PromptTemplate,
			&i.PromptRich,
			&i.PromptRefs,
			&i.ModelProvider,
			&i.ModelID,
			&i.ModelParams,
			&i.CurrentVersionID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaNodeAsset = `-- name: UpdateMediaNodeAsset :one
UPDATE media_node
SET asset_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodeAssetParams struct {
	ID      pgtype.UUID `json:"id"`
	AssetID pgtype.UUID `json:"asset_id"`
}

func (q *Queries) UpdateMediaNodeAsset(ctx context.Context, arg UpdateMediaNodeAssetParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeAsset, arg.ID, arg.AssetID)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodeCurrentVersion = `-- name: UpdateMediaNodeCurrentVersion :one
UPDATE media_node
SET current_version_id = $2,
    status = 'succeeded',
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodeCurrentVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
}

func (q *Queries) UpdateMediaNodeCurrentVersion(ctx context.Context, arg UpdateMediaNodeCurrentVersionParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeCurrentVersion, arg.ID, arg.CurrentVersionID)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodeGroup = `-- name: UpdateMediaNodeGroup :one
UPDATE media_node
SET group_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodeGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) UpdateMediaNodeGroup(ctx context.Context, arg UpdateMediaNodeGroupParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeGroup, arg.ID, arg.GroupID)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodePosition = `-- name: UpdateMediaNodePosition :one
UPDATE media_node
SET canvas_x = $2,
    canvas_y = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodePositionParams struct {
	ID      pgtype.UUID `json:"id"`
	CanvasX float32     `json:"canvas_x"`
	CanvasY float32     `json:"canvas_y"`
}

func (q *Queries) UpdateMediaNodePosition(ctx context.Context, arg UpdateMediaNodePositionParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodePosition, arg.ID, arg.CanvasX, arg.CanvasY)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodeProductionConfig = `-- name: UpdateMediaNodeProductionConfig :one
UPDATE media_node
SET operation_type = $2,
    prompt_template = $3,
    prompt = $3,
    model_provider = $4,
    model_id = $5,
    model_params = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodeProductionConfigParams struct {
	ID             pgtype.UUID `json:"id"`
	OperationType  string      `json:"operation_type"`
	PromptTemplate string      `json:"prompt_template"`
	ModelProvider  pgtype.Text `json:"model_provider"`
	ModelID        pgtype.Text `json:"model_id"`
	ModelParams    []byte      `json:"model_params"`
}

func (q *Queries) UpdateMediaNodeProductionConfig(ctx context.Context, arg UpdateMediaNodeProductionConfigParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeProductionConfig,
		arg.ID,
		arg.OperationType,
		arg.PromptTemplate,
		arg.ModelProvider,
		arg.ModelID,
		arg.ModelParams,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodePrompt = `-- name: UpdateMediaNodePrompt :one
UPDATE media_node
SET prompt = $2,
    prompt_template = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodePromptParams struct {
	ID     pgtype.UUID `json:"id"`
	Prompt string      `json:"prompt"`
}

func (q *Queries) UpdateMediaNodePrompt(ctx context.Context, arg UpdateMediaNodePromptParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodePrompt, arg.ID, arg.Prompt)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodeStatus = `-- name: UpdateMediaNodeStatus :one
UPDATE media_node
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status NodeStatus  `json:"status"`
}

func (q *Queries) UpdateMediaNodeStatus(ctx context.Context, arg UpdateMediaNodeStatusParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeStatus, arg.ID, arg.Status)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}

const updateMediaNodeTitle = `-- name: UpdateMediaNodeTitle :one
UPDATE media_node
SET title = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at, group_id, asset_id, operation_type, prompt_template, prompt_rich, prompt_refs, model_provider, model_id, model_params, current_version_id, metadata
`

type UpdateMediaNodeTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateMediaNodeTitle(ctx context.Context, arg UpdateMediaNodeTitleParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeTitle, arg.ID, arg.Title)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AssetID,
		&i.OperationType,
		&i.PromptTemplate,
		&i.PromptRich,
		&i.PromptRefs,
		&i.ModelProvider,
		&i.ModelID,
		&i.ModelParams,
		&i.CurrentVersionID,
		&i.Metadata,
	)
	return i, err
}
