// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaNode = `-- name: CreateMediaNode :one
INSERT INTO media_node (
    workspace_id,
    node_type,
    title,
    prompt,
    canvas_x,
    canvas_y,
    canvas_w,
    canvas_h
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
`

type CreateMediaNodeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeType    MediaType   `json:"node_type"`
	Title       string      `json:"title"`
	Prompt      string      `json:"prompt"`
	CanvasX     float32     `json:"canvas_x"`
	CanvasY     float32     `json:"canvas_y"`
	CanvasW     float32     `json:"canvas_w"`
	CanvasH     float32     `json:"canvas_h"`
}

func (q *Queries) CreateMediaNode(ctx context.Context, arg CreateMediaNodeParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, createMediaNode,
		arg.WorkspaceID,
		arg.NodeType,
		arg.Title,
		arg.Prompt,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasW,
		arg.CanvasH,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaNodeWithID = `-- name: CreateMediaNodeWithID :one
INSERT INTO media_node (
    id,
    workspace_id,
    node_type,
    title,
    prompt,
    status,
    canvas_x,
    canvas_y,
    canvas_w,
    canvas_h
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
`

type CreateMediaNodeWithIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeType    MediaType   `json:"node_type"`
	Title       string      `json:"title"`
	Prompt      string      `json:"prompt"`
	Status      NodeStatus  `json:"status"`
	CanvasX     float32     `json:"canvas_x"`
	CanvasY     float32     `json:"canvas_y"`
	CanvasW     float32     `json:"canvas_w"`
	CanvasH     float32     `json:"canvas_h"`
}

func (q *Queries) CreateMediaNodeWithID(ctx context.Context, arg CreateMediaNodeWithIDParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, createMediaNodeWithID,
		arg.ID,
		arg.WorkspaceID,
		arg.NodeType,
		arg.Title,
		arg.Prompt,
		arg.Status,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasW,
		arg.CanvasH,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaNode = `-- name: DeleteMediaNode :exec
DELETE FROM media_node
WHERE id = $1
`

func (q *Queries) DeleteMediaNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaNode, id)
	return err
}

const getMediaNodeByID = `-- name: GetMediaNodeByID :one
SELECT id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
FROM media_node
WHERE id = $1
`

func (q *Queries) GetMediaNodeByID(ctx context.Context, id pgtype.UUID) (MediaNode, error) {
	row := q.db.QueryRow(ctx, getMediaNodeByID, id)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaNodesByWorkspace = `-- name: ListMediaNodesByWorkspace :many
SELECT id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
FROM media_node
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListMediaNodesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listMediaNodesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaNodePosition = `-- name: UpdateMediaNodePosition :one
UPDATE media_node
SET canvas_x = $2,
    canvas_y = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
`

type UpdateMediaNodePositionParams struct {
	ID      pgtype.UUID `json:"id"`
	CanvasX float32     `json:"canvas_x"`
	CanvasY float32     `json:"canvas_y"`
}

func (q *Queries) UpdateMediaNodePosition(ctx context.Context, arg UpdateMediaNodePositionParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodePosition, arg.ID, arg.CanvasX, arg.CanvasY)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaNodePrompt = `-- name: UpdateMediaNodePrompt :one
UPDATE media_node
SET prompt = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
`

type UpdateMediaNodePromptParams struct {
	ID     pgtype.UUID `json:"id"`
	Prompt string      `json:"prompt"`
}

func (q *Queries) UpdateMediaNodePrompt(ctx context.Context, arg UpdateMediaNodePromptParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodePrompt, arg.ID, arg.Prompt)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaNodeStatus = `-- name: UpdateMediaNodeStatus :one
UPDATE media_node
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
`

type UpdateMediaNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status NodeStatus  `json:"status"`
}

func (q *Queries) UpdateMediaNodeStatus(ctx context.Context, arg UpdateMediaNodeStatusParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeStatus, arg.ID, arg.Status)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaNodeTitle = `-- name: UpdateMediaNodeTitle :one
UPDATE media_node
SET title = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, node_type, title, status, prompt, source, canvas_x, canvas_y, canvas_w, canvas_h, created_at, updated_at
`

type UpdateMediaNodeTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateMediaNodeTitle(ctx context.Context, arg UpdateMediaNodeTitleParams) (MediaNode, error) {
	row := q.db.QueryRow(ctx, updateMediaNodeTitle, arg.ID, arg.Title)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeType,
		&i.Title,
		&i.Status,
		&i.Prompt,
		&i.Source,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasW,
		&i.CanvasH,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
