// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearArtifactWinnersForNode = `-- name: ClearArtifactWinnersForNode :exec
UPDATE artifact_version
SET winner = false
WHERE node_id = $1
  AND winner = true
`

func (q *Queries) ClearArtifactWinnersForNode(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearArtifactWinnersForNode, nodeID)
	return err
}

const createArtifactVersion = `-- name: CreateArtifactVersion :one
INSERT INTO artifact_version (
    workspace_id,
    node_id,
    job_id,
    asset_id,
    version_no,
    winner,
    output,
    review_score,
    input_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, workspace_id, node_id, job_id, asset_id, version_no, winner, output, review_score, input_hash, created_at
`

type CreateArtifactVersionParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	NodeID      pgtype.UUID   `json:"node_id"`
	JobID       pgtype.UUID   `json:"job_id"`
	AssetID     pgtype.UUID   `json:"asset_id"`
	VersionNo   int32         `json:"version_no"`
	Winner      bool          `json:"winner"`
	Output      []byte        `json:"output"`
	ReviewScore pgtype.Float4 `json:"review_score"`
	InputHash   string        `json:"input_hash"`
}

func (q *Queries) CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, createArtifactVersion,
		arg.WorkspaceID,
		arg.NodeID,
		arg.JobID,
		arg.AssetID,
		arg.VersionNo,
		arg.Winner,
		arg.Output,
		arg.ReviewScore,
		arg.InputHash,
	)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.JobID,
		&i.AssetID,
		&i.VersionNo,
		&i.Winner,
		&i.Output,
		&i.ReviewScore,
		&i.InputHash,
		&i.CreatedAt,
	)
	return i, err
}

const createGenerationJob = `-- name: CreateGenerationJob :one
INSERT INTO generation_job (
    workspace_id,
    target_node_id,
    parent_job_id,
    operation_type,
    provider,
    model_id,
    intent,
    rendered_prompt,
    provider_request,
    provider_response,
    status,
    progress,
    attempt,
    max_attempts,
    retry_policy,
    cost_cents,
    error_code,
    error_message,
    requested_by_type,
    requested_by_id,
    started_at,
    completed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
) RETURNING id, workspace_id, target_node_id, parent_job_id, operation_type, provider, model_id, intent, rendered_prompt, provider_request, provider_response, status, progress, attempt, max_attempts, retry_policy, cost_cents, error_code, error_message, requested_by_type, requested_by_id, started_at, completed_at, created_at
`

type CreateGenerationJobParams struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	TargetNodeID     pgtype.UUID        `json:"target_node_id"`
	ParentJobID      pgtype.UUID        `json:"parent_job_id"`
	OperationType    string             `json:"operation_type"`
	Provider         string             `json:"provider"`
	ModelID          string             `json:"model_id"`
	Intent           []byte             `json:"intent"`
	RenderedPrompt   string             `json:"rendered_prompt"`
	ProviderRequest  []byte             `json:"provider_request"`
	ProviderResponse []byte             `json:"provider_response"`
	Status           JobStatus          `json:"status"`
	Progress         int32              `json:"progress"`
	Attempt          int32              `json:"attempt"`
	MaxAttempts      int32              `json:"max_attempts"`
	RetryPolicy      []byte             `json:"retry_policy"`
	CostCents        pgtype.Int4        `json:"cost_cents"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	RequestedByType  string             `json:"requested_by_type"`
	RequestedByID    pgtype.Text        `json:"requested_by_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, createGenerationJob,
		arg.WorkspaceID,
		arg.TargetNodeID,
		arg.ParentJobID,
		arg.OperationType,
		arg.Provider,
		arg.ModelID,
		arg.Intent,
		arg.RenderedPrompt,
		arg.ProviderRequest,
		arg.ProviderResponse,
		arg.Status,
		arg.Progress,
		arg.Attempt,
		arg.MaxAttempts,
		arg.RetryPolicy,
		arg.CostCents,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.RequestedByType,
		arg.RequestedByID,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.ParentJobID,
		&i.OperationType,
		&i.Provider,
		&i.ModelID,
		&i.Intent,
		&i.RenderedPrompt,
		&i.ProviderRequest,
		&i.ProviderResponse,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryPolicy,
		&i.CostCents,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestedByType,
		&i.RequestedByID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactVersionByID = `-- name: GetArtifactVersionByID :one
SELECT id, workspace_id, node_id, job_id, asset_id, version_no, winner, output, review_score, input_hash, created_at
FROM artifact_version
WHERE id = $1
`

func (q *Queries) GetArtifactVersionByID(ctx context.Context, id pgtype.UUID) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersionByID, id)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.JobID,
		&i.AssetID,
		&i.VersionNo,
		&i.Winner,
		&i.Output,
		&i.ReviewScore,
		&i.InputHash,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentArtifactVersionForNode = `-- name: GetCurrentArtifactVersionForNode :one
SELECT artifact_version.id, artifact_version.workspace_id, artifact_version.node_id, artifact_version.job_id, artifact_version.asset_id, artifact_version.version_no, artifact_version.winner, artifact_version.output, artifact_version.review_score, artifact_version.input_hash, artifact_version.created_at
FROM artifact_version
JOIN media_node ON media_node.current_version_id = artifact_version.id
WHERE media_node.id = $1
`

func (q *Queries) GetCurrentArtifactVersionForNode(ctx context.Context, id pgtype.UUID) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentArtifactVersionForNode, id)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.JobID,
		&i.AssetID,
		&i.VersionNo,
		&i.Winner,
		&i.Output,
		&i.ReviewScore,
		&i.InputHash,
		&i.CreatedAt,
	)
	return i, err
}

const getGenerationJobByID = `-- name: GetGenerationJobByID :one
SELECT id, workspace_id, target_node_id, parent_job_id, operation_type, provider, model_id, intent, rendered_prompt, provider_request, provider_response, status, progress, attempt, max_attempts, retry_policy, cost_cents, error_code, error_message, requested_by_type, requested_by_id, started_at, completed_at, created_at
FROM generation_job
WHERE id = $1
`

func (q *Queries) GetGenerationJobByID(ctx context.Context, id pgtype.UUID) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByID, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.ParentJobID,
		&i.OperationType,
		&i.Provider,
		&i.ModelID,
		&i.Intent,
		&i.RenderedPrompt,
		&i.ProviderRequest,
		&i.ProviderResponse,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryPolicy,
		&i.CostCents,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestedByType,
		&i.RequestedByID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const latestGenerationJobByNode = `-- name: LatestGenerationJobByNode :one
SELECT id, workspace_id, target_node_id, parent_job_id, operation_type, provider, model_id, intent, rendered_prompt, provider_request, provider_response, status, progress, attempt, max_attempts, retry_policy, cost_cents, error_code, error_message, requested_by_type, requested_by_id, started_at, completed_at, created_at
FROM generation_job
WHERE target_node_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestGenerationJobByNode(ctx context.Context, targetNodeID pgtype.UUID) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, latestGenerationJobByNode, targetNodeID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.ParentJobID,
		&i.OperationType,
		&i.Provider,
		&i.ModelID,
		&i.Intent,
		&i.RenderedPrompt,
		&i.ProviderRequest,
		&i.ProviderResponse,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryPolicy,
		&i.CostCents,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestedByType,
		&i.RequestedByID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const latestGenerationJobInChain = `-- name: LatestGenerationJobInChain :one
WITH RECURSIVE chain AS (
    SELECT generation_job.id, generation_job.workspace_id, generation_job.target_node_id, generation_job.parent_job_id, generation_job.operation_type, generation_job.provider, generation_job.model_id, generation_job.intent, generation_job.rendered_prompt, generation_job.provider_request, generation_job.provider_response, generation_job.status, generation_job.progress, generation_job.attempt, generation_job.max_attempts, generation_job.retry_policy, generation_job.cost_cents, generation_job.error_code, generation_job.error_message, generation_job.requested_by_type, generation_job.requested_by_id, generation_job.started_at, generation_job.completed_at, generation_job.created_at
    FROM generation_job
    WHERE generation_job.id = $1
    UNION ALL
    SELECT child.id, child.workspace_id, child.target_node_id, child.parent_job_id, child.operation_type, child.provider, child.model_id, child.intent, child.rendered_prompt, child.provider_request, child.provider_response, child.status, child.progress, child.attempt, child.max_attempts, child.retry_policy, child.cost_cents, child.error_code, child.error_message, child.requested_by_type, child.requested_by_id, child.started_at, child.completed_at, child.created_at
    FROM generation_job child
    JOIN chain parent ON child.parent_job_id = parent.id
)
SELECT id, workspace_id, target_node_id, parent_job_id, operation_type, provider, model_id, intent, rendered_prompt, provider_request, provider_response, status, progress, attempt, max_attempts, retry_policy, cost_cents, error_code, error_message, requested_by_type, requested_by_id, started_at, completed_at, created_at
FROM chain
ORDER BY attempt DESC, created_at DESC
LIMIT 1
`

type LatestGenerationJobInChainRow struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	TargetNodeID     pgtype.UUID        `json:"target_node_id"`
	ParentJobID      pgtype.UUID        `json:"parent_job_id"`
	OperationType    string             `json:"operation_type"`
	Provider         string             `json:"provider"`
	ModelID          string             `json:"model_id"`
	Intent           []byte             `json:"intent"`
	RenderedPrompt   string             `json:"rendered_prompt"`
	ProviderRequest  []byte             `json:"provider_request"`
	ProviderResponse []byte             `json:"provider_response"`
	Status           JobStatus          `json:"status"`
	Progress         int32              `json:"progress"`
	Attempt          int32              `json:"attempt"`
	MaxAttempts      int32              `json:"max_attempts"`
	RetryPolicy      []byte             `json:"retry_policy"`
	CostCents        pgtype.Int4        `json:"cost_cents"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	RequestedByType  string             `json:"requested_by_type"`
	RequestedByID    pgtype.Text        `json:"requested_by_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LatestGenerationJobInChain(ctx context.Context, id pgtype.UUID) (LatestGenerationJobInChainRow, error) {
	row := q.db.QueryRow(ctx, latestGenerationJobInChain, id)
	var i LatestGenerationJobInChainRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.ParentJobID,
		&i.OperationType,
		&i.Provider,
		&i.ModelID,
		&i.Intent,
		&i.RenderedPrompt,
		&i.ProviderRequest,
		&i.ProviderResponse,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryPolicy,
		&i.CostCents,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestedByType,
		&i.RequestedByID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStaleReasonsByNode = `-- name: ListActiveStaleReasonsByNode :many
SELECT id, workspace_id, node_id, upstream_node_id, upstream_version_id, reason_code, reason_message, details, resolved_at, created_at
FROM node_stale_reason
WHERE node_id = $1
  AND resolved_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListActiveStaleReasonsByNode(ctx context.Context, nodeID pgtype.UUID) ([]NodeStaleReason, error) {
	rows, err := q.db.Query(ctx, listActiveStaleReasonsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeStaleReason{}
	for rows.Next() {
		var i NodeStaleReason
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeID,
			&i.UpstreamNodeID,
			&i.UpstreamVersionID,
			&i.ReasonCode,
			&i.ReasonMessage,
			&i.Details,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersionsByNode = `-- name: ListArtifactVersionsByNode :many
SELECT id, workspace_id, node_id, job_id, asset_id, version_no, winner, output, review_score, input_hash, created_at
FROM artifact_version
WHERE node_id = $1
ORDER BY version_no
`

func (q *Queries) ListArtifactVersionsByNode(ctx context.Context, nodeID pgtype.UUID) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactVersion{}
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeID,
			&i.JobID,
			&i.AssetID,
			&i.VersionNo,
			&i.Winner,
			&i.Output,
			&i.ReviewScore,
			&i.InputHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationJobsByNode = `-- name: ListGenerationJobsByNode :many
SELECT id, workspace_id, target_node_id, parent_job_id, operation_type, provider, model_id, intent, rendered_prompt, provider_request, provider_response, status, progress, attempt, max_attempts, retry_policy, cost_cents, error_code, error_message, requested_by_type, requested_by_id, started_at, completed_at, created_at
FROM generation_job
WHERE target_node_id = $1
ORDER BY created_at
`

func (q *Queries) ListGenerationJobsByNode(ctx context.Context, targetNodeID pgtype.UUID) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByNode, targetNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationJob{}
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetNodeID,
			&i.ParentJobID,
			&i.OperationType,
			&i.Provider,
			&i.ModelID,
			&i.Intent,
			&i.RenderedPrompt,
			&i.ProviderRequest,
			&i.ProviderResponse,
			&i.Status,
			&i.Progress,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryPolicy,
			&i.CostCents,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RequestedByType,
			&i.RequestedByID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationJobsByParent = `-- name: ListGenerationJobsByParent :many
SELECT id, workspace_id, target_node_id, parent_job_id, operation_type, provider, model_id, intent, rendered_prompt, provider_request, provider_response, status, progress, attempt, max_attempts, retry_policy, cost_cents, error_code, error_message, requested_by_type, requested_by_id, started_at, completed_at, created_at
FROM generation_job
WHERE parent_job_id = $1
ORDER BY attempt
`

func (q *Queries) ListGenerationJobsByParent(ctx context.Context, parentJobID pgtype.UUID) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByParent, parentJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationJob{}
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetNodeID,
			&i.ParentJobID,
			&i.OperationType,
			&i.Provider,
			&i.ModelID,
			&i.Intent,
			&i.RenderedPrompt,
			&i.ProviderRequest,
			&i.ProviderResponse,
			&i.Status,
			&i.Progress,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryPolicy,
			&i.CostCents,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RequestedByType,
			&i.RequestedByID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextArtifactVersionNo = `-- name: NextArtifactVersionNo :one
SELECT COALESCE(MAX(version_no), 0)::int + 1 AS version_no
FROM artifact_version
WHERE node_id = $1
`

func (q *Queries) NextArtifactVersionNo(ctx context.Context, nodeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextArtifactVersionNo, nodeID)
	var version_no int32
	err := row.Scan(&version_no)
	return version_no, err
}

const resolveActiveStaleReasonsByNode = `-- name: ResolveActiveStaleReasonsByNode :exec
UPDATE node_stale_reason
SET resolved_at = now()
WHERE node_id = $1
  AND resolved_at IS NULL
`

func (q *Queries) ResolveActiveStaleReasonsByNode(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resolveActiveStaleReasonsByNode, nodeID)
	return err
}

const upsertNodeStaleReason = `-- name: UpsertNodeStaleReason :one
INSERT INTO node_stale_reason (
    workspace_id,
    node_id,
    upstream_node_id,
    upstream_version_id,
    reason_code,
    reason_message,
    details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (node_id, upstream_node_id, reason_code)
WHERE resolved_at IS NULL
DO UPDATE SET
    upstream_version_id = EXCLUDED.upstream_version_id,
    reason_message = EXCLUDED.reason_message,
    details = EXCLUDED.details,
    created_at = now()
RETURNING id, workspace_id, node_id, upstream_node_id, upstream_version_id, reason_code, reason_message, details, resolved_at, created_at
`

type UpsertNodeStaleReasonParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	NodeID            pgtype.UUID `json:"node_id"`
	UpstreamNodeID    pgtype.UUID `json:"upstream_node_id"`
	UpstreamVersionID pgtype.UUID `json:"upstream_version_id"`
	ReasonCode        string      `json:"reason_code"`
	ReasonMessage     string      `json:"reason_message"`
	Details           []byte      `json:"details"`
}

func (q *Queries) UpsertNodeStaleReason(ctx context.Context, arg UpsertNodeStaleReasonParams) (NodeStaleReason, error) {
	row := q.db.QueryRow(ctx, upsertNodeStaleReason,
		arg.WorkspaceID,
		arg.NodeID,
		arg.UpstreamNodeID,
		arg.UpstreamVersionID,
		arg.ReasonCode,
		arg.ReasonMessage,
		arg.Details,
	)
	var i NodeStaleReason
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.UpstreamNodeID,
		&i.UpstreamVersionID,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Details,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}
