// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: producer_pending_signal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProducerPendingSignals = `-- name: ClaimProducerPendingSignals :many
WITH picked AS (
    SELECT producer_pending_signal.id
    FROM producer_pending_signal
    WHERE producer_pending_signal.workspace_id = $1
      AND producer_pending_signal.producer_thread_id = $2
      AND (
        producer_pending_signal.status = 'pending'
        OR (
            producer_pending_signal.status = 'claimed'
            AND producer_pending_signal.claimed_at < now() - make_interval(secs => $4::int)
        )
      )
    ORDER BY producer_pending_signal.priority ASC, producer_pending_signal.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $5
)
UPDATE producer_pending_signal
SET status = 'claimed',
    claimed_by_task_id = $3,
    claimed_at = now(),
    last_error = NULL,
    updated_at = now()
WHERE id IN (SELECT id FROM picked)
RETURNING id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
`

type ClaimProducerPendingSignalsParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ProducerThreadID  pgtype.UUID `json:"producer_thread_id"`
	ClaimedByTaskID   pgtype.UUID `json:"claimed_by_task_id"`
	StaleAfterSeconds int32       `json:"stale_after_seconds"`
	RowLimit          int32       `json:"row_limit"`
}

func (q *Queries) ClaimProducerPendingSignals(ctx context.Context, arg ClaimProducerPendingSignalsParams) ([]ProducerPendingSignal, error) {
	rows, err := q.db.Query(ctx, claimProducerPendingSignals,
		arg.WorkspaceID,
		arg.ProducerThreadID,
		arg.ClaimedByTaskID,
		arg.StaleAfterSeconds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProducerPendingSignal{}
	for rows.Next() {
		var i ProducerPendingSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProducerThreadID,
			&i.SourceRole,
			&i.SourceTaskID,
			&i.SourceThreadID,
			&i.SignalType,
			&i.ScopeType,
			&i.ScopeID,
			&i.RenderPlanID,
			&i.MessageID,
			&i.Status,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.ClaimedByTaskID,
			&i.ClaimedAt,
			&i.ProcessedByTaskID,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProducerPendingSignal = `-- name: CreateProducerPendingSignal :one
WITH proposed AS (
    SELECT
        gen_random_uuid() AS id,
        COALESCE(
            (SELECT render_plan.semantic_key FROM render_plan WHERE render_plan.id = $9),
            $7 || '.' || left(COALESCE($8::uuid::text, $1::uuid::text), 8)
        ) AS source_semantic_key
)
INSERT INTO producer_pending_signal (
    id,
    workspace_id,
    producer_thread_id,
    source_role,
    source_task_id,
    source_thread_id,
    signal_type,
    scope_type,
    scope_id,
    render_plan_id,
    message_id,
    status,
    priority,
    dedupe_key,
    payload,
    last_error,
    semantic_key,
    display_name
)
SELECT
    proposed.id,
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    'pending', $11, $12, $13, NULL,
    COALESCE(
        NULLIF($14::text, ''),
        'signal.' || proposed.source_semantic_key || '.' || $6 || '.' || left(proposed.id::text, 8)
    ),
    COALESCE(NULLIF($15::text, ''), $6)
FROM proposed
ON CONFLICT (workspace_id, dedupe_key) DO UPDATE
SET producer_thread_id = EXCLUDED.producer_thread_id,
    source_role = EXCLUDED.source_role,
    source_task_id = EXCLUDED.source_task_id,
    source_thread_id = EXCLUDED.source_thread_id,
    signal_type = EXCLUDED.signal_type,
    scope_type = EXCLUDED.scope_type,
    scope_id = EXCLUDED.scope_id,
    render_plan_id = EXCLUDED.render_plan_id,
    message_id = EXCLUDED.message_id,
    status = CASE
        WHEN producer_pending_signal.status IN ('processed', 'ignored') THEN producer_pending_signal.status
        ELSE 'pending'
    END,
    priority = EXCLUDED.priority,
    payload = EXCLUDED.payload,
    claimed_by_task_id = CASE
        WHEN producer_pending_signal.status IN ('processed', 'ignored') THEN producer_pending_signal.claimed_by_task_id
        ELSE NULL
    END,
    claimed_at = CASE
        WHEN producer_pending_signal.status IN ('processed', 'ignored') THEN producer_pending_signal.claimed_at
        ELSE NULL
    END,
    last_error = NULL,
    semantic_key = COALESCE(NULLIF($14::text, ''), EXCLUDED.semantic_key),
    display_name = COALESCE(NULLIF($15::text, ''), EXCLUDED.display_name),
    updated_at = now()
RETURNING id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
`

type CreateProducerPendingSignalParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ProducerThreadID pgtype.UUID `json:"producer_thread_id"`
	SourceRole       string      `json:"source_role"`
	SourceTaskID     pgtype.UUID `json:"source_task_id"`
	SourceThreadID   pgtype.UUID `json:"source_thread_id"`
	SignalType       string      `json:"signal_type"`
	ScopeType        string      `json:"scope_type"`
	ScopeID          pgtype.UUID `json:"scope_id"`
	RenderPlanID     pgtype.UUID `json:"render_plan_id"`
	MessageID        pgtype.UUID `json:"message_id"`
	Priority         int32       `json:"priority"`
	DedupeKey        string      `json:"dedupe_key"`
	Payload          []byte      `json:"payload"`
	SemanticKey      string      `json:"semantic_key"`
	DisplayName      string      `json:"display_name"`
}

func (q *Queries) CreateProducerPendingSignal(ctx context.Context, arg CreateProducerPendingSignalParams) (ProducerPendingSignal, error) {
	row := q.db.QueryRow(ctx, createProducerPendingSignal,
		arg.WorkspaceID,
		arg.ProducerThreadID,
		arg.SourceRole,
		arg.SourceTaskID,
		arg.SourceThreadID,
		arg.SignalType,
		arg.ScopeType,
		arg.ScopeID,
		arg.RenderPlanID,
		arg.MessageID,
		arg.Priority,
		arg.DedupeKey,
		arg.Payload,
		arg.SemanticKey,
		arg.DisplayName,
	)
	var i ProducerPendingSignal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProducerThreadID,
		&i.SourceRole,
		&i.SourceTaskID,
		&i.SourceThreadID,
		&i.SignalType,
		&i.ScopeType,
		&i.ScopeID,
		&i.RenderPlanID,
		&i.MessageID,
		&i.Status,
		&i.Priority,
		&i.DedupeKey,
		&i.Payload,
		&i.ClaimedByTaskID,
		&i.ClaimedAt,
		&i.ProcessedByTaskID,
		&i.ProcessedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const listClaimedProducerSignalsByTask = `-- name: ListClaimedProducerSignalsByTask :many
SELECT id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
FROM producer_pending_signal
WHERE workspace_id = $1
  AND producer_thread_id = $2
  AND status = 'claimed'
  AND claimed_by_task_id = $3
ORDER BY priority ASC, created_at ASC
`

type ListClaimedProducerSignalsByTaskParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ProducerThreadID pgtype.UUID `json:"producer_thread_id"`
	ClaimedByTaskID  pgtype.UUID `json:"claimed_by_task_id"`
}

func (q *Queries) ListClaimedProducerSignalsByTask(ctx context.Context, arg ListClaimedProducerSignalsByTaskParams) ([]ProducerPendingSignal, error) {
	rows, err := q.db.Query(ctx, listClaimedProducerSignalsByTask, arg.WorkspaceID, arg.ProducerThreadID, arg.ClaimedByTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProducerPendingSignal{}
	for rows.Next() {
		var i ProducerPendingSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProducerThreadID,
			&i.SourceRole,
			&i.SourceTaskID,
			&i.SourceThreadID,
			&i.SignalType,
			&i.ScopeType,
			&i.ScopeID,
			&i.RenderPlanID,
			&i.MessageID,
			&i.Status,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.ClaimedByTaskID,
			&i.ClaimedAt,
			&i.ProcessedByTaskID,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProducerSignals = `-- name: ListPendingProducerSignals :many
SELECT id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
FROM producer_pending_signal
WHERE workspace_id = $1
  AND status IN ('pending', 'claimed', 'failed')
ORDER BY priority ASC, created_at ASC
LIMIT $2
`

type ListPendingProducerSignalsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListPendingProducerSignals(ctx context.Context, arg ListPendingProducerSignalsParams) ([]ProducerPendingSignal, error) {
	rows, err := q.db.Query(ctx, listPendingProducerSignals, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProducerPendingSignal{}
	for rows.Next() {
		var i ProducerPendingSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProducerThreadID,
			&i.SourceRole,
			&i.SourceTaskID,
			&i.SourceThreadID,
			&i.SignalType,
			&i.ScopeType,
			&i.ScopeID,
			&i.RenderPlanID,
			&i.MessageID,
			&i.Status,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.ClaimedByTaskID,
			&i.ClaimedAt,
			&i.ProcessedByTaskID,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProducerSignalsByThread = `-- name: ListPendingProducerSignalsByThread :many
SELECT id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
FROM producer_pending_signal
WHERE workspace_id = $1
  AND producer_thread_id = $2
  AND status IN ('pending', 'claimed', 'failed')
ORDER BY priority ASC, created_at ASC
LIMIT $3
`

type ListPendingProducerSignalsByThreadParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ProducerThreadID pgtype.UUID `json:"producer_thread_id"`
	Limit            int32       `json:"limit"`
}

func (q *Queries) ListPendingProducerSignalsByThread(ctx context.Context, arg ListPendingProducerSignalsByThreadParams) ([]ProducerPendingSignal, error) {
	rows, err := q.db.Query(ctx, listPendingProducerSignalsByThread, arg.WorkspaceID, arg.ProducerThreadID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProducerPendingSignal{}
	for rows.Next() {
		var i ProducerPendingSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProducerThreadID,
			&i.SourceRole,
			&i.SourceTaskID,
			&i.SourceThreadID,
			&i.SignalType,
			&i.ScopeType,
			&i.ScopeID,
			&i.RenderPlanID,
			&i.MessageID,
			&i.Status,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.ClaimedByTaskID,
			&i.ClaimedAt,
			&i.ProcessedByTaskID,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProducerPendingSignalIgnored = `-- name: MarkProducerPendingSignalIgnored :one
UPDATE producer_pending_signal
SET status = 'ignored',
    processed_by_task_id = $3,
    processed_at = now(),
    last_error = $4,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('pending', 'claimed', 'failed')
RETURNING id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
`

type MarkProducerPendingSignalIgnoredParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ProcessedByTaskID pgtype.UUID `json:"processed_by_task_id"`
	LastError         pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkProducerPendingSignalIgnored(ctx context.Context, arg MarkProducerPendingSignalIgnoredParams) (ProducerPendingSignal, error) {
	row := q.db.QueryRow(ctx, markProducerPendingSignalIgnored,
		arg.ID,
		arg.WorkspaceID,
		arg.ProcessedByTaskID,
		arg.LastError,
	)
	var i ProducerPendingSignal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProducerThreadID,
		&i.SourceRole,
		&i.SourceTaskID,
		&i.SourceThreadID,
		&i.SignalType,
		&i.ScopeType,
		&i.ScopeID,
		&i.RenderPlanID,
		&i.MessageID,
		&i.Status,
		&i.Priority,
		&i.DedupeKey,
		&i.Payload,
		&i.ClaimedByTaskID,
		&i.ClaimedAt,
		&i.ProcessedByTaskID,
		&i.ProcessedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markProducerPendingSignalProcessed = `-- name: MarkProducerPendingSignalProcessed :one
UPDATE producer_pending_signal
SET status = 'processed',
    processed_by_task_id = $3,
    processed_at = now(),
    last_error = NULL,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('pending', 'claimed', 'failed')
RETURNING id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
`

type MarkProducerPendingSignalProcessedParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ProcessedByTaskID pgtype.UUID `json:"processed_by_task_id"`
}

func (q *Queries) MarkProducerPendingSignalProcessed(ctx context.Context, arg MarkProducerPendingSignalProcessedParams) (ProducerPendingSignal, error) {
	row := q.db.QueryRow(ctx, markProducerPendingSignalProcessed, arg.ID, arg.WorkspaceID, arg.ProcessedByTaskID)
	var i ProducerPendingSignal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProducerThreadID,
		&i.SourceRole,
		&i.SourceTaskID,
		&i.SourceThreadID,
		&i.SignalType,
		&i.ScopeType,
		&i.ScopeID,
		&i.RenderPlanID,
		&i.MessageID,
		&i.Status,
		&i.Priority,
		&i.DedupeKey,
		&i.Payload,
		&i.ClaimedByTaskID,
		&i.ClaimedAt,
		&i.ProcessedByTaskID,
		&i.ProcessedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markProducerPendingSignalsProcessedByRenderPlan = `-- name: MarkProducerPendingSignalsProcessedByRenderPlan :many
UPDATE producer_pending_signal
SET status = 'processed',
    processed_by_task_id = $3,
    processed_at = now(),
    last_error = NULL,
    updated_at = now()
WHERE workspace_id = $1
  AND render_plan_id = $2
  AND signal_type = 'craftsman_render_plan_ready'
  AND status IN ('pending', 'claimed', 'failed')
RETURNING id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
`

type MarkProducerPendingSignalsProcessedByRenderPlanParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	RenderPlanID      pgtype.UUID `json:"render_plan_id"`
	ProcessedByTaskID pgtype.UUID `json:"processed_by_task_id"`
}

func (q *Queries) MarkProducerPendingSignalsProcessedByRenderPlan(ctx context.Context, arg MarkProducerPendingSignalsProcessedByRenderPlanParams) ([]ProducerPendingSignal, error) {
	rows, err := q.db.Query(ctx, markProducerPendingSignalsProcessedByRenderPlan, arg.WorkspaceID, arg.RenderPlanID, arg.ProcessedByTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProducerPendingSignal{}
	for rows.Next() {
		var i ProducerPendingSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProducerThreadID,
			&i.SourceRole,
			&i.SourceTaskID,
			&i.SourceThreadID,
			&i.SignalType,
			&i.ScopeType,
			&i.ScopeID,
			&i.RenderPlanID,
			&i.MessageID,
			&i.Status,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.ClaimedByTaskID,
			&i.ClaimedAt,
			&i.ProcessedByTaskID,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseProducerPendingSignalsForTask = `-- name: ReleaseProducerPendingSignalsForTask :many
UPDATE producer_pending_signal
SET status = 'pending',
    claimed_by_task_id = NULL,
    claimed_at = NULL,
    last_error = $3,
    updated_at = now()
WHERE workspace_id = $1
  AND claimed_by_task_id = $2
  AND status = 'claimed'
RETURNING id, workspace_id, producer_thread_id, source_role, source_task_id, source_thread_id, signal_type, scope_type, scope_id, render_plan_id, message_id, status, priority, dedupe_key, payload, claimed_by_task_id, claimed_at, processed_by_task_id, processed_at, last_error, created_at, updated_at, semantic_key, display_name
`

type ReleaseProducerPendingSignalsForTaskParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ClaimedByTaskID pgtype.UUID `json:"claimed_by_task_id"`
	LastError       pgtype.Text `json:"last_error"`
}

func (q *Queries) ReleaseProducerPendingSignalsForTask(ctx context.Context, arg ReleaseProducerPendingSignalsForTaskParams) ([]ProducerPendingSignal, error) {
	rows, err := q.db.Query(ctx, releaseProducerPendingSignalsForTask, arg.WorkspaceID, arg.ClaimedByTaskID, arg.LastError)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProducerPendingSignal{}
	for rows.Next() {
		var i ProducerPendingSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProducerThreadID,
			&i.SourceRole,
			&i.SourceTaskID,
			&i.SourceThreadID,
			&i.SignalType,
			&i.ScopeType,
			&i.ScopeID,
			&i.RenderPlanID,
			&i.MessageID,
			&i.Status,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.ClaimedByTaskID,
			&i.ClaimedAt,
			&i.ProcessedByTaskID,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
