// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference_video_analysis.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReferenceVideoAnalysis = `-- name: CreateReferenceVideoAnalysis :one
INSERT INTO reference_video_analysis (
    workspace_id,
    source_node_id,
    status,
    brief,
    focus,
    model_provider,
    model_id,
    request_summary,
    result,
    created_by_thread_id,
    created_by_task_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at
`

type CreateReferenceVideoAnalysisParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	SourceNodeID      pgtype.UUID `json:"source_node_id"`
	Status            string      `json:"status"`
	Brief             string      `json:"brief"`
	Focus             []byte      `json:"focus"`
	ModelProvider     string      `json:"model_provider"`
	ModelID           string      `json:"model_id"`
	RequestSummary    []byte      `json:"request_summary"`
	Result            []byte      `json:"result"`
	CreatedByThreadID pgtype.UUID `json:"created_by_thread_id"`
	CreatedByTaskID   pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateReferenceVideoAnalysis(ctx context.Context, arg CreateReferenceVideoAnalysisParams) (ReferenceVideoAnalysis, error) {
	row := q.db.QueryRow(ctx, createReferenceVideoAnalysis,
		arg.WorkspaceID,
		arg.SourceNodeID,
		arg.Status,
		arg.Brief,
		arg.Focus,
		arg.ModelProvider,
		arg.ModelID,
		arg.RequestSummary,
		arg.Result,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
	)
	var i ReferenceVideoAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceNodeID,
		&i.Status,
		&i.Brief,
		&i.Focus,
		&i.ModelProvider,
		&i.ModelID,
		&i.RequestSummary,
		&i.Result,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferenceVideoAnalysisByID = `-- name: GetReferenceVideoAnalysisByID :one
SELECT id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at FROM reference_video_analysis
WHERE id = $1
`

func (q *Queries) GetReferenceVideoAnalysisByID(ctx context.Context, id pgtype.UUID) (ReferenceVideoAnalysis, error) {
	row := q.db.QueryRow(ctx, getReferenceVideoAnalysisByID, id)
	var i ReferenceVideoAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceNodeID,
		&i.Status,
		&i.Brief,
		&i.Focus,
		&i.ModelProvider,
		&i.ModelID,
		&i.RequestSummary,
		&i.Result,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReferenceVideoAnalysesBySourceNode = `-- name: ListReferenceVideoAnalysesBySourceNode :many
SELECT id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at FROM reference_video_analysis
WHERE workspace_id = $1
  AND source_node_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListReferenceVideoAnalysesBySourceNodeParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	SourceNodeID pgtype.UUID `json:"source_node_id"`
	LimitCount   int32       `json:"limit_count"`
}

func (q *Queries) ListReferenceVideoAnalysesBySourceNode(ctx context.Context, arg ListReferenceVideoAnalysesBySourceNodeParams) ([]ReferenceVideoAnalysis, error) {
	rows, err := q.db.Query(ctx, listReferenceVideoAnalysesBySourceNode, arg.WorkspaceID, arg.SourceNodeID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferenceVideoAnalysis{}
	for rows.Next() {
		var i ReferenceVideoAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceNodeID,
			&i.Status,
			&i.Brief,
			&i.Focus,
			&i.ModelProvider,
			&i.ModelID,
			&i.RequestSummary,
			&i.Result,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceVideoAnalysesByWorkspace = `-- name: ListReferenceVideoAnalysesByWorkspace :many
SELECT id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at FROM reference_video_analysis
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListReferenceVideoAnalysesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListReferenceVideoAnalysesByWorkspace(ctx context.Context, arg ListReferenceVideoAnalysesByWorkspaceParams) ([]ReferenceVideoAnalysis, error) {
	rows, err := q.db.Query(ctx, listReferenceVideoAnalysesByWorkspace, arg.WorkspaceID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferenceVideoAnalysis{}
	for rows.Next() {
		var i ReferenceVideoAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceNodeID,
			&i.Status,
			&i.Brief,
			&i.Focus,
			&i.ModelProvider,
			&i.ModelID,
			&i.RequestSummary,
			&i.Result,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReferenceVideoAnalysisFailed = `-- name: MarkReferenceVideoAnalysisFailed :one
UPDATE reference_video_analysis
SET status = 'failed',
    request_summary = $1,
    error_code = $2,
    error_message = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at
`

type MarkReferenceVideoAnalysisFailedParams struct {
	RequestSummary []byte      `json:"request_summary"`
	ErrorCode      string      `json:"error_code"`
	ErrorMessage   string      `json:"error_message"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) MarkReferenceVideoAnalysisFailed(ctx context.Context, arg MarkReferenceVideoAnalysisFailedParams) (ReferenceVideoAnalysis, error) {
	row := q.db.QueryRow(ctx, markReferenceVideoAnalysisFailed,
		arg.RequestSummary,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	var i ReferenceVideoAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceNodeID,
		&i.Status,
		&i.Brief,
		&i.Focus,
		&i.ModelProvider,
		&i.ModelID,
		&i.RequestSummary,
		&i.Result,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReferenceVideoAnalysisRunning = `-- name: MarkReferenceVideoAnalysisRunning :one
UPDATE reference_video_analysis
SET status = 'running',
    request_summary = $1,
    model_provider = $2,
    model_id = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at
`

type MarkReferenceVideoAnalysisRunningParams struct {
	RequestSummary []byte      `json:"request_summary"`
	ModelProvider  string      `json:"model_provider"`
	ModelID        string      `json:"model_id"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) MarkReferenceVideoAnalysisRunning(ctx context.Context, arg MarkReferenceVideoAnalysisRunningParams) (ReferenceVideoAnalysis, error) {
	row := q.db.QueryRow(ctx, markReferenceVideoAnalysisRunning,
		arg.RequestSummary,
		arg.ModelProvider,
		arg.ModelID,
		arg.ID,
	)
	var i ReferenceVideoAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceNodeID,
		&i.Status,
		&i.Brief,
		&i.Focus,
		&i.ModelProvider,
		&i.ModelID,
		&i.RequestSummary,
		&i.Result,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReferenceVideoAnalysisSucceeded = `-- name: MarkReferenceVideoAnalysisSucceeded :one
UPDATE reference_video_analysis
SET status = 'succeeded',
    request_summary = $1,
    result = $2,
    error_code = '',
    error_message = '',
    updated_at = now()
WHERE id = $3
RETURNING id, workspace_id, source_node_id, status, brief, focus, model_provider, model_id, request_summary, result, error_code, error_message, created_by_thread_id, created_by_task_id, created_at, updated_at
`

type MarkReferenceVideoAnalysisSucceededParams struct {
	RequestSummary []byte      `json:"request_summary"`
	Result         []byte      `json:"result"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) MarkReferenceVideoAnalysisSucceeded(ctx context.Context, arg MarkReferenceVideoAnalysisSucceededParams) (ReferenceVideoAnalysis, error) {
	row := q.db.QueryRow(ctx, markReferenceVideoAnalysisSucceeded, arg.RequestSummary, arg.Result, arg.ID)
	var i ReferenceVideoAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceNodeID,
		&i.Status,
		&i.Brief,
		&i.Focus,
		&i.ModelProvider,
		&i.ModelID,
		&i.RequestSummary,
		&i.Result,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
