// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference_pack.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReferencePackItem = `-- name: CreateReferencePackItem :one
INSERT INTO reference_pack_item (
    workspace_id,
    pack_node_id,
    member_node_id,
    position,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, workspace_id, pack_node_id, member_node_id, position, metadata, created_at, updated_at
`

type CreateReferencePackItemParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	PackNodeID   pgtype.UUID `json:"pack_node_id"`
	MemberNodeID pgtype.UUID `json:"member_node_id"`
	Position     int32       `json:"position"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateReferencePackItem(ctx context.Context, arg CreateReferencePackItemParams) (ReferencePackItem, error) {
	row := q.db.QueryRow(ctx, createReferencePackItem,
		arg.WorkspaceID,
		arg.PackNodeID,
		arg.MemberNodeID,
		arg.Position,
		arg.Metadata,
	)
	var i ReferencePackItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PackNodeID,
		&i.MemberNodeID,
		&i.Position,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReferencePackItems = `-- name: DeleteReferencePackItems :exec
DELETE FROM reference_pack_item
WHERE pack_node_id = $1
`

func (q *Queries) DeleteReferencePackItems(ctx context.Context, packNodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReferencePackItems, packNodeID)
	return err
}

const listReferencePackItemNodes = `-- name: ListReferencePackItemNodes :many
SELECT media_node.id, media_node.workspace_id, media_node.node_type, media_node.title, media_node.status, media_node.prompt, media_node.source, media_node.canvas_x, media_node.canvas_y, media_node.canvas_w, media_node.canvas_h, media_node.created_at, media_node.updated_at, media_node.group_id, media_node.asset_id, media_node.operation_type, media_node.prompt_template, media_node.prompt_rich, media_node.prompt_refs, media_node.model_provider, media_node.model_id, media_node.model_params, media_node.current_version_id, media_node.metadata, media_node.shot_id
FROM reference_pack_item
JOIN media_node ON media_node.id = reference_pack_item.member_node_id
WHERE reference_pack_item.pack_node_id = $1
ORDER BY reference_pack_item.position, reference_pack_item.created_at
`

func (q *Queries) ListReferencePackItemNodes(ctx context.Context, packNodeID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listReferencePackItemNodes, packNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AssetID,
			&i.OperationType,
			&i.PromptTemplate,
			&i.PromptRich,
			&i.PromptRefs,
			&i.ModelProvider,
			&i.ModelID,
			&i.ModelParams,
			&i.CurrentVersionID,
			&i.Metadata,
			&i.ShotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencePackItems = `-- name: ListReferencePackItems :many
SELECT reference_pack_item.id, reference_pack_item.workspace_id, reference_pack_item.pack_node_id, reference_pack_item.member_node_id, reference_pack_item.position, reference_pack_item.metadata, reference_pack_item.created_at, reference_pack_item.updated_at
FROM reference_pack_item
WHERE pack_node_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListReferencePackItems(ctx context.Context, packNodeID pgtype.UUID) ([]ReferencePackItem, error) {
	rows, err := q.db.Query(ctx, listReferencePackItems, packNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferencePackItem{}
	for rows.Next() {
		var i ReferencePackItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PackNodeID,
			&i.MemberNodeID,
			&i.Position,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencePacksByMember = `-- name: ListReferencePacksByMember :many
SELECT media_node.id, media_node.workspace_id, media_node.node_type, media_node.title, media_node.status, media_node.prompt, media_node.source, media_node.canvas_x, media_node.canvas_y, media_node.canvas_w, media_node.canvas_h, media_node.created_at, media_node.updated_at, media_node.group_id, media_node.asset_id, media_node.operation_type, media_node.prompt_template, media_node.prompt_rich, media_node.prompt_refs, media_node.model_provider, media_node.model_id, media_node.model_params, media_node.current_version_id, media_node.metadata, media_node.shot_id
FROM reference_pack_item
JOIN media_node ON media_node.id = reference_pack_item.pack_node_id
WHERE reference_pack_item.member_node_id = $1
ORDER BY reference_pack_item.created_at
`

func (q *Queries) ListReferencePacksByMember(ctx context.Context, memberNodeID pgtype.UUID) ([]MediaNode, error) {
	rows, err := q.db.Query(ctx, listReferencePacksByMember, memberNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeType,
			&i.Title,
			&i.Status,
			&i.Prompt,
			&i.Source,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasW,
			&i.CanvasH,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AssetID,
			&i.OperationType,
			&i.PromptTemplate,
			&i.PromptRich,
			&i.PromptRefs,
			&i.ModelProvider,
			&i.ModelID,
			&i.ModelParams,
			&i.CurrentVersionID,
			&i.Metadata,
			&i.ShotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
