// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remotion_renderer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemotionRendererArtifact = `-- name: CreateRemotionRendererArtifact :one
INSERT INTO remotion_renderer_artifact (
    workspace_id,
    timeline_plan_id,
    status,
    route_policy,
    summary,
    created_by_role,
    created_by_task_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, workspace_id, timeline_plan_id, current_attempt_id, status, route_policy, summary, created_by_role, created_by_task_id, created_at, updated_at
`

type CreateRemotionRendererArtifactParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	TimelinePlanID  pgtype.UUID `json:"timeline_plan_id"`
	Status          string      `json:"status"`
	RoutePolicy     []byte      `json:"route_policy"`
	Summary         string      `json:"summary"`
	CreatedByRole   string      `json:"created_by_role"`
	CreatedByTaskID pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateRemotionRendererArtifact(ctx context.Context, arg CreateRemotionRendererArtifactParams) (RemotionRendererArtifact, error) {
	row := q.db.QueryRow(ctx, createRemotionRendererArtifact,
		arg.WorkspaceID,
		arg.TimelinePlanID,
		arg.Status,
		arg.RoutePolicy,
		arg.Summary,
		arg.CreatedByRole,
		arg.CreatedByTaskID,
	)
	var i RemotionRendererArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.CurrentAttemptID,
		&i.Status,
		&i.RoutePolicy,
		&i.Summary,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRemotionRendererAttempt = `-- name: CreateRemotionRendererAttempt :one
INSERT INTO remotion_renderer_attempt (
    workspace_id,
    timeline_plan_id,
    renderer_artifact_id,
    attempt_no,
    status,
    source_snapshot,
    props_json,
    source_hash,
    props_hash,
    workspace_dir,
    validation_result,
    compile_result,
    render_result,
    qa_result,
    repair_from_attempt_id,
    repair_notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at
`

type CreateRemotionRendererAttemptParams struct {
	WorkspaceID         pgtype.UUID `json:"workspace_id"`
	TimelinePlanID      pgtype.UUID `json:"timeline_plan_id"`
	RendererArtifactID  pgtype.UUID `json:"renderer_artifact_id"`
	AttemptNo           int32       `json:"attempt_no"`
	Status              string      `json:"status"`
	SourceSnapshot      []byte      `json:"source_snapshot"`
	PropsJson           []byte      `json:"props_json"`
	SourceHash          string      `json:"source_hash"`
	PropsHash           string      `json:"props_hash"`
	WorkspaceDir        string      `json:"workspace_dir"`
	ValidationResult    []byte      `json:"validation_result"`
	CompileResult       []byte      `json:"compile_result"`
	RenderResult        []byte      `json:"render_result"`
	QaResult            []byte      `json:"qa_result"`
	RepairFromAttemptID pgtype.UUID `json:"repair_from_attempt_id"`
	RepairNotes         string      `json:"repair_notes"`
}

func (q *Queries) CreateRemotionRendererAttempt(ctx context.Context, arg CreateRemotionRendererAttemptParams) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, createRemotionRendererAttempt,
		arg.WorkspaceID,
		arg.TimelinePlanID,
		arg.RendererArtifactID,
		arg.AttemptNo,
		arg.Status,
		arg.SourceSnapshot,
		arg.PropsJson,
		arg.SourceHash,
		arg.PropsHash,
		arg.WorkspaceDir,
		arg.ValidationResult,
		arg.CompileResult,
		arg.RenderResult,
		arg.QaResult,
		arg.RepairFromAttemptID,
		arg.RepairNotes,
	)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentRemotionRendererAttempt = `-- name: GetCurrentRemotionRendererAttempt :one
SELECT remotion_renderer_attempt.id, remotion_renderer_attempt.workspace_id, remotion_renderer_attempt.timeline_plan_id, remotion_renderer_attempt.renderer_artifact_id, remotion_renderer_attempt.attempt_no, remotion_renderer_attempt.status, remotion_renderer_attempt.source_snapshot, remotion_renderer_attempt.props_json, remotion_renderer_attempt.source_hash, remotion_renderer_attempt.props_hash, remotion_renderer_attempt.workspace_dir, remotion_renderer_attempt.validation_result, remotion_renderer_attempt.compile_result, remotion_renderer_attempt.render_result, remotion_renderer_attempt.qa_result, remotion_renderer_attempt.sandbox_job_id, remotion_renderer_attempt.repair_from_attempt_id, remotion_renderer_attempt.repair_notes, remotion_renderer_attempt.created_at, remotion_renderer_attempt.updated_at
FROM remotion_renderer_attempt
JOIN remotion_renderer_artifact
  ON remotion_renderer_artifact.current_attempt_id = remotion_renderer_attempt.id
WHERE remotion_renderer_artifact.id = $1
`

func (q *Queries) GetCurrentRemotionRendererAttempt(ctx context.Context, rendererArtifactID pgtype.UUID) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, getCurrentRemotionRendererAttempt, rendererArtifactID)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRemotionRendererAttemptByArtifact = `-- name: GetLatestRemotionRendererAttemptByArtifact :one
SELECT id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at FROM remotion_renderer_attempt
WHERE renderer_artifact_id = $1
ORDER BY attempt_no DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRemotionRendererAttemptByArtifact(ctx context.Context, rendererArtifactID pgtype.UUID) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestRemotionRendererAttemptByArtifact, rendererArtifactID)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemotionRendererArtifact = `-- name: GetRemotionRendererArtifact :one
SELECT id, workspace_id, timeline_plan_id, current_attempt_id, status, route_policy, summary, created_by_role, created_by_task_id, created_at, updated_at FROM remotion_renderer_artifact
WHERE id = $1
`

func (q *Queries) GetRemotionRendererArtifact(ctx context.Context, id pgtype.UUID) (RemotionRendererArtifact, error) {
	row := q.db.QueryRow(ctx, getRemotionRendererArtifact, id)
	var i RemotionRendererArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.CurrentAttemptID,
		&i.Status,
		&i.RoutePolicy,
		&i.Summary,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemotionRendererArtifactByTimelinePlan = `-- name: GetRemotionRendererArtifactByTimelinePlan :one
SELECT id, workspace_id, timeline_plan_id, current_attempt_id, status, route_policy, summary, created_by_role, created_by_task_id, created_at, updated_at FROM remotion_renderer_artifact
WHERE timeline_plan_id = $1
`

func (q *Queries) GetRemotionRendererArtifactByTimelinePlan(ctx context.Context, timelinePlanID pgtype.UUID) (RemotionRendererArtifact, error) {
	row := q.db.QueryRow(ctx, getRemotionRendererArtifactByTimelinePlan, timelinePlanID)
	var i RemotionRendererArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.CurrentAttemptID,
		&i.Status,
		&i.RoutePolicy,
		&i.Summary,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemotionRendererAttempt = `-- name: GetRemotionRendererAttempt :one
SELECT id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at FROM remotion_renderer_attempt
WHERE id = $1
`

func (q *Queries) GetRemotionRendererAttempt(ctx context.Context, id pgtype.UUID) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, getRemotionRendererAttempt, id)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRemotionRendererArtifactsByWorkspace = `-- name: ListRemotionRendererArtifactsByWorkspace :many
SELECT id, workspace_id, timeline_plan_id, current_attempt_id, status, route_policy, summary, created_by_role, created_by_task_id, created_at, updated_at FROM remotion_renderer_artifact
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRemotionRendererArtifactsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListRemotionRendererArtifactsByWorkspace(ctx context.Context, arg ListRemotionRendererArtifactsByWorkspaceParams) ([]RemotionRendererArtifact, error) {
	rows, err := q.db.Query(ctx, listRemotionRendererArtifactsByWorkspace, arg.WorkspaceID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemotionRendererArtifact{}
	for rows.Next() {
		var i RemotionRendererArtifact
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TimelinePlanID,
			&i.CurrentAttemptID,
			&i.Status,
			&i.RoutePolicy,
			&i.Summary,
			&i.CreatedByRole,
			&i.CreatedByTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemotionRendererAttemptsByArtifact = `-- name: ListRemotionRendererAttemptsByArtifact :many
SELECT id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at FROM remotion_renderer_attempt
WHERE renderer_artifact_id = $1
ORDER BY attempt_no ASC, created_at ASC
`

func (q *Queries) ListRemotionRendererAttemptsByArtifact(ctx context.Context, rendererArtifactID pgtype.UUID) ([]RemotionRendererAttempt, error) {
	rows, err := q.db.Query(ctx, listRemotionRendererAttemptsByArtifact, rendererArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemotionRendererAttempt{}
	for rows.Next() {
		var i RemotionRendererAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TimelinePlanID,
			&i.RendererArtifactID,
			&i.AttemptNo,
			&i.Status,
			&i.SourceSnapshot,
			&i.PropsJson,
			&i.SourceHash,
			&i.PropsHash,
			&i.WorkspaceDir,
			&i.ValidationResult,
			&i.CompileResult,
			&i.RenderResult,
			&i.QaResult,
			&i.SandboxJobID,
			&i.RepairFromAttemptID,
			&i.RepairNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentRemotionRendererAttempt = `-- name: SetCurrentRemotionRendererAttempt :one
UPDATE remotion_renderer_artifact
SET
    current_attempt_id = $1,
    status = $2,
    updated_at = now()
WHERE remotion_renderer_artifact.id = $3
  AND EXISTS (
    SELECT 1
    FROM remotion_renderer_attempt
    WHERE remotion_renderer_attempt.id = $1
      AND remotion_renderer_attempt.renderer_artifact_id = remotion_renderer_artifact.id
  )
RETURNING id, workspace_id, timeline_plan_id, current_attempt_id, status, route_policy, summary, created_by_role, created_by_task_id, created_at, updated_at
`

type SetCurrentRemotionRendererAttemptParams struct {
	CurrentAttemptID pgtype.UUID `json:"current_attempt_id"`
	Status           string      `json:"status"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) SetCurrentRemotionRendererAttempt(ctx context.Context, arg SetCurrentRemotionRendererAttemptParams) (RemotionRendererArtifact, error) {
	row := q.db.QueryRow(ctx, setCurrentRemotionRendererAttempt, arg.CurrentAttemptID, arg.Status, arg.ID)
	var i RemotionRendererArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.CurrentAttemptID,
		&i.Status,
		&i.RoutePolicy,
		&i.Summary,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRemotionRendererArtifactStatus = `-- name: UpdateRemotionRendererArtifactStatus :one
UPDATE remotion_renderer_artifact
SET
    status = $1,
    route_policy = COALESCE($2, route_policy),
    summary = COALESCE($3, summary),
    updated_at = now()
WHERE id = $4
RETURNING id, workspace_id, timeline_plan_id, current_attempt_id, status, route_policy, summary, created_by_role, created_by_task_id, created_at, updated_at
`

type UpdateRemotionRendererArtifactStatusParams struct {
	Status      string      `json:"status"`
	RoutePolicy []byte      `json:"route_policy"`
	Summary     pgtype.Text `json:"summary"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRemotionRendererArtifactStatus(ctx context.Context, arg UpdateRemotionRendererArtifactStatusParams) (RemotionRendererArtifact, error) {
	row := q.db.QueryRow(ctx, updateRemotionRendererArtifactStatus,
		arg.Status,
		arg.RoutePolicy,
		arg.Summary,
		arg.ID,
	)
	var i RemotionRendererArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.CurrentAttemptID,
		&i.Status,
		&i.RoutePolicy,
		&i.Summary,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRemotionRendererAttemptQAResult = `-- name: UpdateRemotionRendererAttemptQAResult :one
UPDATE remotion_renderer_attempt
SET
    status = $1,
    qa_result = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at
`

type UpdateRemotionRendererAttemptQAResultParams struct {
	Status   string      `json:"status"`
	QaResult []byte      `json:"qa_result"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRemotionRendererAttemptQAResult(ctx context.Context, arg UpdateRemotionRendererAttemptQAResultParams) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, updateRemotionRendererAttemptQAResult, arg.Status, arg.QaResult, arg.ID)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRemotionRendererAttemptRenderResult = `-- name: UpdateRemotionRendererAttemptRenderResult :one
UPDATE remotion_renderer_attempt
SET
    status = $1,
    render_result = $2,
    sandbox_job_id = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at
`

type UpdateRemotionRendererAttemptRenderResultParams struct {
	Status       string      `json:"status"`
	RenderResult []byte      `json:"render_result"`
	SandboxJobID pgtype.UUID `json:"sandbox_job_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRemotionRendererAttemptRenderResult(ctx context.Context, arg UpdateRemotionRendererAttemptRenderResultParams) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, updateRemotionRendererAttemptRenderResult,
		arg.Status,
		arg.RenderResult,
		arg.SandboxJobID,
		arg.ID,
	)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRemotionRendererAttemptSnapshot = `-- name: UpdateRemotionRendererAttemptSnapshot :one
UPDATE remotion_renderer_attempt
SET
    status = $1,
    source_snapshot = $2,
    props_json = $3,
    source_hash = $4,
    props_hash = $5,
    workspace_dir = $6,
    validation_result = $7,
    compile_result = $8,
    updated_at = now()
WHERE id = $9
RETURNING id, workspace_id, timeline_plan_id, renderer_artifact_id, attempt_no, status, source_snapshot, props_json, source_hash, props_hash, workspace_dir, validation_result, compile_result, render_result, qa_result, sandbox_job_id, repair_from_attempt_id, repair_notes, created_at, updated_at
`

type UpdateRemotionRendererAttemptSnapshotParams struct {
	Status           string      `json:"status"`
	SourceSnapshot   []byte      `json:"source_snapshot"`
	PropsJson        []byte      `json:"props_json"`
	SourceHash       string      `json:"source_hash"`
	PropsHash        string      `json:"props_hash"`
	WorkspaceDir     string      `json:"workspace_dir"`
	ValidationResult []byte      `json:"validation_result"`
	CompileResult    []byte      `json:"compile_result"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRemotionRendererAttemptSnapshot(ctx context.Context, arg UpdateRemotionRendererAttemptSnapshotParams) (RemotionRendererAttempt, error) {
	row := q.db.QueryRow(ctx, updateRemotionRendererAttemptSnapshot,
		arg.Status,
		arg.SourceSnapshot,
		arg.PropsJson,
		arg.SourceHash,
		arg.PropsHash,
		arg.WorkspaceDir,
		arg.ValidationResult,
		arg.CompileResult,
		arg.ID,
	)
	var i RemotionRendererAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TimelinePlanID,
		&i.RendererArtifactID,
		&i.AttemptNo,
		&i.Status,
		&i.SourceSnapshot,
		&i.PropsJson,
		&i.SourceHash,
		&i.PropsHash,
		&i.WorkspaceDir,
		&i.ValidationResult,
		&i.CompileResult,
		&i.RenderResult,
		&i.QaResult,
		&i.SandboxJobID,
		&i.RepairFromAttemptID,
		&i.RepairNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
