// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: render_plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveRenderPlansBySemanticKey = `-- name: ArchiveRenderPlansBySemanticKey :exec
UPDATE render_plan
SET archived_at = now(),
    updated_at = now()
WHERE workspace_id = $1
  AND semantic_key = $2
  AND archived_at IS NULL
`

type ArchiveRenderPlansBySemanticKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SemanticKey string      `json:"semantic_key"`
}

func (q *Queries) ArchiveRenderPlansBySemanticKey(ctx context.Context, arg ArchiveRenderPlansBySemanticKeyParams) error {
	_, err := q.db.Exec(ctx, archiveRenderPlansBySemanticKey, arg.WorkspaceID, arg.SemanticKey)
	return err
}

const createRenderPlan = `-- name: CreateRenderPlan :one
INSERT INTO render_plan (
    workspace_id, scope_type, scope_id, target_phase, task_type,
    model_prompt_profile, operation, status, revision, forked_from_render_plan_id,
    render_plan_key, reference_bindings, subject_bindings, prompt_parts, params,
    audit_hints, blocker, rationale, created_by_thread_id, created_by_task_id,
    semantic_key, display_name
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22
) RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type CreateRenderPlanParams struct {
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	ScopeType              string      `json:"scope_type"`
	ScopeID                pgtype.UUID `json:"scope_id"`
	TargetPhase            string      `json:"target_phase"`
	TaskType               string      `json:"task_type"`
	ModelPromptProfile     string      `json:"model_prompt_profile"`
	Operation              string      `json:"operation"`
	Status                 string      `json:"status"`
	Revision               int32       `json:"revision"`
	ForkedFromRenderPlanID pgtype.UUID `json:"forked_from_render_plan_id"`
	RenderPlanKey          string      `json:"render_plan_key"`
	ReferenceBindings      []byte      `json:"reference_bindings"`
	SubjectBindings        []byte      `json:"subject_bindings"`
	PromptParts            []byte      `json:"prompt_parts"`
	Params                 []byte      `json:"params"`
	AuditHints             []byte      `json:"audit_hints"`
	Blocker                []byte      `json:"blocker"`
	Rationale              string      `json:"rationale"`
	CreatedByThreadID      pgtype.UUID `json:"created_by_thread_id"`
	CreatedByTaskID        pgtype.UUID `json:"created_by_task_id"`
	SemanticKey            string      `json:"semantic_key"`
	DisplayName            string      `json:"display_name"`
}

func (q *Queries) CreateRenderPlan(ctx context.Context, arg CreateRenderPlanParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, createRenderPlan,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.TargetPhase,
		arg.TaskType,
		arg.ModelPromptProfile,
		arg.Operation,
		arg.Status,
		arg.Revision,
		arg.ForkedFromRenderPlanID,
		arg.RenderPlanKey,
		arg.ReferenceBindings,
		arg.SubjectBindings,
		arg.PromptParts,
		arg.Params,
		arg.AuditHints,
		arg.Blocker,
		arg.Rationale,
		arg.CreatedByThreadID,
		arg.CreatedByTaskID,
		arg.SemanticKey,
		arg.DisplayName,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getLatestRenderPlanByScopePhase = `-- name: GetLatestRenderPlanByScopePhase :one
SELECT id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name FROM render_plan
WHERE workspace_id = $1
  AND scope_type = $2
  AND scope_id = $3
  AND target_phase = $4
  AND archived_at IS NULL
ORDER BY revision DESC
LIMIT 1
`

type GetLatestRenderPlanByScopePhaseParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     pgtype.UUID `json:"scope_id"`
	TargetPhase string      `json:"target_phase"`
}

func (q *Queries) GetLatestRenderPlanByScopePhase(ctx context.Context, arg GetLatestRenderPlanByScopePhaseParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, getLatestRenderPlanByScopePhase,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.TargetPhase,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getLatestRenderPlanByTaskScopePhase = `-- name: GetLatestRenderPlanByTaskScopePhase :one
SELECT id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name FROM render_plan
WHERE workspace_id = $1
  AND scope_type = $2
  AND scope_id = $3
  AND target_phase = $4
  AND created_by_task_id = $5
  AND archived_at IS NULL
ORDER BY revision DESC, updated_at DESC
LIMIT 1
`

type GetLatestRenderPlanByTaskScopePhaseParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ScopeType       string      `json:"scope_type"`
	ScopeID         pgtype.UUID `json:"scope_id"`
	TargetPhase     string      `json:"target_phase"`
	CreatedByTaskID pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) GetLatestRenderPlanByTaskScopePhase(ctx context.Context, arg GetLatestRenderPlanByTaskScopePhaseParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, getLatestRenderPlanByTaskScopePhase,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.TargetPhase,
		arg.CreatedByTaskID,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const getRenderPlanByID = `-- name: GetRenderPlanByID :one
SELECT id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name FROM render_plan
WHERE id = $1 AND workspace_id = $2 AND archived_at IS NULL
`

type GetRenderPlanByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetRenderPlanByID(ctx context.Context, arg GetRenderPlanByIDParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, getRenderPlanByID, arg.ID, arg.WorkspaceID)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const listRenderPlansByScope = `-- name: ListRenderPlansByScope :many
SELECT id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name FROM render_plan
WHERE workspace_id = $1
  AND scope_type = $2
  AND scope_id = $3
  AND archived_at IS NULL
ORDER BY target_phase ASC, revision DESC
`

type ListRenderPlansByScopeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     pgtype.UUID `json:"scope_id"`
}

func (q *Queries) ListRenderPlansByScope(ctx context.Context, arg ListRenderPlansByScopeParams) ([]RenderPlan, error) {
	rows, err := q.db.Query(ctx, listRenderPlansByScope, arg.WorkspaceID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenderPlan{}
	for rows.Next() {
		var i RenderPlan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.ScopeID,
			&i.TargetPhase,
			&i.TaskType,
			&i.ModelPromptProfile,
			&i.Operation,
			&i.Status,
			&i.Revision,
			&i.ForkedFromRenderPlanID,
			&i.RenderPlanKey,
			&i.ReferenceBindings,
			&i.SubjectBindings,
			&i.PromptParts,
			&i.Params,
			&i.AuditHints,
			&i.Blocker,
			&i.CompiledPrompt,
			&i.CompiledRequest,
			&i.PromptAudit,
			&i.CostEstimate,
			&i.Rationale,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.SubmittedWorkerTaskID,
			&i.OutputNodeID,
			&i.OutputVersionID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompiledAt,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenderPlansByWorkspace = `-- name: ListRenderPlansByWorkspace :many
SELECT id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name FROM render_plan
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListRenderPlansByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]RenderPlan, error) {
	rows, err := q.db.Query(ctx, listRenderPlansByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenderPlan{}
	for rows.Next() {
		var i RenderPlan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.ScopeID,
			&i.TargetPhase,
			&i.TaskType,
			&i.ModelPromptProfile,
			&i.Operation,
			&i.Status,
			&i.Revision,
			&i.ForkedFromRenderPlanID,
			&i.RenderPlanKey,
			&i.ReferenceBindings,
			&i.SubjectBindings,
			&i.PromptParts,
			&i.Params,
			&i.AuditHints,
			&i.Blocker,
			&i.CompiledPrompt,
			&i.CompiledRequest,
			&i.PromptAudit,
			&i.CostEstimate,
			&i.Rationale,
			&i.CreatedByThreadID,
			&i.CreatedByTaskID,
			&i.SubmittedWorkerTaskID,
			&i.OutputNodeID,
			&i.OutputVersionID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompiledAt,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRenderPlanBlocked = `-- name: MarkRenderPlanBlocked :one
UPDATE render_plan
SET status = 'blocked',
    blocker = $3,
    audit_hints = $4,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('draft', 'blocked')
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkRenderPlanBlockedParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Blocker     []byte      `json:"blocker"`
	AuditHints  []byte      `json:"audit_hints"`
}

func (q *Queries) MarkRenderPlanBlocked(ctx context.Context, arg MarkRenderPlanBlockedParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markRenderPlanBlocked,
		arg.ID,
		arg.WorkspaceID,
		arg.Blocker,
		arg.AuditHints,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markRenderPlanCompiled = `-- name: MarkRenderPlanCompiled :one
UPDATE render_plan
SET status = 'compiled',
    compiled_prompt = $3,
    compiled_request = $4,
    prompt_audit = $5,
    cost_estimate = $6,
    compiled_at = now(),
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status = 'draft'
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkRenderPlanCompiledParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	CompiledPrompt  string      `json:"compiled_prompt"`
	CompiledRequest []byte      `json:"compiled_request"`
	PromptAudit     []byte      `json:"prompt_audit"`
	CostEstimate    []byte      `json:"cost_estimate"`
}

func (q *Queries) MarkRenderPlanCompiled(ctx context.Context, arg MarkRenderPlanCompiledParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markRenderPlanCompiled,
		arg.ID,
		arg.WorkspaceID,
		arg.CompiledPrompt,
		arg.CompiledRequest,
		arg.PromptAudit,
		arg.CostEstimate,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markRenderPlanCompleted = `-- name: MarkRenderPlanCompleted :one
UPDATE render_plan
SET status = $3,
    output_version_id = $4,
    output_node_id = $5,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('submitted', 'running')
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkRenderPlanCompletedParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	Status          string      `json:"status"`
	OutputVersionID pgtype.UUID `json:"output_version_id"`
	OutputNodeID    pgtype.UUID `json:"output_node_id"`
}

func (q *Queries) MarkRenderPlanCompleted(ctx context.Context, arg MarkRenderPlanCompletedParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markRenderPlanCompleted,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.OutputVersionID,
		arg.OutputNodeID,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markRenderPlanRejected = `-- name: MarkRenderPlanRejected :one
UPDATE render_plan
SET status = 'rejected',
    blocker = $3,
    audit_hints = $4,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('compiled', 'waiting_for_approval')
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkRenderPlanRejectedParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Blocker     []byte      `json:"blocker"`
	AuditHints  []byte      `json:"audit_hints"`
}

func (q *Queries) MarkRenderPlanRejected(ctx context.Context, arg MarkRenderPlanRejectedParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markRenderPlanRejected,
		arg.ID,
		arg.WorkspaceID,
		arg.Blocker,
		arg.AuditHints,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markRenderPlanSubmitted = `-- name: MarkRenderPlanSubmitted :one
UPDATE render_plan
SET status = 'submitted',
    submitted_worker_task_id = $3,
    output_node_id = $4,
    submitted_at = now(),
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('compiled', 'waiting_for_approval', 'submitted')
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkRenderPlanSubmittedParams struct {
	ID                    pgtype.UUID `json:"id"`
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	SubmittedWorkerTaskID pgtype.UUID `json:"submitted_worker_task_id"`
	OutputNodeID          pgtype.UUID `json:"output_node_id"`
}

func (q *Queries) MarkRenderPlanSubmitted(ctx context.Context, arg MarkRenderPlanSubmittedParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markRenderPlanSubmitted,
		arg.ID,
		arg.WorkspaceID,
		arg.SubmittedWorkerTaskID,
		arg.OutputNodeID,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markRenderPlanWaitingForApproval = `-- name: MarkRenderPlanWaitingForApproval :one
UPDATE render_plan
SET status = 'waiting_for_approval',
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status = 'compiled'
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkRenderPlanWaitingForApprovalParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) MarkRenderPlanWaitingForApproval(ctx context.Context, arg MarkRenderPlanWaitingForApprovalParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markRenderPlanWaitingForApproval, arg.ID, arg.WorkspaceID)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const markSubmittedRenderPlanCompletedByWorkerTask = `-- name: MarkSubmittedRenderPlanCompletedByWorkerTask :one
UPDATE render_plan
SET status = $3,
    output_version_id = $4,
    output_node_id = $5,
    blocker = CASE
      WHEN $3 = 'failed' AND $6::jsonb IS NOT NULL THEN $6::jsonb
      ELSE blocker
    END,
    completed_at = now(),
    updated_at = now()
WHERE workspace_id = $1
  AND submitted_worker_task_id = $2
  AND status IN ('submitted', 'running')
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type MarkSubmittedRenderPlanCompletedByWorkerTaskParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	SubmittedWorkerTaskID pgtype.UUID `json:"submitted_worker_task_id"`
	Status                string      `json:"status"`
	OutputVersionID       pgtype.UUID `json:"output_version_id"`
	OutputNodeID          pgtype.UUID `json:"output_node_id"`
	FailureBlocker        []byte      `json:"failure_blocker"`
}

func (q *Queries) MarkSubmittedRenderPlanCompletedByWorkerTask(ctx context.Context, arg MarkSubmittedRenderPlanCompletedByWorkerTaskParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, markSubmittedRenderPlanCompletedByWorkerTask,
		arg.WorkspaceID,
		arg.SubmittedWorkerTaskID,
		arg.Status,
		arg.OutputVersionID,
		arg.OutputNodeID,
		arg.FailureBlocker,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const nextRenderPlanRevision = `-- name: NextRenderPlanRevision :one
SELECT COALESCE(MAX(revision), 0)::int + 1 AS next_revision
FROM render_plan
WHERE workspace_id = $1
  AND scope_type = $2
  AND scope_id = $3
  AND target_phase = $4
  AND archived_at IS NULL
`

type NextRenderPlanRevisionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     pgtype.UUID `json:"scope_id"`
	TargetPhase string      `json:"target_phase"`
}

func (q *Queries) NextRenderPlanRevision(ctx context.Context, arg NextRenderPlanRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextRenderPlanRevision,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.TargetPhase,
	)
	var next_revision int32
	err := row.Scan(&next_revision)
	return next_revision, err
}

const updateRenderPlanDraft = `-- name: UpdateRenderPlanDraft :one
UPDATE render_plan
SET task_type = $3,
    model_prompt_profile = $4,
    operation = $5,
    reference_bindings = $6,
    subject_bindings = $7,
    prompt_parts = $8,
    params = $9,
    audit_hints = $10,
    blocker = $11,
    rationale = $12,
    status = $13,
    updated_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status IN ('draft', 'blocked')
  AND archived_at IS NULL
RETURNING id, workspace_id, scope_type, scope_id, target_phase, task_type, model_prompt_profile, operation, status, revision, forked_from_render_plan_id, render_plan_key, reference_bindings, subject_bindings, prompt_parts, params, audit_hints, blocker, compiled_prompt, compiled_request, prompt_audit, cost_estimate, rationale, created_by_thread_id, created_by_task_id, submitted_worker_task_id, output_node_id, output_version_id, archived_at, created_at, updated_at, compiled_at, submitted_at, completed_at, semantic_key, display_name
`

type UpdateRenderPlanDraftParams struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	TaskType           string      `json:"task_type"`
	ModelPromptProfile string      `json:"model_prompt_profile"`
	Operation          string      `json:"operation"`
	ReferenceBindings  []byte      `json:"reference_bindings"`
	SubjectBindings    []byte      `json:"subject_bindings"`
	PromptParts        []byte      `json:"prompt_parts"`
	Params             []byte      `json:"params"`
	AuditHints         []byte      `json:"audit_hints"`
	Blocker            []byte      `json:"blocker"`
	Rationale          string      `json:"rationale"`
	Status             string      `json:"status"`
}

func (q *Queries) UpdateRenderPlanDraft(ctx context.Context, arg UpdateRenderPlanDraftParams) (RenderPlan, error) {
	row := q.db.QueryRow(ctx, updateRenderPlanDraft,
		arg.ID,
		arg.WorkspaceID,
		arg.TaskType,
		arg.ModelPromptProfile,
		arg.Operation,
		arg.ReferenceBindings,
		arg.SubjectBindings,
		arg.PromptParts,
		arg.Params,
		arg.AuditHints,
		arg.Blocker,
		arg.Rationale,
		arg.Status,
	)
	var i RenderPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.TargetPhase,
		&i.TaskType,
		&i.ModelPromptProfile,
		&i.Operation,
		&i.Status,
		&i.Revision,
		&i.ForkedFromRenderPlanID,
		&i.RenderPlanKey,
		&i.ReferenceBindings,
		&i.SubjectBindings,
		&i.PromptParts,
		&i.Params,
		&i.AuditHints,
		&i.Blocker,
		&i.CompiledPrompt,
		&i.CompiledRequest,
		&i.PromptAudit,
		&i.CostEstimate,
		&i.Rationale,
		&i.CreatedByThreadID,
		&i.CreatedByTaskID,
		&i.SubmittedWorkerTaskID,
		&i.OutputNodeID,
		&i.OutputVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompiledAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}
