// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_record.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeReviewRecord = `-- name: CompleteReviewRecord :one
UPDATE review_record
SET status = $2,
    overall_score = $3,
    rubric = $4,
    critique = $5,
    retry_recommendation = $6,
    escalation = $7,
    error_code = '',
    error_message = '',
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
`

type CompleteReviewRecordParams struct {
	ID                  pgtype.UUID   `json:"id"`
	Status              string        `json:"status"`
	OverallScore        pgtype.Float4 `json:"overall_score"`
	Rubric              []byte        `json:"rubric"`
	Critique            string        `json:"critique"`
	RetryRecommendation []byte        `json:"retry_recommendation"`
	Escalation          []byte        `json:"escalation"`
}

func (q *Queries) CompleteReviewRecord(ctx context.Context, arg CompleteReviewRecordParams) (ReviewRecord, error) {
	row := q.db.QueryRow(ctx, completeReviewRecord,
		arg.ID,
		arg.Status,
		arg.OverallScore,
		arg.Rubric,
		arg.Critique,
		arg.RetryRecommendation,
		arg.Escalation,
	)
	var i ReviewRecord
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShotID,
		&i.NodeID,
		&i.ArtifactVersionID,
		&i.GenerationJobID,
		&i.ReviewerThreadID,
		&i.ReviewerTaskID,
		&i.ParentReviewRecordID,
		&i.TargetPhase,
		&i.Status,
		&i.AttemptNo,
		&i.MaxAttempts,
		&i.OverallScore,
		&i.Rubric,
		&i.Critique,
		&i.RetryRecommendation,
		&i.ModelProvider,
		&i.ModelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ReviewTask,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.RenderPlanID,
		&i.RequiredAxes,
		&i.Escalation,
	)
	return i, err
}

const countReviewAttemptsByShotPhase = `-- name: CountReviewAttemptsByShotPhase :one
SELECT COUNT(*)::int
FROM review_record
WHERE workspace_id = $1
  AND shot_id = $2
  AND target_phase = $3
  AND status IN ('accepted', 'rejected', 'failed')
`

type CountReviewAttemptsByShotPhaseParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ShotID      pgtype.UUID `json:"shot_id"`
	TargetPhase string      `json:"target_phase"`
}

func (q *Queries) CountReviewAttemptsByShotPhase(ctx context.Context, arg CountReviewAttemptsByShotPhaseParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReviewAttemptsByShotPhase, arg.WorkspaceID, arg.ShotID, arg.TargetPhase)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createReviewRecord = `-- name: CreateReviewRecord :one
INSERT INTO review_record (
    workspace_id,
    shot_id,
    node_id,
    artifact_version_id,
    generation_job_id,
    reviewer_thread_id,
    reviewer_task_id,
    parent_review_record_id,
    target_phase,
    review_task,
    target_object_type,
    target_object_id,
    render_plan_id,
    status,
    attempt_no,
    max_attempts,
    model_provider,
    model_id,
    required_axes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13,
    'running', $14, $15, $16, $17, $18
) RETURNING id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
`

type CreateReviewRecordParams struct {
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	ShotID               pgtype.UUID `json:"shot_id"`
	NodeID               pgtype.UUID `json:"node_id"`
	ArtifactVersionID    pgtype.UUID `json:"artifact_version_id"`
	GenerationJobID      pgtype.UUID `json:"generation_job_id"`
	ReviewerThreadID     pgtype.UUID `json:"reviewer_thread_id"`
	ReviewerTaskID       pgtype.UUID `json:"reviewer_task_id"`
	ParentReviewRecordID pgtype.UUID `json:"parent_review_record_id"`
	TargetPhase          string      `json:"target_phase"`
	ReviewTask           string      `json:"review_task"`
	TargetObjectType     string      `json:"target_object_type"`
	TargetObjectID       pgtype.UUID `json:"target_object_id"`
	RenderPlanID         pgtype.UUID `json:"render_plan_id"`
	AttemptNo            int32       `json:"attempt_no"`
	MaxAttempts          int32       `json:"max_attempts"`
	ModelProvider        string      `json:"model_provider"`
	ModelID              string      `json:"model_id"`
	RequiredAxes         []byte      `json:"required_axes"`
}

func (q *Queries) CreateReviewRecord(ctx context.Context, arg CreateReviewRecordParams) (ReviewRecord, error) {
	row := q.db.QueryRow(ctx, createReviewRecord,
		arg.WorkspaceID,
		arg.ShotID,
		arg.NodeID,
		arg.ArtifactVersionID,
		arg.GenerationJobID,
		arg.ReviewerThreadID,
		arg.ReviewerTaskID,
		arg.ParentReviewRecordID,
		arg.TargetPhase,
		arg.ReviewTask,
		arg.TargetObjectType,
		arg.TargetObjectID,
		arg.RenderPlanID,
		arg.AttemptNo,
		arg.MaxAttempts,
		arg.ModelProvider,
		arg.ModelID,
		arg.RequiredAxes,
	)
	var i ReviewRecord
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShotID,
		&i.NodeID,
		&i.ArtifactVersionID,
		&i.GenerationJobID,
		&i.ReviewerThreadID,
		&i.ReviewerTaskID,
		&i.ParentReviewRecordID,
		&i.TargetPhase,
		&i.Status,
		&i.AttemptNo,
		&i.MaxAttempts,
		&i.OverallScore,
		&i.Rubric,
		&i.Critique,
		&i.RetryRecommendation,
		&i.ModelProvider,
		&i.ModelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ReviewTask,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.RenderPlanID,
		&i.RequiredAxes,
		&i.Escalation,
	)
	return i, err
}

const failReviewRecord = `-- name: FailReviewRecord :one
UPDATE review_record
SET status = 'failed',
    error_code = $2,
    error_message = $3,
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
`

type FailReviewRecordParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorCode    string      `json:"error_code"`
	ErrorMessage string      `json:"error_message"`
}

func (q *Queries) FailReviewRecord(ctx context.Context, arg FailReviewRecordParams) (ReviewRecord, error) {
	row := q.db.QueryRow(ctx, failReviewRecord, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	var i ReviewRecord
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShotID,
		&i.NodeID,
		&i.ArtifactVersionID,
		&i.GenerationJobID,
		&i.ReviewerThreadID,
		&i.ReviewerTaskID,
		&i.ParentReviewRecordID,
		&i.TargetPhase,
		&i.Status,
		&i.AttemptNo,
		&i.MaxAttempts,
		&i.OverallScore,
		&i.Rubric,
		&i.Critique,
		&i.RetryRecommendation,
		&i.ModelProvider,
		&i.ModelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ReviewTask,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.RenderPlanID,
		&i.RequiredAxes,
		&i.Escalation,
	)
	return i, err
}

const getReviewRecordByID = `-- name: GetReviewRecordByID :one
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE id = $1
`

func (q *Queries) GetReviewRecordByID(ctx context.Context, id pgtype.UUID) (ReviewRecord, error) {
	row := q.db.QueryRow(ctx, getReviewRecordByID, id)
	var i ReviewRecord
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShotID,
		&i.NodeID,
		&i.ArtifactVersionID,
		&i.GenerationJobID,
		&i.ReviewerThreadID,
		&i.ReviewerTaskID,
		&i.ParentReviewRecordID,
		&i.TargetPhase,
		&i.Status,
		&i.AttemptNo,
		&i.MaxAttempts,
		&i.OverallScore,
		&i.Rubric,
		&i.Critique,
		&i.RetryRecommendation,
		&i.ModelProvider,
		&i.ModelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ReviewTask,
		&i.TargetObjectType,
		&i.TargetObjectID,
		&i.RenderPlanID,
		&i.RequiredAxes,
		&i.Escalation,
	)
	return i, err
}

const listReviewRecordsByArtifactVersion = `-- name: ListReviewRecordsByArtifactVersion :many
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE artifact_version_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewRecordsByArtifactVersion(ctx context.Context, artifactVersionID pgtype.UUID) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByArtifactVersion, artifactVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.NodeID,
			&i.ArtifactVersionID,
			&i.GenerationJobID,
			&i.ReviewerThreadID,
			&i.ReviewerTaskID,
			&i.ParentReviewRecordID,
			&i.TargetPhase,
			&i.Status,
			&i.AttemptNo,
			&i.MaxAttempts,
			&i.OverallScore,
			&i.Rubric,
			&i.Critique,
			&i.RetryRecommendation,
			&i.ModelProvider,
			&i.ModelID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ReviewTask,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.RenderPlanID,
			&i.RequiredAxes,
			&i.Escalation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRecordsByNode = `-- name: ListReviewRecordsByNode :many
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE node_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewRecordsByNode(ctx context.Context, nodeID pgtype.UUID) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.NodeID,
			&i.ArtifactVersionID,
			&i.GenerationJobID,
			&i.ReviewerThreadID,
			&i.ReviewerTaskID,
			&i.ParentReviewRecordID,
			&i.TargetPhase,
			&i.Status,
			&i.AttemptNo,
			&i.MaxAttempts,
			&i.OverallScore,
			&i.Rubric,
			&i.Critique,
			&i.RetryRecommendation,
			&i.ModelProvider,
			&i.ModelID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ReviewTask,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.RenderPlanID,
			&i.RequiredAxes,
			&i.Escalation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRecordsByRenderPlan = `-- name: ListReviewRecordsByRenderPlan :many
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE render_plan_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewRecordsByRenderPlan(ctx context.Context, renderPlanID pgtype.UUID) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByRenderPlan, renderPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.NodeID,
			&i.ArtifactVersionID,
			&i.GenerationJobID,
			&i.ReviewerThreadID,
			&i.ReviewerTaskID,
			&i.ParentReviewRecordID,
			&i.TargetPhase,
			&i.Status,
			&i.AttemptNo,
			&i.MaxAttempts,
			&i.OverallScore,
			&i.Rubric,
			&i.Critique,
			&i.RetryRecommendation,
			&i.ModelProvider,
			&i.ModelID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ReviewTask,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.RenderPlanID,
			&i.RequiredAxes,
			&i.Escalation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRecordsByShotPhase = `-- name: ListReviewRecordsByShotPhase :many
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE workspace_id = $1
  AND shot_id = $2
  AND target_phase = $3
ORDER BY created_at DESC
`

type ListReviewRecordsByShotPhaseParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ShotID      pgtype.UUID `json:"shot_id"`
	TargetPhase string      `json:"target_phase"`
}

func (q *Queries) ListReviewRecordsByShotPhase(ctx context.Context, arg ListReviewRecordsByShotPhaseParams) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByShotPhase, arg.WorkspaceID, arg.ShotID, arg.TargetPhase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.NodeID,
			&i.ArtifactVersionID,
			&i.GenerationJobID,
			&i.ReviewerThreadID,
			&i.ReviewerTaskID,
			&i.ParentReviewRecordID,
			&i.TargetPhase,
			&i.Status,
			&i.AttemptNo,
			&i.MaxAttempts,
			&i.OverallScore,
			&i.Rubric,
			&i.Critique,
			&i.RetryRecommendation,
			&i.ModelProvider,
			&i.ModelID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ReviewTask,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.RenderPlanID,
			&i.RequiredAxes,
			&i.Escalation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRecordsByTarget = `-- name: ListReviewRecordsByTarget :many
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE workspace_id = $1
  AND target_object_type = $2
  AND target_object_id = $3
ORDER BY created_at DESC
LIMIT $4
`

type ListReviewRecordsByTargetParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	TargetObjectType string      `json:"target_object_type"`
	TargetObjectID   pgtype.UUID `json:"target_object_id"`
	Limit            int32       `json:"limit"`
}

func (q *Queries) ListReviewRecordsByTarget(ctx context.Context, arg ListReviewRecordsByTargetParams) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByTarget,
		arg.WorkspaceID,
		arg.TargetObjectType,
		arg.TargetObjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.NodeID,
			&i.ArtifactVersionID,
			&i.GenerationJobID,
			&i.ReviewerThreadID,
			&i.ReviewerTaskID,
			&i.ParentReviewRecordID,
			&i.TargetPhase,
			&i.Status,
			&i.AttemptNo,
			&i.MaxAttempts,
			&i.OverallScore,
			&i.Rubric,
			&i.Critique,
			&i.RetryRecommendation,
			&i.ModelProvider,
			&i.ModelID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ReviewTask,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.RenderPlanID,
			&i.RequiredAxes,
			&i.Escalation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRecordsByWorkspace = `-- name: ListReviewRecordsByWorkspace :many
SELECT id, workspace_id, shot_id, node_id, artifact_version_id, generation_job_id, reviewer_thread_id, reviewer_task_id, parent_review_record_id, target_phase, status, attempt_no, max_attempts, overall_score, rubric, critique, retry_recommendation, model_provider, model_id, error_code, error_message, created_at, completed_at, review_task, target_object_type, target_object_id, render_plan_id, required_axes, escalation
FROM review_record
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReviewRecordsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListReviewRecordsByWorkspace(ctx context.Context, arg ListReviewRecordsByWorkspaceParams) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShotID,
			&i.NodeID,
			&i.ArtifactVersionID,
			&i.GenerationJobID,
			&i.ReviewerThreadID,
			&i.ReviewerTaskID,
			&i.ParentReviewRecordID,
			&i.TargetPhase,
			&i.Status,
			&i.AttemptNo,
			&i.MaxAttempts,
			&i.OverallScore,
			&i.Rubric,
			&i.Critique,
			&i.RetryRecommendation,
			&i.ModelProvider,
			&i.ModelID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ReviewTask,
			&i.TargetObjectType,
			&i.TargetObjectID,
			&i.RenderPlanID,
			&i.RequiredAxes,
			&i.Escalation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
