// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceSandboxBinding = `-- name: CreateWorkspaceSandboxBinding :one
INSERT INTO workspace_sandbox (
    workspace_id,
    volume_name,
    status
) VALUES (
    $1, $2, $3
)
ON CONFLICT (workspace_id) DO UPDATE
SET updated_at = workspace_sandbox.updated_at
RETURNING workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
`

type CreateWorkspaceSandboxBindingParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	VolumeName  string      `json:"volume_name"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateWorkspaceSandboxBinding(ctx context.Context, arg CreateWorkspaceSandboxBindingParams) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, createWorkspaceSandboxBinding, arg.WorkspaceID, arg.VolumeName, arg.Status)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceSandboxBinding = `-- name: GetWorkspaceSandboxBinding :one
SELECT workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
FROM workspace_sandbox
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceSandboxBinding(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSandboxBinding, workspaceID)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWorkspaceSandboxBinding = `-- name: LockWorkspaceSandboxBinding :one
SELECT workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
FROM workspace_sandbox
WHERE workspace_id = $1
FOR UPDATE
`

func (q *Queries) LockWorkspaceSandboxBinding(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceSandboxBinding, workspaceID)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceSandboxCreating = `-- name: MarkWorkspaceSandboxCreating :one
UPDATE workspace_sandbox
SET status = 'creating',
    error_message = NULL,
    updated_at = now()
WHERE workspace_id = $1
RETURNING workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
`

func (q *Queries) MarkWorkspaceSandboxCreating(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, markWorkspaceSandboxCreating, workspaceID)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceSandboxRunning = `-- name: MarkWorkspaceSandboxRunning :one
UPDATE workspace_sandbox
SET sandbox_id = $2,
    status = 'running',
    last_health_check_at = now(),
    last_seen_at = now(),
    error_message = NULL,
    updated_at = now()
WHERE workspace_id = $1
RETURNING workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
`

type MarkWorkspaceSandboxRunningParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SandboxID   pgtype.Text `json:"sandbox_id"`
}

func (q *Queries) MarkWorkspaceSandboxRunning(ctx context.Context, arg MarkWorkspaceSandboxRunningParams) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, markWorkspaceSandboxRunning, arg.WorkspaceID, arg.SandboxID)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceSandboxTerminated = `-- name: MarkWorkspaceSandboxTerminated :one
UPDATE workspace_sandbox
SET status = 'terminated',
    sandbox_id = NULL,
    updated_at = now()
WHERE workspace_id = $1
RETURNING workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
`

func (q *Queries) MarkWorkspaceSandboxTerminated(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, markWorkspaceSandboxTerminated, workspaceID)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceSandboxUnhealthy = `-- name: MarkWorkspaceSandboxUnhealthy :one
UPDATE workspace_sandbox
SET status = 'unhealthy',
    last_health_check_at = now(),
    error_message = $2,
    updated_at = now()
WHERE workspace_id = $1
RETURNING workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
`

type MarkWorkspaceSandboxUnhealthyParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkWorkspaceSandboxUnhealthy(ctx context.Context, arg MarkWorkspaceSandboxUnhealthyParams) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, markWorkspaceSandboxUnhealthy, arg.WorkspaceID, arg.ErrorMessage)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchWorkspaceSandboxSeen = `-- name: TouchWorkspaceSandboxSeen :one
UPDATE workspace_sandbox
SET last_health_check_at = now(),
    last_seen_at = now(),
    updated_at = now()
WHERE workspace_id = $1
RETURNING workspace_id, sandbox_id, volume_name, status, last_health_check_at, last_seen_at, error_message, created_at, updated_at
`

func (q *Queries) TouchWorkspaceSandboxSeen(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceSandbox, error) {
	row := q.db.QueryRow(ctx, touchWorkspaceSandboxSeen, workspaceID)
	var i WorkspaceSandbox
	err := row.Scan(
		&i.WorkspaceID,
		&i.SandboxID,
		&i.VolumeName,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.LastSeenAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
