// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandbox_job.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSandboxJob = `-- name: CreateSandboxJob :one
INSERT INTO sandbox_job (
    workspace_id,
    target_node_id,
    generation_job_id,
    job_type,
    operation_type,
    status,
    input
) VALUES (
    $1, $2, $3, $4, $5, 'pending', $6
) RETURNING id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
`

type CreateSandboxJobParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	TargetNodeID    pgtype.UUID `json:"target_node_id"`
	GenerationJobID pgtype.UUID `json:"generation_job_id"`
	JobType         string      `json:"job_type"`
	OperationType   string      `json:"operation_type"`
	Input           []byte      `json:"input"`
}

func (q *Queries) CreateSandboxJob(ctx context.Context, arg CreateSandboxJobParams) (SandboxJob, error) {
	row := q.db.QueryRow(ctx, createSandboxJob,
		arg.WorkspaceID,
		arg.TargetNodeID,
		arg.GenerationJobID,
		arg.JobType,
		arg.OperationType,
		arg.Input,
	)
	var i SandboxJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.GenerationJobID,
		&i.JobType,
		&i.OperationType,
		&i.Status,
		&i.SandboxID,
		&i.Command,
		&i.Cwd,
		&i.Input,
		&i.Output,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.DurationMs,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSandboxJobByID = `-- name: GetSandboxJobByID :one
SELECT id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
FROM sandbox_job
WHERE id = $1
`

func (q *Queries) GetSandboxJobByID(ctx context.Context, id pgtype.UUID) (SandboxJob, error) {
	row := q.db.QueryRow(ctx, getSandboxJobByID, id)
	var i SandboxJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.GenerationJobID,
		&i.JobType,
		&i.OperationType,
		&i.Status,
		&i.SandboxID,
		&i.Command,
		&i.Cwd,
		&i.Input,
		&i.Output,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.DurationMs,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkSandboxJobGenerationJob = `-- name: LinkSandboxJobGenerationJob :one
UPDATE sandbox_job
SET generation_job_id = $2
WHERE id = $1
RETURNING id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
`

type LinkSandboxJobGenerationJobParams struct {
	ID              pgtype.UUID `json:"id"`
	GenerationJobID pgtype.UUID `json:"generation_job_id"`
}

func (q *Queries) LinkSandboxJobGenerationJob(ctx context.Context, arg LinkSandboxJobGenerationJobParams) (SandboxJob, error) {
	row := q.db.QueryRow(ctx, linkSandboxJobGenerationJob, arg.ID, arg.GenerationJobID)
	var i SandboxJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.GenerationJobID,
		&i.JobType,
		&i.OperationType,
		&i.Status,
		&i.SandboxID,
		&i.Command,
		&i.Cwd,
		&i.Input,
		&i.Output,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.DurationMs,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSandboxJobsByGenerationJob = `-- name: ListSandboxJobsByGenerationJob :many
SELECT id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
FROM sandbox_job
WHERE generation_job_id = $1
ORDER BY created_at
`

func (q *Queries) ListSandboxJobsByGenerationJob(ctx context.Context, generationJobID pgtype.UUID) ([]SandboxJob, error) {
	rows, err := q.db.Query(ctx, listSandboxJobsByGenerationJob, generationJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxJob{}
	for rows.Next() {
		var i SandboxJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetNodeID,
			&i.GenerationJobID,
			&i.JobType,
			&i.OperationType,
			&i.Status,
			&i.SandboxID,
			&i.Command,
			&i.Cwd,
			&i.Input,
			&i.Output,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.DurationMs,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxJobsByTargetNode = `-- name: ListSandboxJobsByTargetNode :many
SELECT id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
FROM sandbox_job
WHERE target_node_id = $1
ORDER BY created_at
`

func (q *Queries) ListSandboxJobsByTargetNode(ctx context.Context, targetNodeID pgtype.UUID) ([]SandboxJob, error) {
	rows, err := q.db.Query(ctx, listSandboxJobsByTargetNode, targetNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxJob{}
	for rows.Next() {
		var i SandboxJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetNodeID,
			&i.GenerationJobID,
			&i.JobType,
			&i.OperationType,
			&i.Status,
			&i.SandboxID,
			&i.Command,
			&i.Cwd,
			&i.Input,
			&i.Output,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.DurationMs,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxJobsByWorkspace = `-- name: ListSandboxJobsByWorkspace :many
SELECT id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
FROM sandbox_job
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListSandboxJobsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]SandboxJob, error) {
	rows, err := q.db.Query(ctx, listSandboxJobsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxJob{}
	for rows.Next() {
		var i SandboxJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetNodeID,
			&i.GenerationJobID,
			&i.JobType,
			&i.OperationType,
			&i.Status,
			&i.SandboxID,
			&i.Command,
			&i.Cwd,
			&i.Input,
			&i.Output,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.DurationMs,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSandboxJobFailed = `-- name: MarkSandboxJobFailed :one
UPDATE sandbox_job
SET status = 'failed',
    output = $2,
    exit_code = $3,
    stdout = $4,
    stderr = $5,
    duration_ms = $6,
    error_code = $7,
    error_message = $8,
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
`

type MarkSandboxJobFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	Output       []byte      `json:"output"`
	ExitCode     pgtype.Int4 `json:"exit_code"`
	Stdout       string      `json:"stdout"`
	Stderr       string      `json:"stderr"`
	DurationMs   int32       `json:"duration_ms"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkSandboxJobFailed(ctx context.Context, arg MarkSandboxJobFailedParams) (SandboxJob, error) {
	row := q.db.QueryRow(ctx, markSandboxJobFailed,
		arg.ID,
		arg.Output,
		arg.ExitCode,
		arg.Stdout,
		arg.Stderr,
		arg.DurationMs,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i SandboxJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.GenerationJobID,
		&i.JobType,
		&i.OperationType,
		&i.Status,
		&i.SandboxID,
		&i.Command,
		&i.Cwd,
		&i.Input,
		&i.Output,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.DurationMs,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markSandboxJobRunning = `-- name: MarkSandboxJobRunning :one
UPDATE sandbox_job
SET status = 'running',
    sandbox_id = $2,
    command = $3,
    cwd = $4,
    started_at = now()
WHERE id = $1
RETURNING id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
`

type MarkSandboxJobRunningParams struct {
	ID        pgtype.UUID `json:"id"`
	SandboxID pgtype.Text `json:"sandbox_id"`
	Command   string      `json:"command"`
	Cwd       string      `json:"cwd"`
}

func (q *Queries) MarkSandboxJobRunning(ctx context.Context, arg MarkSandboxJobRunningParams) (SandboxJob, error) {
	row := q.db.QueryRow(ctx, markSandboxJobRunning,
		arg.ID,
		arg.SandboxID,
		arg.Command,
		arg.Cwd,
	)
	var i SandboxJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.GenerationJobID,
		&i.JobType,
		&i.OperationType,
		&i.Status,
		&i.SandboxID,
		&i.Command,
		&i.Cwd,
		&i.Input,
		&i.Output,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.DurationMs,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markSandboxJobSucceeded = `-- name: MarkSandboxJobSucceeded :one
UPDATE sandbox_job
SET status = 'succeeded',
    output = $2,
    exit_code = $3,
    stdout = $4,
    stderr = $5,
    duration_ms = $6,
    completed_at = now()
WHERE id = $1
RETURNING id, workspace_id, target_node_id, generation_job_id, job_type, operation_type, status, sandbox_id, command, cwd, input, output, exit_code, stdout, stderr, duration_ms, error_code, error_message, started_at, completed_at, created_at
`

type MarkSandboxJobSucceededParams struct {
	ID         pgtype.UUID `json:"id"`
	Output     []byte      `json:"output"`
	ExitCode   pgtype.Int4 `json:"exit_code"`
	Stdout     string      `json:"stdout"`
	Stderr     string      `json:"stderr"`
	DurationMs int32       `json:"duration_ms"`
}

func (q *Queries) MarkSandboxJobSucceeded(ctx context.Context, arg MarkSandboxJobSucceededParams) (SandboxJob, error) {
	row := q.db.QueryRow(ctx, markSandboxJobSucceeded,
		arg.ID,
		arg.Output,
		arg.ExitCode,
		arg.Stdout,
		arg.Stderr,
		arg.DurationMs,
	)
	var i SandboxJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetNodeID,
		&i.GenerationJobID,
		&i.JobType,
		&i.OperationType,
		&i.Status,
		&i.SandboxID,
		&i.Command,
		&i.Cwd,
		&i.Input,
		&i.Output,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.DurationMs,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
