// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shot_dependency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShotDependency = `-- name: CreateShotDependency :one
INSERT INTO shot_dependency (
    workspace_id,
    from_shot_id,
    to_shot_id,
    dependency_type,
    required_artifact,
    injection_role,
    blocking_phase,
    stale_policy,
    reason,
    semantic_key,
    display_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, workspace_id, from_shot_id, to_shot_id, dependency_type, required_artifact, injection_role, blocking_phase, stale_policy, reason, created_at, semantic_key, display_name
`

type CreateShotDependencyParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	FromShotID       pgtype.UUID `json:"from_shot_id"`
	ToShotID         pgtype.UUID `json:"to_shot_id"`
	DependencyType   string      `json:"dependency_type"`
	RequiredArtifact string      `json:"required_artifact"`
	InjectionRole    string      `json:"injection_role"`
	BlockingPhase    string      `json:"blocking_phase"`
	StalePolicy      string      `json:"stale_policy"`
	Reason           string      `json:"reason"`
	SemanticKey      string      `json:"semantic_key"`
	DisplayName      string      `json:"display_name"`
}

func (q *Queries) CreateShotDependency(ctx context.Context, arg CreateShotDependencyParams) (ShotDependency, error) {
	row := q.db.QueryRow(ctx, createShotDependency,
		arg.WorkspaceID,
		arg.FromShotID,
		arg.ToShotID,
		arg.DependencyType,
		arg.RequiredArtifact,
		arg.InjectionRole,
		arg.BlockingPhase,
		arg.StalePolicy,
		arg.Reason,
		arg.SemanticKey,
		arg.DisplayName,
	)
	var i ShotDependency
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FromShotID,
		&i.ToShotID,
		&i.DependencyType,
		&i.RequiredArtifact,
		&i.InjectionRole,
		&i.BlockingPhase,
		&i.StalePolicy,
		&i.Reason,
		&i.CreatedAt,
		&i.SemanticKey,
		&i.DisplayName,
	)
	return i, err
}

const deleteShotDependenciesByWorkspace = `-- name: DeleteShotDependenciesByWorkspace :exec
DELETE FROM shot_dependency
WHERE workspace_id = $1
`

func (q *Queries) DeleteShotDependenciesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShotDependenciesByWorkspace, workspaceID)
	return err
}

const deleteShotDependenciesForShot = `-- name: DeleteShotDependenciesForShot :exec
DELETE FROM shot_dependency
WHERE workspace_id = $1
  AND (from_shot_id = $2 OR to_shot_id = $2)
`

type DeleteShotDependenciesForShotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromShotID  pgtype.UUID `json:"from_shot_id"`
}

func (q *Queries) DeleteShotDependenciesForShot(ctx context.Context, arg DeleteShotDependenciesForShotParams) error {
	_, err := q.db.Exec(ctx, deleteShotDependenciesForShot, arg.WorkspaceID, arg.FromShotID)
	return err
}

const listShotDependenciesByWorkspace = `-- name: ListShotDependenciesByWorkspace :many
SELECT id, workspace_id, from_shot_id, to_shot_id, dependency_type, required_artifact, injection_role, blocking_phase, stale_policy, reason, created_at, semantic_key, display_name
FROM shot_dependency
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListShotDependenciesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ShotDependency, error) {
	rows, err := q.db.Query(ctx, listShotDependenciesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShotDependency{}
	for rows.Next() {
		var i ShotDependency
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromShotID,
			&i.ToShotID,
			&i.DependencyType,
			&i.RequiredArtifact,
			&i.InjectionRole,
			&i.BlockingPhase,
			&i.StalePolicy,
			&i.Reason,
			&i.CreatedAt,
			&i.SemanticKey,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
