// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline_plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimelinePlan = `-- name: CreateTimelinePlan :one
INSERT INTO timeline_plan (
    workspace_id,
    source_storyboard_node_id,
    output_node_id,
    production_job_id,
    artifact_version_id,
    sandbox_job_id,
    status,
    template_key,
    plan_json,
    render_settings,
    result,
    error_message,
    created_by_role,
    created_by_task_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, workspace_id, source_storyboard_node_id, output_node_id, production_job_id, artifact_version_id, sandbox_job_id, status, template_key, plan_json, render_settings, result, error_message, created_by_role, created_by_task_id, created_at, updated_at
`

type CreateTimelinePlanParams struct {
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	SourceStoryboardNodeID pgtype.UUID `json:"source_storyboard_node_id"`
	OutputNodeID           pgtype.UUID `json:"output_node_id"`
	ProductionJobID        pgtype.UUID `json:"production_job_id"`
	ArtifactVersionID      pgtype.UUID `json:"artifact_version_id"`
	SandboxJobID           pgtype.UUID `json:"sandbox_job_id"`
	Status                 string      `json:"status"`
	TemplateKey            string      `json:"template_key"`
	PlanJson               []byte      `json:"plan_json"`
	RenderSettings         []byte      `json:"render_settings"`
	Result                 []byte      `json:"result"`
	ErrorMessage           pgtype.Text `json:"error_message"`
	CreatedByRole          string      `json:"created_by_role"`
	CreatedByTaskID        pgtype.UUID `json:"created_by_task_id"`
}

func (q *Queries) CreateTimelinePlan(ctx context.Context, arg CreateTimelinePlanParams) (TimelinePlan, error) {
	row := q.db.QueryRow(ctx, createTimelinePlan,
		arg.WorkspaceID,
		arg.SourceStoryboardNodeID,
		arg.OutputNodeID,
		arg.ProductionJobID,
		arg.ArtifactVersionID,
		arg.SandboxJobID,
		arg.Status,
		arg.TemplateKey,
		arg.PlanJson,
		arg.RenderSettings,
		arg.Result,
		arg.ErrorMessage,
		arg.CreatedByRole,
		arg.CreatedByTaskID,
	)
	var i TimelinePlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceStoryboardNodeID,
		&i.OutputNodeID,
		&i.ProductionJobID,
		&i.ArtifactVersionID,
		&i.SandboxJobID,
		&i.Status,
		&i.TemplateKey,
		&i.PlanJson,
		&i.RenderSettings,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCompletedTimelinePlanByWorkspace = `-- name: GetLatestCompletedTimelinePlanByWorkspace :one
SELECT id, workspace_id, source_storyboard_node_id, output_node_id, production_job_id, artifact_version_id, sandbox_job_id, status, template_key, plan_json, render_settings, result, error_message, created_by_role, created_by_task_id, created_at, updated_at FROM timeline_plan
WHERE workspace_id = $1
  AND status = 'completed'
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestCompletedTimelinePlanByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (TimelinePlan, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedTimelinePlanByWorkspace, workspaceID)
	var i TimelinePlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceStoryboardNodeID,
		&i.OutputNodeID,
		&i.ProductionJobID,
		&i.ArtifactVersionID,
		&i.SandboxJobID,
		&i.Status,
		&i.TemplateKey,
		&i.PlanJson,
		&i.RenderSettings,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestTimelinePlanByWorkspace = `-- name: GetLatestTimelinePlanByWorkspace :one
SELECT id, workspace_id, source_storyboard_node_id, output_node_id, production_job_id, artifact_version_id, sandbox_job_id, status, template_key, plan_json, render_settings, result, error_message, created_by_role, created_by_task_id, created_at, updated_at FROM timeline_plan
WHERE workspace_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestTimelinePlanByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (TimelinePlan, error) {
	row := q.db.QueryRow(ctx, getLatestTimelinePlanByWorkspace, workspaceID)
	var i TimelinePlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceStoryboardNodeID,
		&i.OutputNodeID,
		&i.ProductionJobID,
		&i.ArtifactVersionID,
		&i.SandboxJobID,
		&i.Status,
		&i.TemplateKey,
		&i.PlanJson,
		&i.RenderSettings,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimelinePlan = `-- name: GetTimelinePlan :one
SELECT id, workspace_id, source_storyboard_node_id, output_node_id, production_job_id, artifact_version_id, sandbox_job_id, status, template_key, plan_json, render_settings, result, error_message, created_by_role, created_by_task_id, created_at, updated_at FROM timeline_plan
WHERE id = $1
`

func (q *Queries) GetTimelinePlan(ctx context.Context, id pgtype.UUID) (TimelinePlan, error) {
	row := q.db.QueryRow(ctx, getTimelinePlan, id)
	var i TimelinePlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceStoryboardNodeID,
		&i.OutputNodeID,
		&i.ProductionJobID,
		&i.ArtifactVersionID,
		&i.SandboxJobID,
		&i.Status,
		&i.TemplateKey,
		&i.PlanJson,
		&i.RenderSettings,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimelinePlansByWorkspace = `-- name: ListTimelinePlansByWorkspace :many
SELECT id, workspace_id, source_storyboard_node_id, output_node_id, production_job_id, artifact_version_id, sandbox_job_id, status, template_key, plan_json, render_settings, result, error_message, created_by_role, created_by_task_id, created_at, updated_at FROM timeline_plan
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListTimelinePlansByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListTimelinePlansByWorkspace(ctx context.Context, arg ListTimelinePlansByWorkspaceParams) ([]TimelinePlan, error) {
	rows, err := q.db.Query(ctx, listTimelinePlansByWorkspace, arg.WorkspaceID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelinePlan{}
	for rows.Next() {
		var i TimelinePlan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceStoryboardNodeID,
			&i.OutputNodeID,
			&i.ProductionJobID,
			&i.ArtifactVersionID,
			&i.SandboxJobID,
			&i.Status,
			&i.TemplateKey,
			&i.PlanJson,
			&i.RenderSettings,
			&i.Result,
			&i.ErrorMessage,
			&i.CreatedByRole,
			&i.CreatedByTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimelinePlanStatus = `-- name: UpdateTimelinePlanStatus :one
UPDATE timeline_plan
SET
    status = $1,
    production_job_id = COALESCE($2, production_job_id),
    artifact_version_id = COALESCE($3, artifact_version_id),
    sandbox_job_id = COALESCE($4, sandbox_job_id),
    result = COALESCE($5, result),
    error_message = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, workspace_id, source_storyboard_node_id, output_node_id, production_job_id, artifact_version_id, sandbox_job_id, status, template_key, plan_json, render_settings, result, error_message, created_by_role, created_by_task_id, created_at, updated_at
`

type UpdateTimelinePlanStatusParams struct {
	Status            string      `json:"status"`
	ProductionJobID   pgtype.UUID `json:"production_job_id"`
	ArtifactVersionID pgtype.UUID `json:"artifact_version_id"`
	SandboxJobID      pgtype.UUID `json:"sandbox_job_id"`
	Result            []byte      `json:"result"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTimelinePlanStatus(ctx context.Context, arg UpdateTimelinePlanStatusParams) (TimelinePlan, error) {
	row := q.db.QueryRow(ctx, updateTimelinePlanStatus,
		arg.Status,
		arg.ProductionJobID,
		arg.ArtifactVersionID,
		arg.SandboxJobID,
		arg.Result,
		arg.ErrorMessage,
		arg.ID,
	)
	var i TimelinePlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceStoryboardNodeID,
		&i.OutputNodeID,
		&i.ProductionJobID,
		&i.ArtifactVersionID,
		&i.SandboxJobID,
		&i.Status,
		&i.TemplateKey,
		&i.PlanJson,
		&i.RenderSettings,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedByRole,
		&i.CreatedByTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
